In [84]:
import pandas as pd

# Import raw data for preprocessing

In [85]:
filename = "raw-website/FH3-cars-list"
tables = pd.read_html(filename + ".htm")
df = tables[1]
df.head()

,Vehicle,📅,Value,Sp,Ha,Ac,La,Br,PI
0,Abarth 500 esseesse 2010Autoshow,NaN,"35,000 CRHot Hatch",5.0,5.8,6.4,6.7,5.9,C563
1,Abarth 595 esseesse 1968Autoshow,NaN,"35,000 CRCult Classics",3.0,3.6,3.0,3.2,3.0,D100
2,Abarth 695 Biposto 2016Autoshow,NaN,"48,000 CRHot Hatch",5.0,6.6,6.8,6.9,7.7,B625
3,Abarth Fiat 131 1980Autoshow,NaN,"38,000 CRClassic Rally",4.8,4.9,6.1,6.3,4.2,D477
4,Acura Integra Type-R 2001Autoshow,NaN,"25,000 CRRetro Hot Hatch",5.7,5.8,6.6,6.8,5.5,C571

## Remove redundant columns

In [86]:
columns_to_drop = [1]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,PI
0,Abarth 500 esseesse 2010Autoshow,"35,000 CRHot Hatch",5.0,5.8,6.4,6.7,5.9,C563
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCult Classics",3.0,3.6,3.0,3.2,3.0,D100
2,Abarth 695 Biposto 2016Autoshow,"48,000 CRHot Hatch",5.0,6.6,6.8,6.9,7.7,B625
3,Abarth Fiat 131 1980Autoshow,"38,000 CRClassic Rally",4.8,4.9,6.1,6.3,4.2,D477
4,Acura Integra Type-R 2001Autoshow,"25,000 CRRetro Hot Hatch",5.7,5.8,6.6,6.8,5.5,C571

## Expand abbreviated columns

In [87]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,PI
0,Abarth 500 esseesse 2010Autoshow,"35,000 CRHot Hatch",5.0,5.8,6.4,6.7,5.9,C563
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCult Classics",3.0,3.6,3.0,3.2,3.0,D100
2,Abarth 695 Biposto 2016Autoshow,"48,000 CRHot Hatch",5.0,6.6,6.8,6.9,7.7,B625
3,Abarth Fiat 131 1980Autoshow,"38,000 CRClassic Rally",4.8,4.9,6.1,6.3,4.2,D477
4,Acura Integra Type-R 2001Autoshow,"25,000 CRRetro Hot Hatch",5.7,5.8,6.6,6.8,5.5,C571

In [88]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   524 non-null    str
 1   Value     524 non-null    str
 2   Speed     524 non-null    float64
 3   Handling  524 non-null    float64
 4   Accel     524 non-null    float64
 5   Launch    524 non-null    float64
 6   Braking   524 non-null    float64
 7   PI        524 non-null    str
dtypes: float64(5), str(3)
memory usage: 32.9 KB

## Remove stat columns from df_lite

In [89]:
columns_to_drop = [2, 3, 4, 5, 6]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                             Vehicle                     Value    PI
0   Abarth 500 esseesse 2010Autoshow        35,000 CRHot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow    35,000 CRCult Classics  D100
2    Abarth 695 Biposto 2016Autoshow        48,000 CRHot Hatch  B625
3       Abarth Fiat 131 1980Autoshow    38,000 CRClassic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25,000 CRRetro Hot Hatch  C571

## Split original Value column into Value and Car Type

In [90]:
df_lite[["Value", "Car Type"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].str.replace("?", "0")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                             Vehicle  Value         Car Type    PI
0   Abarth 500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow  35000    Cult Classics  D100
2    Abarth 695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3       Abarth Fiat 131 1980Autoshow  38000    Classic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

## Split original Vehicle column into Brand and Vehicle

In [91]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

    Brand                      Vehicle  Value         Car Type    PI
0  Abarth    500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1  Abarth    595 esseesse 1968Autoshow  35000    Cult Classics  D100
2  Abarth     695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3  Abarth        Fiat 131 1980Autoshow  38000    Classic Rally  D477
4   Acura  Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

In [92]:
df_lite[["Vehicle", "Collection"]] = df_lite["Vehicle"].str.split(r'(?=Autoshow)|(?=Barn)|(?=Wheelspin)|(?=Forzathon)|(?=Gifted)', n=1,
                                                                  expand=True)
df_lite.head()

    Brand              Vehicle  Value         Car Type    PI Collection
0  Abarth    500 esseesse 2010  35000        Hot Hatch  C563   Autoshow
1  Abarth    595 esseesse 1968  35000    Cult Classics  D100   Autoshow
2  Abarth     695 Biposto 2016  48000        Hot Hatch  B625   Autoshow
3  Abarth        Fiat 131 1980  38000    Classic Rally  D477   Autoshow
4   Acura  Integra Type-R 2001  25000  Retro Hot Hatch  C571   Autoshow

In [94]:
df_lite["Collection"].value_counts()

Collection
Autoshow                                       349
Wheelspin                                       28
Forzathon                                       26
Barn Find                                       17
Autoshow (DLC: All-Stars Car Pack)              11
Autoshow (DLC: Hot Wheels Expansion)             9
Autoshow (DLC: Blizzard Mountain Expansion)      9
Autoshow (DLC: Duracell Car Pack)                8
Autoshow (DLC: Porsche Car Pack)                 8
Autoshow (DLC: Alpinestars Car Pack)             7
Autoshow (DLC: Mountain Dew Car Pack)            7
Autoshow (DLC: Playseat Car Pack)                7
Autoshow (DLC: The Smoking Tire Car Pack)        7
Autoshow (DLC: Rockstar Energy Car Pack)         7
Autoshow (DLC: Logitech G Car Pack)              7
Autoshow (DLC: Hoonigan Car Pack)                7
Autoshow (DLC: VIP)                              5
Barn Find (Forzathon)                            2
Gifted                                           2
Barn Find (DLC: Hot Wheels Expansion)            1
Name: count, dtype: int64

## Create Boolean columns for method of obtaining

In [9]:
df_lite["Autoshow"] = df_lite["Vehicle"].str.contains("Autoshow")
df_lite["Barn Find"] = df_lite["Vehicle"].str.contains("Barn Find")
df_lite["Wheelspin"] = df_lite["Vehicle"].str.contains("Wheelspin")
df_lite["Forzathon"] = df_lite["Vehicle"].str.contains("Forzathon")
df_lite["DLC"] = df_lite["Vehicle"].str.contains("DLC")
df_lite.head()

,Brand,Vehicle,Value,Car Type,PI,Autoshow,Barn Find,Wheelspin,Forzathon,DLC
0,Abarth,500 esseesse 2010Autoshow,35000,Hot Hatch,C563,True,False,False,False,False
1,Abarth,595 esseesse 1968Autoshow,35000,Cult Classics,D100,True,False,False,False,False
2,Abarth,695 Biposto 2016Autoshow,48000,Hot Hatch,B625,True,False,False,False,False
3,Abarth,Fiat 131 1980Autoshow,38000,Classic Rally,D477,True,False,False,False,False
4,Acura,Integra Type-R 2001Autoshow,25000,Retro Hot Hatch,C571,True,False,False,False,False

In [10]:
df_lite.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Brand      524 non-null    str
 1   Vehicle    524 non-null    str
 2   Value      524 non-null    int64
 3   Car Type   524 non-null    str
 4   PI         524 non-null    str
 5   Autoshow   524 non-null    bool
 6   Barn Find  524 non-null    bool
 7   Wheelspin  524 non-null    bool
 8   Forzathon  524 non-null    bool
 9   DLC        524 non-null    bool
dtypes: bool(5), int64(1), str(4)
memory usage: 23.2 KB

In [11]:
# Error checking
df_verify = df_lite.loc[(df_lite["Autoshow"] == False) &
                        (df_lite["Barn Find"] == False) &
                        (df_lite["Wheelspin"] == False) &
                        (df_lite["Forzathon"] == False) &
                        (df_lite["DLC"] == False)]
df_verify.head()

,Brand,Vehicle,Value,Car Type,PI,Autoshow,Barn Find,Wheelspin,Forzathon,DLC
459,Quartz,Regalia 723Gifted,475000,GT Cars,A702,False,False,False,False,False
496,Tamo,Racemo 2017Gifted,600000,Asian Sports Cars,C589,False,False,False,False,False

## Filter to cars that are obtainable via Autoshow and Wheelspin

In [ ]:
df_sort = df_lite[df_lite["Vehicle"].str.contains("Autoshow, Wheelspin")]
df_sort.head()

In [ ]:
df_sort.info()

## Sort vehicles by brand, then lowest to highest cost

In [ ]:
#df_sort = df_sort.sort_values(["Vehicle", "Value"], ascending=[True, True])
df_sort = df_sort.sort_values(["Brand", "Value"], ascending=[True, True])
#df_sort = df_sort[df_sort["Value"] <= 500000]
df_sort.head()

In [ ]:
df_sort.info()

### Convert dataframes to csv

In [ ]:
df_sort.to_csv(filename + "-sorted" + ".csv", index=False)

In [ ]:
df_lite.to_csv(filename + ".csv", index=False)

## Filter to Wheelspin-exclusive cars

In [ ]:
df_wheelspin = df_lite.loc[(df_lite["Autoshow"] == False) & (df_lite["Wheelspin"] == True)]
df_wheelspin = df_wheelspin.drop(columns=["Hard to Find", "Aftermarket Car"])
df_wheelspin.head()

In [ ]:
df_wheelspin["Rarity"].value_counts()

### Associate each rarity with numerical value

In [ ]:
rarity_dict = {"COMMON": 1, "RARE": 2, "EPIC": 3, "LEGENDARY": 4, "FORZA EDITION": 5}
df_wheelspin["Rarity Value"] = df_wheelspin["Rarity"].map(rarity_dict)
df_wheelspin.head()

### Sort Wheelspin-exclusives according to Rarity

In [ ]:
df_wheelspin = df_wheelspin.sort_values(["Rarity Value", "Brand"], ascending=[True, True])
df_wheelspin.head()

In [ ]:
df_wheelspin = df_wheelspin.drop(columns=["Rarity Value"])
df_wheelspin.info()

### Dataframe to csv

In [ ]:
df_wheelspin.to_csv(filename + "-wheelspin" + ".csv", index=False)

In [ ]:
df_test = df_lite[(df_lite["Rarity"] == "COMMON") & (df_lite["Wheelspin"] == True)]
df_test = df_test.sort_values(["Value"], ascending=False)
df_test.head()