In [1]:
import pandas as pd

# Import raw data for preprocessing

In [2]:
filename = "FH3-cars-list"
tables = pd.read_html("raw-website/" + filename + ".htm")
df = tables[1]
df.head(10)

,Vehicle,📅,Value,Sp,Ha,Ac,La,Br,PI
0,Abarth 500 esseesse 2010Autoshow,NaN,"35,000 CRHot Hatch",5.0,5.8,6.4,6.7,5.9,C563
1,Abarth 595 esseesse 1968Autoshow,NaN,"35,000 CRCult Classics",3.0,3.6,3.0,3.2,3.0,D100
2,Abarth 695 Biposto 2016Autoshow,NaN,"48,000 CRHot Hatch",5.0,6.6,6.8,6.9,7.7,B625
3,Abarth Fiat 131 1980Autoshow,NaN,"38,000 CRClassic Rally",4.8,4.9,6.1,6.3,4.2,D477
4,Acura Integra Type-R 2001Autoshow,NaN,"25,000 CRRetro Hot Hatch",5.7,5.8,6.6,6.8,5.5,C571
5,Acura NSX 2017Autoshow (DLC: Alpinestars Car P...,NaN,"170,000 CRModern Supercars",7.0,7.6,9.0,10.0,9.3,S1868
6,Acura RSX Type-S 2002Autoshow,NaN,"25,000 CRHot Hatch",5.7,5.8,6.6,6.7,5.5,C568
7,Alfa Romeo 4C 2014Autoshow,NaN,"74,000 CREuropean Sports Cars",6.0,7.0,8.0,8.5,8.0,A758
8,Alfa Romeo 8C Competizione 2007Autoshow,NaN,"300,000 CRGT Cars",7.2,6.8,8.1,8.1,7.8,A766
9,Alfa Romeo 33 Stradale 1968Autoshow,NaN,"10,000,000 CRClassic Racers",6.4,6.0,8.3,8.0,6.1,B648

## Remove redundant columns

In [3]:
columns_to_drop = [1]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,PI
0,Abarth 500 esseesse 2010Autoshow,"35,000 CRHot Hatch",5.0,5.8,6.4,6.7,5.9,C563
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCult Classics",3.0,3.6,3.0,3.2,3.0,D100
2,Abarth 695 Biposto 2016Autoshow,"48,000 CRHot Hatch",5.0,6.6,6.8,6.9,7.7,B625
3,Abarth Fiat 131 1980Autoshow,"38,000 CRClassic Rally",4.8,4.9,6.1,6.3,4.2,D477
4,Acura Integra Type-R 2001Autoshow,"25,000 CRRetro Hot Hatch",5.7,5.8,6.6,6.8,5.5,C571

## Expand abbreviated columns

In [4]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,PI
0,Abarth 500 esseesse 2010Autoshow,"35,000 CRHot Hatch",5.0,5.8,6.4,6.7,5.9,C563
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCult Classics",3.0,3.6,3.0,3.2,3.0,D100
2,Abarth 695 Biposto 2016Autoshow,"48,000 CRHot Hatch",5.0,6.6,6.8,6.9,7.7,B625
3,Abarth Fiat 131 1980Autoshow,"38,000 CRClassic Rally",4.8,4.9,6.1,6.3,4.2,D477
4,Acura Integra Type-R 2001Autoshow,"25,000 CRRetro Hot Hatch",5.7,5.8,6.6,6.8,5.5,C571

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   524 non-null    str
 1   Value     524 non-null    str
 2   Speed     524 non-null    float64
 3   Handling  524 non-null    float64
 4   Accel     524 non-null    float64
 5   Launch    524 non-null    float64
 6   Braking   524 non-null    float64
 7   PI        524 non-null    str
dtypes: float64(5), str(3)
memory usage: 32.9 KB

## Remove stat columns from df_lite

In [6]:
columns_to_drop = [2, 3, 4, 5, 6]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                             Vehicle                     Value    PI
0   Abarth 500 esseesse 2010Autoshow        35,000 CRHot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow    35,000 CRCult Classics  D100
2    Abarth 695 Biposto 2016Autoshow        48,000 CRHot Hatch  B625
3       Abarth Fiat 131 1980Autoshow    38,000 CRClassic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25,000 CRRetro Hot Hatch  C571

## Split original Value column into Value and Car Type

In [7]:
df_lite.iloc[df_lite["Value"].str.contains("?", regex=False)].head()

Empty DataFrame
Columns: [Vehicle, Value, PI]
Index: []

In [8]:
df_lite[["Value", "Car Type"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                             Vehicle  Value         Car Type    PI
0   Abarth 500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow  35000    Cult Classics  D100
2    Abarth 695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3       Abarth Fiat 131 1980Autoshow  38000    Classic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

## Split original Vehicle column into Brand and Vehicle

In [9]:
df_lite.iloc[df_lite["Vehicle"].str.contains("_")].head()

Empty DataFrame
Columns: [Vehicle, Value, Car Type, PI]
Index: []

### Isolate rows for 2-word vehicle brand names

In [10]:
df1 = df_lite.iloc[df_lite["Vehicle"].str.contains("Alfa Romeo|Alumi Craft|Aston Martin|Baldwin Motorsports|Land Rover|Local Motors|RJ Anderson|Spania GTA|W Motors")]
df1 = df1.loc[~df1["Vehicle"].str.contains("Hoonigan")]
df1.head()

,Vehicle,Value,Car Type,PI
7,Alfa Romeo 4C 2014Autoshow,74000,European Sports Cars,A758
8,Alfa Romeo 8C Competizione 2007Autoshow,300000,GT Cars,A766
9,Alfa Romeo 33 Stradale 1968Autoshow,10000000,Classic Racers,B648
10,Alfa Romeo 155 Q4 1992Autoshow,25000,Retro Saloons,C578
11,Alfa Romeo Giulia Sprint GTA Stradale 1965Auto...,300000,Rare Classics,D252

In [11]:
df1["Vehicle"] = df1["Vehicle"].str.replace(" ", "_", n=1)
df1.head()

,Vehicle,Value,Car Type,PI
7,Alfa_Romeo 4C 2014Autoshow,74000,European Sports Cars,A758
8,Alfa_Romeo 8C Competizione 2007Autoshow,300000,GT Cars,A766
9,Alfa_Romeo 33 Stradale 1968Autoshow,10000000,Classic Racers,B648
10,Alfa_Romeo 155 Q4 1992Autoshow,25000,Retro Saloons,C578
11,Alfa_Romeo Giulia Sprint GTA Stradale 1965Auto...,300000,Rare Classics,D252

### Separate filtering for Hot Wheels

In [12]:
df_hw = df_lite.iloc[df_lite["Vehicle"].str.contains("Hot Wheels")]
df_hw = df_hw.loc[~df_hw["Vehicle"].str.contains("Chrysler|Ford|Jeep|Pagani|Toyota|Zenvo")]
df_hw.head()

,Vehicle,Value,Car Type,PI
255,Hot Wheels Bone Shaker 2005Autoshow (DLC: Hot ...,150000,Rods and Customs,A797
256,Hot Wheels Mustang 2005Autoshow (DLC: Hot Whee...,50000,Extreme Track Toys,S1900
257,Hot Wheels Rip Rod 2012Autoshow (DLC: Hot Whee...,75000,Buggies,B700
258,Hot Wheels Twin Mill 1969Autoshow (DLC: Hot Wh...,110000,Rods and Customs,S1900

In [13]:
df_hw["Vehicle"] = df_hw["Vehicle"].str.replace(" ", "_", n=1)
df_hw.head()

,Vehicle,Value,Car Type,PI
255,Hot_Wheels Bone Shaker 2005Autoshow (DLC: Hot ...,150000,Rods and Customs,A797
256,Hot_Wheels Mustang 2005Autoshow (DLC: Hot Whee...,50000,Extreme Track Toys,S1900
257,Hot_Wheels Rip Rod 2012Autoshow (DLC: Hot Whee...,75000,Buggies,B700
258,Hot_Wheels Twin Mill 1969Autoshow (DLC: Hot Wh...,110000,Rods and Customs,S1900

### Isolate rows for 3-word vehicle brand names

In [14]:
df2 = df_lite.iloc[df_lite["Vehicle"].str.contains("AMG Transport")]
df2.head()

,Vehicle,Value,Car Type,PI
19,AMG Transport Dynamics M12S Warthog CST 2554Au...,850000,Extreme Offroad,A800

In [15]:
df2["Vehicle"] = df2["Vehicle"].str.replace(" ", "_", n=2)
df2.head()

,Vehicle,Value,Car Type,PI
19,AMG_Transport_Dynamics M12S Warthog CST 2554Au...,850000,Extreme Offroad,A800

In [16]:
df_lite.update(df1)
df_lite.head()

                             Vehicle  Value         Car Type    PI
0   Abarth 500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow  35000    Cult Classics  D100
2    Abarth 695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3       Abarth Fiat 131 1980Autoshow  38000    Classic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

In [17]:
df_lite.update(df2)
df_lite.head()

                             Vehicle  Value         Car Type    PI
0   Abarth 500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow  35000    Cult Classics  D100
2    Abarth 695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3       Abarth Fiat 131 1980Autoshow  38000    Classic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

In [18]:
df_lite.update(df_hw)
df_lite.head()

                             Vehicle  Value         Car Type    PI
0   Abarth 500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow  35000    Cult Classics  D100
2    Abarth 695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3       Abarth Fiat 131 1980Autoshow  38000    Classic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

### Perform split

In [19]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

    Brand                      Vehicle  Value         Car Type    PI
0  Abarth    500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1  Abarth    595 esseesse 1968Autoshow  35000    Cult Classics  D100
2  Abarth     695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3  Abarth        Fiat 131 1980Autoshow  38000    Classic Rally  D477
4   Acura  Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

#### Error checking

In [20]:
df_verify = df_lite.iloc[df_lite["Vehicle"].str.contains("_")]
df_verify.head()

Empty DataFrame
Columns: [Brand, Vehicle, Value, Car Type, PI]
Index: []

#### Replace underscores in Brand column with whitespace

In [21]:
df_lite["Brand"] = df_lite["Brand"].str.replace("_", " ")
df_lite.head()

    Brand                      Vehicle  Value         Car Type    PI
0  Abarth    500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1  Abarth    595 esseesse 1968Autoshow  35000    Cult Classics  D100
2  Abarth     695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3  Abarth        Fiat 131 1980Autoshow  38000    Classic Rally  D477
4   Acura  Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

## Split Vehicle column into Vehicle and Collection

In [22]:
df_lite[["Vehicle", "Year", "Collection"]] = df_lite["Vehicle"].str.extract(r'^(.*)(\d{4})(.*)$')
df_lite = df_lite.iloc[:, [0, 1, 5, 2, 6, 3, 4]]
df_lite.loc[459, "Vehicle"] = "Regalia"
df_lite.loc[459, "Year"] = "723"
df_lite.loc[459, "Collection"] = "Gifted"
df_lite.head()

    Brand          Vehicle  Year  Value Collection         Car Type    PI
0  Abarth    500 esseesse   2010  35000   Autoshow        Hot Hatch  C563
1  Abarth    595 esseesse   1968  35000   Autoshow    Cult Classics  D100
2  Abarth     695 Biposto   2016  48000   Autoshow        Hot Hatch  B625
3  Abarth        Fiat 131   1980  38000   Autoshow    Classic Rally  D477
4   Acura  Integra Type-R   2001  25000   Autoshow  Retro Hot Hatch  C571

In [23]:
df_lite["Collection"].value_counts()

Collection
Autoshow                                       349
Wheelspin                                       28
Forzathon                                       26
Barn Find                                       17
Autoshow (DLC: All-Stars Car Pack)              11
Autoshow (DLC: Hot Wheels Expansion)             9
Autoshow (DLC: Blizzard Mountain Expansion)      9
Autoshow (DLC: Duracell Car Pack)                8
Autoshow (DLC: Porsche Car Pack)                 8
Autoshow (DLC: Alpinestars Car Pack)             7
Autoshow (DLC: Mountain Dew Car Pack)            7
Autoshow (DLC: Playseat Car Pack)                7
Autoshow (DLC: The Smoking Tire Car Pack)        7
Autoshow (DLC: Rockstar Energy Car Pack)         7
Autoshow (DLC: Logitech G Car Pack)              7
Autoshow (DLC: Hoonigan Car Pack)                7
Autoshow (DLC: VIP)                              5
Barn Find (Forzathon)                            2
Gifted                                           2
Barn Find (DLC: Hot Wheels Expansion)            1
Name: count, dtype: int64

## Sort by Brand then Year and Vehicle (ascending)

In [24]:
df_lite = df_lite.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df_lite = df_lite.reset_index(drop=True)
df_lite.head(10)

,Brand,Vehicle,Year,Value,Collection,Car Type,PI
0,Abarth,595 esseesse,1968,35000,Autoshow,Cult Classics,D100
1,Abarth,Fiat 131,1980,38000,Autoshow,Classic Rally,D477
2,Abarth,500 esseesse,2010,35000,Autoshow,Hot Hatch,C563
3,Abarth,695 Biposto,2016,48000,Autoshow,Hot Hatch,B625
4,Acura,Integra Type-R,2001,25000,Autoshow,Retro Hot Hatch,C571
5,Acura,RSX Type-S,2002,25000,Autoshow,Hot Hatch,C568
6,Acura,NSX,2017,170000,Autoshow (DLC: Alpinestars Car Pack),Modern Supercars,S1868
7,Alfa Romeo,Giulia Sprint GTA Stradale,1965,300000,Autoshow,Rare Classics,D252
8,Alfa Romeo,Giulia TZ2,1965,1000000,Autoshow,Classic Racers,C573
9,Alfa Romeo,33 Stradale,1968,10000000,Autoshow,Classic Racers,B648

## Clean PI column

In [25]:
df_lite[["PI1", "PI2"]] = df_lite["PI"].str.split(r'(?<=D)|(?<=C)|(?<=B)|(?<=A)|(?<=S1)|(?<=S2)', n=1,
                                                                  expand=True)
df_lite.head()

,Brand,Vehicle,Year,Value,Collection,Car Type,PI,PI1,PI2
0,Abarth,595 esseesse,1968,35000,Autoshow,Cult Classics,D100,D,100
1,Abarth,Fiat 131,1980,38000,Autoshow,Classic Rally,D477,D,477
2,Abarth,500 esseesse,2010,35000,Autoshow,Hot Hatch,C563,C,563
3,Abarth,695 Biposto,2016,48000,Autoshow,Hot Hatch,B625,B,625
4,Acura,Integra Type-R,2001,25000,Autoshow,Retro Hot Hatch,C571,C,571

In [26]:
df_lite["PI1"].value_counts()
# "A" is the most common class
# followed by C
# then S1

PI1
A     118
C     111
S1     93
B      85
D      68
S2     49
Name: count, dtype: int64

In [27]:
df_lite["PI2"].value_counts()
# S1 900 is the most common PI value

PI2
900    13
100     9
800     7
715     6
524     5
       ..
512     1
564     1
705     1
919     1
924     1
Name: count, Length: 328, dtype: int64

In [28]:
df_lite["PI"] = df_lite["PI1"] + " " + df_lite["PI2"]
df_lite = df_lite.drop(["PI1", "PI2"], axis="columns")
df_lite.head()

    Brand          Vehicle  Year  Value Collection         Car Type     PI
0  Abarth    595 esseesse   1968  35000   Autoshow    Cult Classics  D 100
1  Abarth        Fiat 131   1980  38000   Autoshow    Classic Rally  D 477
2  Abarth    500 esseesse   2010  35000   Autoshow        Hot Hatch  C 563
3  Abarth     695 Biposto   2016  48000   Autoshow        Hot Hatch  B 625
4   Acura  Integra Type-R   2001  25000   Autoshow  Retro Hot Hatch  C 571

In [29]:
df_lite["Owned"] = pd.Series(dtype="string")
df_lite.head()

,Brand,Vehicle,Year,Value,Collection,Car Type,PI,Owned
0,Abarth,595 esseesse,1968,35000,Autoshow,Cult Classics,D 100,<NA>
1,Abarth,Fiat 131,1980,38000,Autoshow,Classic Rally,D 477,<NA>
2,Abarth,500 esseesse,2010,35000,Autoshow,Hot Hatch,C 563,<NA>
3,Abarth,695 Biposto,2016,48000,Autoshow,Hot Hatch,B 625,<NA>
4,Acura,Integra Type-R,2001,25000,Autoshow,Retro Hot Hatch,C 571,<NA>

## Sort by lowest to highest cost

In [30]:
df_lite.dtypes

Brand            str
Vehicle          str
Year             str
Value          int64
Collection       str
Car Type         str
PI               str
Owned         string
dtype: object

In [31]:
df_lite["Value"] = df_lite["Value"].astype(str)

In [32]:
df_price = df_lite.sort_values(["Brand", "Value"], ascending=[True, True], key=lambda col: col.str.lower())
df_price = df_price.reset_index(drop=True)
df_price.head(10)

,Brand,Vehicle,Year,Value,Collection,Car Type,PI,Owned
0,Abarth,595 esseesse,1968,35000,Autoshow,Cult Classics,D 100,<NA>
1,Abarth,500 esseesse,2010,35000,Autoshow,Hot Hatch,C 563,<NA>
2,Abarth,Fiat 131,1980,38000,Autoshow,Classic Rally,D 477,<NA>
3,Abarth,695 Biposto,2016,48000,Autoshow,Hot Hatch,B 625,<NA>
4,Acura,NSX,2017,170000,Autoshow (DLC: Alpinestars Car Pack),Modern Supercars,S1 868,<NA>
5,Acura,Integra Type-R,2001,25000,Autoshow,Retro Hot Hatch,C 571,<NA>
6,Acura,RSX Type-S,2002,25000,Autoshow,Hot Hatch,C 568,<NA>
7,Alfa Romeo,Giulia TZ2,1965,1000000,Autoshow,Classic Racers,C 573,<NA>
8,Alfa Romeo,33 Stradale,1968,10000000,Autoshow,Classic Racers,B 648,<NA>
9,Alfa Romeo,155 Q4,1992,25000,Autoshow,Retro Saloons,C 578,<NA>

### Convert dataframe to csv

In [33]:
df_lite.to_csv("FH3/FH3-0-masterlist.csv", index=False, encoding="utf-8-sig")
df_price.to_csv("FH3/FH3-1-price.csv", index=False, encoding="utf-8-sig")