In [118]:
import pandas as pd

# Import raw data for preprocessing

In [119]:
filename = "FH3-cars-list"
tables = pd.read_html("raw-website/" + filename + ".htm")
df = tables[1]
df.head(10)

,Vehicle,📅,Value,Sp,Ha,Ac,La,Br,PI
0,Abarth 500 esseesse 2010Autoshow,NaN,"35,000 CRHot Hatch",5.0,5.8,6.4,6.7,5.9,C563
1,Abarth 595 esseesse 1968Autoshow,NaN,"35,000 CRCult Classics",3.0,3.6,3.0,3.2,3.0,D100
2,Abarth 695 Biposto 2016Autoshow,NaN,"48,000 CRHot Hatch",5.0,6.6,6.8,6.9,7.7,B625
3,Abarth Fiat 131 1980Autoshow,NaN,"38,000 CRClassic Rally",4.8,4.9,6.1,6.3,4.2,D477
4,Acura Integra Type-R 2001Autoshow,NaN,"25,000 CRRetro Hot Hatch",5.7,5.8,6.6,6.8,5.5,C571
5,Acura NSX 2017Autoshow (DLC: Alpinestars Car P...,NaN,"170,000 CRModern Supercars",7.0,7.6,9.0,10.0,9.3,S1868
6,Acura RSX Type-S 2002Autoshow,NaN,"25,000 CRHot Hatch",5.7,5.8,6.6,6.7,5.5,C568
7,Alfa Romeo 4C 2014Autoshow,NaN,"74,000 CREuropean Sports Cars",6.0,7.0,8.0,8.5,8.0,A758
8,Alfa Romeo 8C Competizione 2007Autoshow,NaN,"300,000 CRGT Cars",7.2,6.8,8.1,8.1,7.8,A766
9,Alfa Romeo 33 Stradale 1968Autoshow,NaN,"10,000,000 CRClassic Racers",6.4,6.0,8.3,8.0,6.1,B648

## Remove redundant columns

In [120]:
columns_to_drop = [1]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,PI
0,Abarth 500 esseesse 2010Autoshow,"35,000 CRHot Hatch",5.0,5.8,6.4,6.7,5.9,C563
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCult Classics",3.0,3.6,3.0,3.2,3.0,D100
2,Abarth 695 Biposto 2016Autoshow,"48,000 CRHot Hatch",5.0,6.6,6.8,6.9,7.7,B625
3,Abarth Fiat 131 1980Autoshow,"38,000 CRClassic Rally",4.8,4.9,6.1,6.3,4.2,D477
4,Acura Integra Type-R 2001Autoshow,"25,000 CRRetro Hot Hatch",5.7,5.8,6.6,6.8,5.5,C571

## Expand abbreviated columns

In [121]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,PI
0,Abarth 500 esseesse 2010Autoshow,"35,000 CRHot Hatch",5.0,5.8,6.4,6.7,5.9,C563
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCult Classics",3.0,3.6,3.0,3.2,3.0,D100
2,Abarth 695 Biposto 2016Autoshow,"48,000 CRHot Hatch",5.0,6.6,6.8,6.9,7.7,B625
3,Abarth Fiat 131 1980Autoshow,"38,000 CRClassic Rally",4.8,4.9,6.1,6.3,4.2,D477
4,Acura Integra Type-R 2001Autoshow,"25,000 CRRetro Hot Hatch",5.7,5.8,6.6,6.8,5.5,C571

In [122]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   524 non-null    str
 1   Value     524 non-null    str
 2   Speed     524 non-null    float64
 3   Handling  524 non-null    float64
 4   Accel     524 non-null    float64
 5   Launch    524 non-null    float64
 6   Braking   524 non-null    float64
 7   PI        524 non-null    str
dtypes: float64(5), str(3)
memory usage: 32.9 KB

## Remove stat columns from df_lite

In [123]:
columns_to_drop = [2, 3, 4, 5, 6]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                             Vehicle                     Value    PI
0   Abarth 500 esseesse 2010Autoshow        35,000 CRHot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow    35,000 CRCult Classics  D100
2    Abarth 695 Biposto 2016Autoshow        48,000 CRHot Hatch  B625
3       Abarth Fiat 131 1980Autoshow    38,000 CRClassic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25,000 CRRetro Hot Hatch  C571

## Split original Value column into Value and Car Type

In [124]:
df_lite.iloc[df_lite["Value"].str.contains("?", regex=False)].head()

Empty DataFrame
Columns: [Vehicle, Value, PI]
Index: []

In [125]:
df_lite[["Value", "Car Type"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                             Vehicle  Value         Car Type    PI
0   Abarth 500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow  35000    Cult Classics  D100
2    Abarth 695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3       Abarth Fiat 131 1980Autoshow  38000    Classic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

## Split original Vehicle column into Brand and Vehicle

In [126]:
df_lite.iloc[df_lite["Vehicle"].str.contains("_")].head()

Empty DataFrame
Columns: [Vehicle, Value, Car Type, PI]
Index: []

### Isolate rows for 2-word vehicle brand names

In [127]:
df1 = df_lite.iloc[df_lite["Vehicle"].str.contains("Alfa Romeo|Alumi Craft|Aston Martin|Baldwin Motorsports|Land Rover|Local Motors|RJ Anderson|Spania GTA|W Motors")]
df1 = df1.loc[~df1["Vehicle"].str.contains("Hoonigan")]
df1.head()

,Vehicle,Value,Car Type,PI
7,Alfa Romeo 4C 2014Autoshow,74000,European Sports Cars,A758
8,Alfa Romeo 8C Competizione 2007Autoshow,300000,GT Cars,A766
9,Alfa Romeo 33 Stradale 1968Autoshow,10000000,Classic Racers,B648
10,Alfa Romeo 155 Q4 1992Autoshow,25000,Retro Saloons,C578
11,Alfa Romeo Giulia Sprint GTA Stradale 1965Auto...,300000,Rare Classics,D252

In [128]:
df1["Vehicle"] = df1["Vehicle"].str.replace(" ", "_", n=1)
df1.head()

,Vehicle,Value,Car Type,PI
7,Alfa_Romeo 4C 2014Autoshow,74000,European Sports Cars,A758
8,Alfa_Romeo 8C Competizione 2007Autoshow,300000,GT Cars,A766
9,Alfa_Romeo 33 Stradale 1968Autoshow,10000000,Classic Racers,B648
10,Alfa_Romeo 155 Q4 1992Autoshow,25000,Retro Saloons,C578
11,Alfa_Romeo Giulia Sprint GTA Stradale 1965Auto...,300000,Rare Classics,D252

### Separate filtering for Hot Wheels

In [129]:
df_hw = df_lite.iloc[df_lite["Vehicle"].str.contains("Hot Wheels")]
df_hw = df_hw.loc[~df_hw["Vehicle"].str.contains("Chrysler|Ford|Jeep|Pagani|Toyota|Zenvo")]
df_hw.head()

,Vehicle,Value,Car Type,PI
255,Hot Wheels Bone Shaker 2005Autoshow (DLC: Hot ...,150000,Rods and Customs,A797
256,Hot Wheels Mustang 2005Autoshow (DLC: Hot Whee...,50000,Extreme Track Toys,S1900
257,Hot Wheels Rip Rod 2012Autoshow (DLC: Hot Whee...,75000,Buggies,B700
258,Hot Wheels Twin Mill 1969Autoshow (DLC: Hot Wh...,110000,Rods and Customs,S1900

In [130]:
df_hw["Vehicle"] = df_hw["Vehicle"].str.replace(" ", "_", n=1)
df_hw.head()

,Vehicle,Value,Car Type,PI
255,Hot_Wheels Bone Shaker 2005Autoshow (DLC: Hot ...,150000,Rods and Customs,A797
256,Hot_Wheels Mustang 2005Autoshow (DLC: Hot Whee...,50000,Extreme Track Toys,S1900
257,Hot_Wheels Rip Rod 2012Autoshow (DLC: Hot Whee...,75000,Buggies,B700
258,Hot_Wheels Twin Mill 1969Autoshow (DLC: Hot Wh...,110000,Rods and Customs,S1900

### Isolate rows for 3-word vehicle brand names

In [131]:
df2 = df_lite.iloc[df_lite["Vehicle"].str.contains("AMG Transport")]
df2.head()

,Vehicle,Value,Car Type,PI
19,AMG Transport Dynamics M12S Warthog CST 2554Au...,850000,Extreme Offroad,A800

In [132]:
df2["Vehicle"] = df2["Vehicle"].str.replace(" ", "_", n=2)
df2.head()

,Vehicle,Value,Car Type,PI
19,AMG_Transport_Dynamics M12S Warthog CST 2554Au...,850000,Extreme Offroad,A800

In [133]:
df_lite.update(df1)
df_lite.head()

                             Vehicle  Value         Car Type    PI
0   Abarth 500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow  35000    Cult Classics  D100
2    Abarth 695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3       Abarth Fiat 131 1980Autoshow  38000    Classic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

In [134]:
df_lite.update(df2)
df_lite.head()

                             Vehicle  Value         Car Type    PI
0   Abarth 500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow  35000    Cult Classics  D100
2    Abarth 695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3       Abarth Fiat 131 1980Autoshow  38000    Classic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

In [135]:
df_lite.update(df_hw)
df_lite.head()

                             Vehicle  Value         Car Type    PI
0   Abarth 500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1   Abarth 595 esseesse 1968Autoshow  35000    Cult Classics  D100
2    Abarth 695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3       Abarth Fiat 131 1980Autoshow  38000    Classic Rally  D477
4  Acura Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

### Perform split

In [136]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

    Brand                      Vehicle  Value         Car Type    PI
0  Abarth    500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1  Abarth    595 esseesse 1968Autoshow  35000    Cult Classics  D100
2  Abarth     695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3  Abarth        Fiat 131 1980Autoshow  38000    Classic Rally  D477
4   Acura  Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

#### Error checking

In [137]:
df_verify = df_lite.iloc[df_lite["Vehicle"].str.contains("_")]
df_verify.head()

Empty DataFrame
Columns: [Brand, Vehicle, Value, Car Type, PI]
Index: []

#### Replace underscores in Brand column with whitespace

In [138]:
df_lite["Brand"] = df_lite["Brand"].str.replace("_", " ")
df_lite.head()

    Brand                      Vehicle  Value         Car Type    PI
0  Abarth    500 esseesse 2010Autoshow  35000        Hot Hatch  C563
1  Abarth    595 esseesse 1968Autoshow  35000    Cult Classics  D100
2  Abarth     695 Biposto 2016Autoshow  48000        Hot Hatch  B625
3  Abarth        Fiat 131 1980Autoshow  38000    Classic Rally  D477
4   Acura  Integra Type-R 2001Autoshow  25000  Retro Hot Hatch  C571

## Split Vehicle column into Vehicle and Collection

In [ ]:
df_lite[["Vehicle", "Collection"]] = df_lite["Vehicle"].str.split(r'(?=Autoshow)|(?=Barn)|(?=Wheelspin)|(?=Forzathon)|(?=Gifted)', n=1,
                                                                  expand=True)
df_lite.head()

In [ ]:
df_lite["Collection"].value_counts()

## Split Vehicle Column into Year and Vehicle

In [ ]:
df_lite[["Vehicle", "Year"]] = df_lite["Vehicle"].str.rsplit(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 6, 1, 2, 3, 5, 4]]
df_lite.head()

## Sort by Brand then Year (ascending)

In [ ]:
df_lite = df_lite.sort_values(["Brand", "Year"], ascending=[True, True], key=lambda col: col.str.lower())
df_lite = df_lite.reset_index(drop=True)
df_lite.head(10)

## Clean PI column

In [ ]:
df_lite[["PI1", "PI2"]] = df_lite["PI"].str.split(r'(?<=D)|(?<=C)|(?<=B)|(?<=A)|(?<=S1)|(?<=S2)', n=1,
                                                                  expand=True)
df_lite.head()

In [ ]:
df_lite["PI1"].value_counts()
# "A" is the most common class
# followed by C
# then S1

In [ ]:
df_lite["PI2"].value_counts()
# S1 900 is the most common PI value

In [ ]:
df_lite["PI"] = df_lite["PI1"] + " " + df_lite["PI2"]
df_lite = df_lite.drop(["PI1", "PI2"], axis="columns")
df_lite.head()

In [ ]:
df_lite["Owned"] = pd.Series(dtype="string")
df_lite.head()

### Convert dataframe to csv

In [ ]:
df_lite.to_csv("FH3/FH3-0-masterlist.csv", index=False)