In [5]:
import pandas as pd

# Import raw data for preprocessing

In [6]:
filename = "raw-website/FH4-cars-list"
tables = pd.read_html(filename + ".htm")
df = tables[1]
df.head()

,Image,Vehicle,🔓,🦄,📅,Value,Sp,Ha,Ac,La,Br,PI
0,NaN,Abarth 124 Spider 2017 Autoshow,NaN,NaN,NaN,"43,500 CR COMMON",6.0,5.9,5.6,7.6,5.4,C577
1,NaN,Abarth 595 esseesse 1968 Autoshow,NaN,NaN,NaN,"35,000 CR COMMON",3.9,4.0,3.7,4.9,4.0,D100
2,NaN,Abarth 695 Biposto 2016 Autoshow,NaN,NaN,NaN,"48,000 CR RARE",5.7,6.3,5.9,7.5,6.4,B607
3,NaN,Abarth Fiat 131 1980 Autoshow,NaN,NaN,NaN,"38,000 CR COMMON",5.5,4.7,5.5,7.1,4.5,D449
4,NaN,Acura Integra Type-R 2001 Autoshow,NaN,NaN,NaN,"25,000 CR COMMON",6.3,5.8,5.6,6.9,5.4,C596

## Remove redundant columns

In [7]:
columns_to_drop = [0, 2, 3, 4]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,PI
0,Abarth 124 Spider 2017 Autoshow,"43,500 CR COMMON",6.0,5.9,5.6,7.6,5.4,C577
1,Abarth 595 esseesse 1968 Autoshow,"35,000 CR COMMON",3.9,4.0,3.7,4.9,4.0,D100
2,Abarth 695 Biposto 2016 Autoshow,"48,000 CR RARE",5.7,6.3,5.9,7.5,6.4,B607
3,Abarth Fiat 131 1980 Autoshow,"38,000 CR COMMON",5.5,4.7,5.5,7.1,4.5,D449
4,Acura Integra Type-R 2001 Autoshow,"25,000 CR COMMON",6.3,5.8,5.6,6.9,5.4,C596

## Expand abbreviated columns

In [8]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,PI
0,Abarth 124 Spider 2017 Autoshow,"43,500 CR COMMON",6.0,5.9,5.6,7.6,5.4,C577
1,Abarth 595 esseesse 1968 Autoshow,"35,000 CR COMMON",3.9,4.0,3.7,4.9,4.0,D100
2,Abarth 695 Biposto 2016 Autoshow,"48,000 CR RARE",5.7,6.3,5.9,7.5,6.4,B607
3,Abarth Fiat 131 1980 Autoshow,"38,000 CR COMMON",5.5,4.7,5.5,7.1,4.5,D449
4,Acura Integra Type-R 2001 Autoshow,"25,000 CR COMMON",6.3,5.8,5.6,6.9,5.4,C596

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   753 non-null    str
 1   Value     753 non-null    str
 2   Speed     753 non-null    float64
 3   Handling  753 non-null    float64
 4   Accel     753 non-null    float64
 5   Launch    753 non-null    float64
 6   Braking   753 non-null    float64
 7   PI        753 non-null    str
dtypes: float64(5), str(3)
memory usage: 47.2 KB

## Remove stat columns from df_lite

In [10]:
columns_to_drop = [2, 3, 4, 5, 6]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                              Vehicle             Value    PI
0     Abarth 124 Spider 2017 Autoshow  43,500 CR COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35,000 CR COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow    48,000 CR RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38,000 CR COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25,000 CR COMMON  C596

## Split original Value column into Value and Rarity

In [11]:
df_lite[["Value", "Rarity"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].str.replace("?", "0")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                              Vehicle  Value   Rarity    PI
0     Abarth 124 Spider 2017 Autoshow  43500   COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35000   COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow  48000     RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38000   COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25000   COMMON  C596

## Split original Vehicle column into Brand and Vehicle

In [12]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

    Brand                       Vehicle  Value   Rarity    PI
0  Abarth      124 Spider 2017 Autoshow  43500   COMMON  C577
1  Abarth    595 esseesse 1968 Autoshow  35000   COMMON  D100
2  Abarth     695 Biposto 2016 Autoshow  48000     RARE  B607
3  Abarth        Fiat 131 1980 Autoshow  38000   COMMON  D449
4   Acura  Integra Type-R 2001 Autoshow  25000   COMMON  C596

## Create Boolean columns for method of obtaining

In [13]:
df_lite["Autoshow"] = df_lite["Vehicle"].str.contains("Autoshow")
df_lite["Hard to Find"] = df_lite["Vehicle"].str.contains("Hard to Find")
df_lite["Wheelspin"] = df_lite["Vehicle"].str.contains("Wheelspin")
df_lite.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Hard to Find,Wheelspin
0,Abarth,124 Spider 2017 Autoshow,43500,COMMON,C577,True,False,False
1,Abarth,595 esseesse 1968 Autoshow,35000,COMMON,D100,True,False,False
2,Abarth,695 Biposto 2016 Autoshow,48000,RARE,B607,True,False,False
3,Abarth,Fiat 131 1980 Autoshow,38000,COMMON,D449,True,False,False
4,Acura,Integra Type-R 2001 Autoshow,25000,COMMON,C596,True,False,False

In [14]:
df_lite.info()

<class 'pandas.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         753 non-null    str
 1   Vehicle       753 non-null    str
 2   Value         753 non-null    int64
 3   Rarity        753 non-null    str
 4   PI            753 non-null    str
 5   Autoshow      753 non-null    bool
 6   Hard to Find  753 non-null    bool
 7   Wheelspin     753 non-null    bool
dtypes: bool(3), int64(1), str(4)
memory usage: 31.7 KB

## Filter to cars that are obtainable via Autoshow and Wheelspin

In [ ]:
df_sort = df_lite[df_lite["Vehicle"].str.contains("Autoshow, Wheelspin")]
df_sort.head()

In [ ]:
df_sort.info()

## Sort vehicles by brand, then lowest to highest cost

In [ ]:
#df_sort = df_sort.sort_values(["Vehicle", "Value"], ascending=[True, True])
df_sort = df_sort.sort_values(["Brand", "Value"], ascending=[True, True])
#df_sort = df_sort[df_sort["Value"] <= 500000]
df_sort.head()

In [ ]:
df_sort.info()

### Convert dataframes to csv

In [ ]:
df_sort.to_csv(filename + "-sorted" + ".csv", index=False)

In [ ]:
df_lite.to_csv(filename + ".csv", index=False)

## Filter to Wheelspin-exclusive cars

In [ ]:
df_wheelspin = df_lite.loc[(df_lite["Autoshow"] == False) & (df_lite["Wheelspin"] == True)]
df_wheelspin = df_wheelspin.drop(columns=["Hard to Find", "Aftermarket Car"])
df_wheelspin.head()

In [ ]:
df_wheelspin["Rarity"].value_counts()

### Associate each rarity with numerical value

In [ ]:
rarity_dict = {"COMMON": 1, "RARE": 2, "EPIC": 3, "LEGENDARY": 4, "FORZA EDITION": 5}
df_wheelspin["Rarity Value"] = df_wheelspin["Rarity"].map(rarity_dict)
df_wheelspin.head()

### Sort Wheelspin-exclusives according to Rarity

In [ ]:
df_wheelspin = df_wheelspin.sort_values(["Rarity Value", "Brand"], ascending=[True, True])
df_wheelspin.head()

In [ ]:
df_wheelspin = df_wheelspin.drop(columns=["Rarity Value"])
df_wheelspin.info()

### Dataframe to csv

In [ ]:
df_wheelspin.to_csv(filename + "-wheelspin" + ".csv", index=False)

In [ ]:
df_test = df_lite[(df_lite["Rarity"] == "COMMON") & (df_lite["Wheelspin"] == True)]
df_test = df_test.sort_values(["Value"], ascending=False)
df_test.head()