In [52]:
import pandas as pd

# Import raw data for preprocessing

In [53]:
filename = "FH4-cars-list"
tables = pd.read_html("raw-website/" + filename + ".htm")
df = tables[1]
df.head(10)

,Image,Vehicle,🔓,🦄,📅,Value,Sp,Ha,Ac,La,Br,PI
0,NaN,Abarth 124 Spider 2017 Autoshow,NaN,NaN,NaN,"43,500 CR COMMON",6.0,5.9,5.6,7.6,5.4,C577
1,NaN,Abarth 595 esseesse 1968 Autoshow,NaN,NaN,NaN,"35,000 CR COMMON",3.9,4.0,3.7,4.9,4.0,D100
2,NaN,Abarth 695 Biposto 2016 Autoshow,NaN,NaN,NaN,"48,000 CR RARE",5.7,6.3,5.9,7.5,6.4,B607
3,NaN,Abarth Fiat 131 1980 Autoshow,NaN,NaN,NaN,"38,000 CR COMMON",5.5,4.7,5.5,7.1,4.5,D449
4,NaN,Acura Integra Type-R 2001 Autoshow,NaN,NaN,NaN,"25,000 CR COMMON",6.3,5.8,5.6,6.9,5.4,C596
5,NaN,Acura RSX Type-S 2002 Autoshow,NaN,NaN,NaN,"25,000 CR COMMON",6.3,5.8,5.6,6.7,5.4,C588
6,NaN,Acura NSX 2017 Autoshow,NaN,NaN,NaN,"170,000 CR RARE",7.4,7.6,9.6,10.0,8.3,S1850
7,NaN,"Alfa Romeo 155 Q4 1992 A ""Hard-to-Find"" vehicle",NaN,NaN,NaN,"250,000 CR EPIC",6.2,5.0,5.8,7.8,4.7,C541
8,NaN,Alfa Romeo 4C 2014 Autoshow,NaN,NaN,NaN,"74,000 CR RARE",6.6,7.1,6.5,8.8,7.0,A770
9,NaN,Alfa Romeo 8C Competizione 2007 Autoshow,NaN,NaN,NaN,"300,000 CR EPIC",7.5,6.6,6.6,8.2,6.8,A777

## Remove redundant columns

In [54]:
columns_to_drop = [0, 2, 3, 4]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,PI
0,Abarth 124 Spider 2017 Autoshow,"43,500 CR COMMON",6.0,5.9,5.6,7.6,5.4,C577
1,Abarth 595 esseesse 1968 Autoshow,"35,000 CR COMMON",3.9,4.0,3.7,4.9,4.0,D100
2,Abarth 695 Biposto 2016 Autoshow,"48,000 CR RARE",5.7,6.3,5.9,7.5,6.4,B607
3,Abarth Fiat 131 1980 Autoshow,"38,000 CR COMMON",5.5,4.7,5.5,7.1,4.5,D449
4,Acura Integra Type-R 2001 Autoshow,"25,000 CR COMMON",6.3,5.8,5.6,6.9,5.4,C596

## Expand abbreviated columns

In [55]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,PI
0,Abarth 124 Spider 2017 Autoshow,"43,500 CR COMMON",6.0,5.9,5.6,7.6,5.4,C577
1,Abarth 595 esseesse 1968 Autoshow,"35,000 CR COMMON",3.9,4.0,3.7,4.9,4.0,D100
2,Abarth 695 Biposto 2016 Autoshow,"48,000 CR RARE",5.7,6.3,5.9,7.5,6.4,B607
3,Abarth Fiat 131 1980 Autoshow,"38,000 CR COMMON",5.5,4.7,5.5,7.1,4.5,D449
4,Acura Integra Type-R 2001 Autoshow,"25,000 CR COMMON",6.3,5.8,5.6,6.9,5.4,C596

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   753 non-null    str
 1   Value     753 non-null    str
 2   Speed     753 non-null    float64
 3   Handling  753 non-null    float64
 4   Accel     753 non-null    float64
 5   Launch    753 non-null    float64
 6   Braking   753 non-null    float64
 7   PI        753 non-null    str
dtypes: float64(5), str(3)
memory usage: 47.2 KB

## Remove stat columns from df_lite

In [57]:
columns_to_drop = [2, 3, 4, 5, 6]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                              Vehicle             Value    PI
0     Abarth 124 Spider 2017 Autoshow  43,500 CR COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35,000 CR COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow    48,000 CR RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38,000 CR COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25,000 CR COMMON  C596

## Split original Value column into Value and Rarity

In [58]:
df_lite.iloc[df_lite["Value"].str.contains("?", regex=False)].head()

Empty DataFrame
Columns: [Vehicle, Value, PI]
Index: []

In [59]:
df_lite[["Value", "Rarity"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                              Vehicle  Value   Rarity    PI
0     Abarth 124 Spider 2017 Autoshow  43500   COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35000   COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow  48000     RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38000   COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25000   COMMON  C596

## Split original Vehicle column into Brand and Vehicle

In [60]:
df_lite.iloc[df_lite["Vehicle"].str.contains("%")].head()

Empty DataFrame
Columns: [Vehicle, Value, Rarity, PI]
Index: []

### Isolate rows for 2-word vehicle brand names

In [61]:
df1 = df_lite.iloc[df_lite["Vehicle"].str.contains("Alfa Romeo|Alumi Craft|Aston Martin|Auto Union|DS Automobiles|Formula Drift|Funco Motorsports|Hot Wheels|Land Rover|Local Motors|RJ Anderson|Spania GTA|Top Gear|W Motors")]
df1 = df1.loc[~df1["Vehicle"].str.contains("Mercedes-Benz|James Bond Edition")]
df1.head()

,Vehicle,Value,Rarity,PI
7,"Alfa Romeo 155 Q4 1992 A ""Hard-to-Find"" vehicle",250000,EPIC,C541
8,Alfa Romeo 4C 2014 Autoshow,74000,RARE,A770
9,Alfa Romeo 8C Competizione 2007 Autoshow,300000,EPIC,A777
10,Alfa Romeo 8C Competizione Forza Edition 2007 ...,550000,FORZA EDITION,S1899
11,Alfa Romeo 33 Stradale 1968 Autoshow,10000000,LEGENDARY,A716

In [62]:
df1["Vehicle"] = df1["Vehicle"].str.replace(" ", "%", n=1)
df1.head()

,Vehicle,Value,Rarity,PI
7,"Alfa%Romeo 155 Q4 1992 A ""Hard-to-Find"" vehicle",250000,EPIC,C541
8,Alfa%Romeo 4C 2014 Autoshow,74000,RARE,A770
9,Alfa%Romeo 8C Competizione 2007 Autoshow,300000,EPIC,A777
10,Alfa%Romeo 8C Competizione Forza Edition 2007 ...,550000,FORZA EDITION,S1899
11,Alfa%Romeo 33 Stradale 1968 Autoshow,10000000,LEGENDARY,A716

### Isolate rows for 3-word vehicle brand names

In [63]:
df2 = df_lite.iloc[df_lite["Vehicle"].str.contains("AMG Transport|James Bond Edition|LEGO Speed Champions")]
df2.head()

,Vehicle,Value,Rarity,PI
24,AMG Transport Dynamics M12S Warthog CST 2554 A...,850000,LEGENDARY,A756
373,James Bond Edition AMC Hornet X Hatchback 1974...,35000,COMMON,D414
374,James Bond Edition Aston Martin DB5 1964 Autos...,650000,LEGENDARY,B618
375,James Bond Edition Aston Martin DB10 2015 Auto...,220000,LEGENDARY,S1814
376,James Bond Edition Aston Martin DBS 1969 Autos...,650000,RARE,B612

In [64]:
df2["Vehicle"] = df2["Vehicle"].str.replace(" ", "%", n=2)
df2.head()

,Vehicle,Value,Rarity,PI
24,AMG%Transport%Dynamics M12S Warthog CST 2554 A...,850000,LEGENDARY,A756
373,James%Bond%Edition AMC Hornet X Hatchback 1974...,35000,COMMON,D414
374,James%Bond%Edition Aston Martin DB5 1964 Autos...,650000,LEGENDARY,B618
375,James%Bond%Edition Aston Martin DB10 2015 Auto...,220000,LEGENDARY,S1814
376,James%Bond%Edition Aston Martin DBS 1969 Autos...,650000,RARE,B612

In [65]:
df_lite.update(df1)
df_lite.head()

                              Vehicle  Value   Rarity    PI
0     Abarth 124 Spider 2017 Autoshow  43500   COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35000   COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow  48000     RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38000   COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25000   COMMON  C596

In [66]:
df_lite.update(df2)
df_lite.head()

                              Vehicle  Value   Rarity    PI
0     Abarth 124 Spider 2017 Autoshow  43500   COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35000   COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow  48000     RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38000   COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25000   COMMON  C596

### Perform split

In [67]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

    Brand                       Vehicle  Value   Rarity    PI
0  Abarth      124 Spider 2017 Autoshow  43500   COMMON  C577
1  Abarth    595 esseesse 1968 Autoshow  35000   COMMON  D100
2  Abarth     695 Biposto 2016 Autoshow  48000     RARE  B607
3  Abarth        Fiat 131 1980 Autoshow  38000   COMMON  D449
4   Acura  Integra Type-R 2001 Autoshow  25000   COMMON  C596

#### Error checking

In [68]:
df_verify = df_lite.iloc[df_lite["Vehicle"].str.contains("%")]
df_verify.head()

Empty DataFrame
Columns: [Brand, Vehicle, Value, Rarity, PI]
Index: []

#### Replace percent sign in Brand column with whitespace

In [69]:
df_lite["Brand"] = df_lite["Brand"].str.replace("%", " ")
df_lite.head()

    Brand                       Vehicle  Value   Rarity    PI
0  Abarth      124 Spider 2017 Autoshow  43500   COMMON  C577
1  Abarth    595 esseesse 1968 Autoshow  35000   COMMON  D100
2  Abarth     695 Biposto 2016 Autoshow  48000     RARE  B607
3  Abarth        Fiat 131 1980 Autoshow  38000   COMMON  D449
4   Acura  Integra Type-R 2001 Autoshow  25000   COMMON  C596

## Split Vehicle column into Vehicle and Collection

In [70]:
df_lite[["Vehicle", "Year", "Collection"]] = df_lite["Vehicle"].str.extract(r'^(.*)(\d{4})(.*)$')
df_lite = df_lite.iloc[:, [0, 1, 5, 2, 6, 3, 4]]
df_lite.loc[644, "Vehicle"] = "Regalia"
df_lite.loc[645, "Vehicle"] = "Regalia Type-D"
df_lite.loc[[644, 645], "Year"] = "723"
df_lite.loc[644, "Collection"] = "A \"Hard-to-Find\" vehicle"
df_lite.loc[645, "Collection"] = "Skill Tree:  Quartz Regalia"
df_lite.head()

    Brand          Vehicle  Year  Value Collection   Rarity    PI
0  Abarth      124 Spider   2017  43500   Autoshow   COMMON  C577
1  Abarth    595 esseesse   1968  35000   Autoshow   COMMON  D100
2  Abarth     695 Biposto   2016  48000   Autoshow     RARE  B607
3  Abarth        Fiat 131   1980  38000   Autoshow   COMMON  D449
4   Acura  Integra Type-R   2001  25000   Autoshow   COMMON  C596

In [71]:
df_lite["Collection"].value_counts()

Collection
Autoshow                                          402
A "Hard-to-Find" vehicle                          138
Autoshow (DLC: Car Pass)                           42
A possible Wheelspin reward                        40
Complete its Barn Find rumor                       15
                                                 ...
Reach Tier 5 in Horizon Life: Top Gear              1
Reach Tier 7 in Horizon Life: Horizon Super7        1
Skill Tree: TVR Sagaris                             1
Reach Tier 4 in Horizon Life: The Drag Strip        1
Reach Tier 10 in Horizon Life: World's Fastest      1
Name: count, Length: 69, dtype: int64

## Sort by Brand then Year and Vehicle (ascending)

In [ ]:
df_lite = df_lite.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df_lite = df_lite.reset_index(drop=True)
df_lite.head(10)

## Clean PI column

In [ ]:
df_lite[["PI1", "PI2"]] = df_lite["PI"].str.split(r'(?<=D)|(?<=C)|(?<=B)|(?<=A)|(?<=S1)|(?<=S2)', n=1,
                                                                  expand=True)
df_lite.head()

In [ ]:
df_lite["PI1"].value_counts()
# "A" is the most common class
# followed by C
# then S1

In [ ]:
df_lite["PI2"].value_counts()
# S1 900 is the most common PI value

In [ ]:
df_lite["PI"] = df_lite["PI1"] + " " + df_lite["PI2"]
df_lite = df_lite.drop(["PI1", "PI2"], axis="columns")
df_lite.head()

In [ ]:
df_lite["Owned"] = pd.Series(dtype="string")
df_lite.head()

## Sort by lowest to highest cost

In [ ]:
df_lite.dtypes

In [ ]:
df_lite["Value"] = df_lite["Value"].astype(str)

In [ ]:
df_price = df_lite.sort_values(["Brand", "Value"], ascending=[True, True], key=lambda col: col.str.lower())
df_price = df_price.reset_index(drop=True)
df_price.head(10)

### Convert dataframe to csv

In [ ]:
df_lite.to_csv("FH3/FH3-0-masterlist.csv", index=False, encoding="utf-8-sig")
df_price.to_csv("FH3/FH3-1-price.csv", index=False, encoding="utf-8-sig")