In [116]:
import pandas as pd

# Import raw data for preprocessing

In [117]:
filename = "FH4-cars-list"
tables = pd.read_html("raw-website/" + filename + ".htm")
df = tables[1]
df.head(10)

,Image,Vehicle,🔓,🦄,📅,Value,Sp,Ha,Ac,La,Br,PI
0,NaN,Abarth 124 Spider 2017 Autoshow,NaN,NaN,NaN,"43,500 CR COMMON",6.0,5.9,5.6,7.6,5.4,C577
1,NaN,Abarth 595 esseesse 1968 Autoshow,NaN,NaN,NaN,"35,000 CR COMMON",3.9,4.0,3.7,4.9,4.0,D100
2,NaN,Abarth 695 Biposto 2016 Autoshow,NaN,NaN,NaN,"48,000 CR RARE",5.7,6.3,5.9,7.5,6.4,B607
3,NaN,Abarth Fiat 131 1980 Autoshow,NaN,NaN,NaN,"38,000 CR COMMON",5.5,4.7,5.5,7.1,4.5,D449
4,NaN,Acura Integra Type-R 2001 Autoshow,NaN,NaN,NaN,"25,000 CR COMMON",6.3,5.8,5.6,6.9,5.4,C596
5,NaN,Acura RSX Type-S 2002 Autoshow,NaN,NaN,NaN,"25,000 CR COMMON",6.3,5.8,5.6,6.7,5.4,C588
6,NaN,Acura NSX 2017 Autoshow,NaN,NaN,NaN,"170,000 CR RARE",7.4,7.6,9.6,10.0,8.3,S1850
7,NaN,"Alfa Romeo 155 Q4 1992 A ""Hard-to-Find"" vehicle",NaN,NaN,NaN,"250,000 CR EPIC",6.2,5.0,5.8,7.8,4.7,C541
8,NaN,Alfa Romeo 4C 2014 Autoshow,NaN,NaN,NaN,"74,000 CR RARE",6.6,7.1,6.5,8.8,7.0,A770
9,NaN,Alfa Romeo 8C Competizione 2007 Autoshow,NaN,NaN,NaN,"300,000 CR EPIC",7.5,6.6,6.6,8.2,6.8,A777

## Remove redundant columns

In [118]:
columns_to_drop = [0, 2, 3, 4]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,PI
0,Abarth 124 Spider 2017 Autoshow,"43,500 CR COMMON",6.0,5.9,5.6,7.6,5.4,C577
1,Abarth 595 esseesse 1968 Autoshow,"35,000 CR COMMON",3.9,4.0,3.7,4.9,4.0,D100
2,Abarth 695 Biposto 2016 Autoshow,"48,000 CR RARE",5.7,6.3,5.9,7.5,6.4,B607
3,Abarth Fiat 131 1980 Autoshow,"38,000 CR COMMON",5.5,4.7,5.5,7.1,4.5,D449
4,Acura Integra Type-R 2001 Autoshow,"25,000 CR COMMON",6.3,5.8,5.6,6.9,5.4,C596

## Expand abbreviated columns

In [119]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,PI
0,Abarth 124 Spider 2017 Autoshow,"43,500 CR COMMON",6.0,5.9,5.6,7.6,5.4,C577
1,Abarth 595 esseesse 1968 Autoshow,"35,000 CR COMMON",3.9,4.0,3.7,4.9,4.0,D100
2,Abarth 695 Biposto 2016 Autoshow,"48,000 CR RARE",5.7,6.3,5.9,7.5,6.4,B607
3,Abarth Fiat 131 1980 Autoshow,"38,000 CR COMMON",5.5,4.7,5.5,7.1,4.5,D449
4,Acura Integra Type-R 2001 Autoshow,"25,000 CR COMMON",6.3,5.8,5.6,6.9,5.4,C596

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   753 non-null    str
 1   Value     753 non-null    str
 2   Speed     753 non-null    float64
 3   Handling  753 non-null    float64
 4   Accel     753 non-null    float64
 5   Launch    753 non-null    float64
 6   Braking   753 non-null    float64
 7   PI        753 non-null    str
dtypes: float64(5), str(3)
memory usage: 47.2 KB

## Remove stat columns from df_lite

In [121]:
columns_to_drop = [2, 3, 4, 5, 6]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                              Vehicle             Value    PI
0     Abarth 124 Spider 2017 Autoshow  43,500 CR COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35,000 CR COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow    48,000 CR RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38,000 CR COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25,000 CR COMMON  C596

## Split original Value column into Value and Rarity

In [122]:
df_lite.iloc[df_lite["Value"].str.contains("?", regex=False)].head()

Empty DataFrame
Columns: [Vehicle, Value, PI]
Index: []

In [123]:
df_lite[["Value", "Rarity"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]
df_lite.head()

                              Vehicle    Value   Rarity    PI
0     Abarth 124 Spider 2017 Autoshow  43,500    COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35,000    COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow  48,000      RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38,000    COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25,000    COMMON  C596

### Strip leading and trailing whitespace

In [124]:
df_lite["Value"] = df_lite["Value"].str.strip()
df_lite["Rarity"] = df_lite["Rarity"].str.strip()
df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                              Vehicle  Value  Rarity    PI
0     Abarth 124 Spider 2017 Autoshow  43500  COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35000  COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow  48000    RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38000  COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25000  COMMON  C596

## Split original Vehicle column into Brand and Vehicle

In [125]:
df_lite.iloc[df_lite["Vehicle"].str.contains("%")].head()

Empty DataFrame
Columns: [Vehicle, Value, Rarity, PI]
Index: []

### Isolate rows for 2-word vehicle brand names

In [126]:
df1 = df_lite.iloc[df_lite["Vehicle"].str.contains("Alfa Romeo|Alumi Craft|Aston Martin|Auto Union|DS Automobiles|Formula Drift|Funco Motorsports|Hot Wheels|Land Rover|Local Motors|RJ Anderson|Spania GTA|Top Gear|W Motors")]
df1 = df1.loc[~df1["Vehicle"].str.contains("Mercedes-Benz|James Bond Edition")]
df1.head()

,Vehicle,Value,Rarity,PI
7,"Alfa Romeo 155 Q4 1992 A ""Hard-to-Find"" vehicle",250000,EPIC,C541
8,Alfa Romeo 4C 2014 Autoshow,74000,RARE,A770
9,Alfa Romeo 8C Competizione 2007 Autoshow,300000,EPIC,A777
10,Alfa Romeo 8C Competizione Forza Edition 2007 ...,550000,FORZA EDITION,S1899
11,Alfa Romeo 33 Stradale 1968 Autoshow,10000000,LEGENDARY,A716

In [127]:
df1["Vehicle"] = df1["Vehicle"].str.replace(" ", "%", n=1)
df1.head()

,Vehicle,Value,Rarity,PI
7,"Alfa%Romeo 155 Q4 1992 A ""Hard-to-Find"" vehicle",250000,EPIC,C541
8,Alfa%Romeo 4C 2014 Autoshow,74000,RARE,A770
9,Alfa%Romeo 8C Competizione 2007 Autoshow,300000,EPIC,A777
10,Alfa%Romeo 8C Competizione Forza Edition 2007 ...,550000,FORZA EDITION,S1899
11,Alfa%Romeo 33 Stradale 1968 Autoshow,10000000,LEGENDARY,A716

### Isolate rows for 3-word vehicle brand names

In [128]:
df2 = df_lite.iloc[df_lite["Vehicle"].str.contains("AMG Transport|James Bond Edition|LEGO Speed Champions")]
df2.head()

,Vehicle,Value,Rarity,PI
24,AMG Transport Dynamics M12S Warthog CST 2554 A...,850000,LEGENDARY,A756
373,James Bond Edition AMC Hornet X Hatchback 1974...,35000,COMMON,D414
374,James Bond Edition Aston Martin DB5 1964 Autos...,650000,LEGENDARY,B618
375,James Bond Edition Aston Martin DB10 2015 Auto...,220000,LEGENDARY,S1814
376,James Bond Edition Aston Martin DBS 1969 Autos...,650000,RARE,B612

In [129]:
df2["Vehicle"] = df2["Vehicle"].str.replace(" ", "%", n=2)
df2.head()

,Vehicle,Value,Rarity,PI
24,AMG%Transport%Dynamics M12S Warthog CST 2554 A...,850000,LEGENDARY,A756
373,James%Bond%Edition AMC Hornet X Hatchback 1974...,35000,COMMON,D414
374,James%Bond%Edition Aston Martin DB5 1964 Autos...,650000,LEGENDARY,B618
375,James%Bond%Edition Aston Martin DB10 2015 Auto...,220000,LEGENDARY,S1814
376,James%Bond%Edition Aston Martin DBS 1969 Autos...,650000,RARE,B612

In [130]:
df_lite.update(df1)
df_lite.head()

                              Vehicle  Value  Rarity    PI
0     Abarth 124 Spider 2017 Autoshow  43500  COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35000  COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow  48000    RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38000  COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25000  COMMON  C596

In [131]:
df_lite.update(df2)
df_lite.head()

                              Vehicle  Value  Rarity    PI
0     Abarth 124 Spider 2017 Autoshow  43500  COMMON  C577
1   Abarth 595 esseesse 1968 Autoshow  35000  COMMON  D100
2    Abarth 695 Biposto 2016 Autoshow  48000    RARE  B607
3       Abarth Fiat 131 1980 Autoshow  38000  COMMON  D449
4  Acura Integra Type-R 2001 Autoshow  25000  COMMON  C596

### Perform split

In [132]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

    Brand                       Vehicle  Value  Rarity    PI
0  Abarth      124 Spider 2017 Autoshow  43500  COMMON  C577
1  Abarth    595 esseesse 1968 Autoshow  35000  COMMON  D100
2  Abarth     695 Biposto 2016 Autoshow  48000    RARE  B607
3  Abarth        Fiat 131 1980 Autoshow  38000  COMMON  D449
4   Acura  Integra Type-R 2001 Autoshow  25000  COMMON  C596

#### Error checking

In [133]:
df_verify = df_lite.iloc[df_lite["Vehicle"].str.contains("%")]
df_verify.head()

Empty DataFrame
Columns: [Brand, Vehicle, Value, Rarity, PI]
Index: []

#### Replace percent sign in Brand column with whitespace

In [134]:
df_lite["Brand"] = df_lite["Brand"].str.replace("%", " ")
df_lite.head()

    Brand                       Vehicle  Value  Rarity    PI
0  Abarth      124 Spider 2017 Autoshow  43500  COMMON  C577
1  Abarth    595 esseesse 1968 Autoshow  35000  COMMON  D100
2  Abarth     695 Biposto 2016 Autoshow  48000    RARE  B607
3  Abarth        Fiat 131 1980 Autoshow  38000  COMMON  D449
4   Acura  Integra Type-R 2001 Autoshow  25000  COMMON  C596

## Split Vehicle column into Vehicle and Collection

In [135]:
df_lite[["Vehicle", "Year", "Collection"]] = df_lite["Vehicle"].str.extract(r'^(.*)(\d{4})(.*)$')
df_lite = df_lite.iloc[:, [0, 1, 5, 2, 6, 3, 4]]
df_lite.loc[644, "Vehicle"] = "Regalia"
df_lite.loc[645, "Vehicle"] = "Regalia Type-D"
df_lite.loc[[644, 645], "Year"] = "723"
df_lite.loc[644, "Collection"] = "A \"Hard-to-Find\" vehicle"
df_lite.loc[645, "Collection"] = "Skill Tree:  Quartz Regalia"
df_lite.head()

    Brand          Vehicle  Year  Value Collection  Rarity    PI
0  Abarth      124 Spider   2017  43500   Autoshow  COMMON  C577
1  Abarth    595 esseesse   1968  35000   Autoshow  COMMON  D100
2  Abarth     695 Biposto   2016  48000   Autoshow    RARE  B607
3  Abarth        Fiat 131   1980  38000   Autoshow  COMMON  D449
4   Acura  Integra Type-R   2001  25000   Autoshow  COMMON  C596

In [136]:
df_lite["Collection"].value_counts()

Collection
Autoshow                                          402
A "Hard-to-Find" vehicle                          138
Autoshow (DLC: Car Pass)                           42
A possible Wheelspin reward                        40
Complete its Barn Find rumor                       15
                                                 ...
Reach Tier 5 in Horizon Life: Top Gear              1
Reach Tier 7 in Horizon Life: Horizon Super7        1
Skill Tree: TVR Sagaris                             1
Reach Tier 4 in Horizon Life: The Drag Strip        1
Reach Tier 10 in Horizon Life: World's Fastest      1
Name: count, Length: 69, dtype: int64

### Strip leading and trailing whitespace

In [137]:
df_lite["Collection"] = df_lite["Collection"].str.strip()

## Sort by Brand then Year and Vehicle (ascending)

In [138]:
df_lite = df_lite.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df_lite = df_lite.reset_index(drop=True)
df_lite.head(10)

,Brand,Vehicle,Year,Value,Collection,Rarity,PI
0,Abarth,595 esseesse,1968,35000,Autoshow,COMMON,D100
1,Abarth,Fiat 131,1980,38000,Autoshow,COMMON,D449
2,Abarth,695 Biposto,2016,48000,Autoshow,RARE,B607
3,Abarth,124 Spider,2017,43500,Autoshow,COMMON,C577
4,Acura,Integra Type-R,2001,25000,Autoshow,COMMON,C596
5,Acura,RSX Type-S,2002,25000,Autoshow,COMMON,C588
6,Acura,NSX,2017,170000,Autoshow,RARE,S1850
7,Alfa Romeo,P3,1934,10000000,Purchase: Edinburgh Castle,LEGENDARY,B626
8,Alfa Romeo,Giulia Sprint GTA Stradale,1965,300000,Autoshow,RARE,D432
9,Alfa Romeo,Giulia TZ2,1965,2500000,Autoshow,LEGENDARY,B639

## Clean PI column

In [139]:
df_lite[["PI1", "PI2"]] = df_lite["PI"].str.split(r'(?<=D)|(?<=C)|(?<=B)|(?<=A)|(?<=S1)|(?<=S2)', n=1,
                                                                  expand=True)
df_lite.head()

    Brand          Vehicle  Year  Value Collection  Rarity    PI PI1  PI2
0  Abarth    595 esseesse   1968  35000   Autoshow  COMMON  D100   D  100
1  Abarth        Fiat 131   1980  38000   Autoshow  COMMON  D449   D  449
2  Abarth     695 Biposto   2016  48000   Autoshow    RARE  B607   B  607
3  Abarth      124 Spider   2017  43500   Autoshow  COMMON  C577   C  577
4   Acura  Integra Type-R   2001  25000   Autoshow  COMMON  C596   C  596

In [140]:
df_lite["PI1"].value_counts()
# "S1" is the most common class
# followed by A
# then D

PI1
S1    172
A     163
D     123
C     116
B     109
S2     70
Name: count, dtype: int64

In [141]:
df_lite["PI2"].value_counts()
# D 100 is the most common PI value

PI2
100    26
900    17
998     8
800     7
716     6
       ..
661     1
672     1
869     1
926     1
907     1
Name: count, Length: 437, dtype: int64

In [142]:
df_lite["PI"] = df_lite["PI1"] + " " + df_lite["PI2"]
df_lite = df_lite.drop(["PI1", "PI2"], axis="columns")
df_lite.head()

    Brand          Vehicle  Year  Value Collection  Rarity     PI
0  Abarth    595 esseesse   1968  35000   Autoshow  COMMON  D 100
1  Abarth        Fiat 131   1980  38000   Autoshow  COMMON  D 449
2  Abarth     695 Biposto   2016  48000   Autoshow    RARE  B 607
3  Abarth      124 Spider   2017  43500   Autoshow  COMMON  C 577
4   Acura  Integra Type-R   2001  25000   Autoshow  COMMON  C 596

In [143]:
df_lite["Owned"] = pd.Series(dtype="string")
df_lite.head()

    Brand          Vehicle  Year  Value Collection  Rarity     PI Owned
0  Abarth    595 esseesse   1968  35000   Autoshow  COMMON  D 100  <NA>
1  Abarth        Fiat 131   1980  38000   Autoshow  COMMON  D 449  <NA>
2  Abarth     695 Biposto   2016  48000   Autoshow    RARE  B 607  <NA>
3  Abarth      124 Spider   2017  43500   Autoshow  COMMON  C 577  <NA>
4   Acura  Integra Type-R   2001  25000   Autoshow  COMMON  C 596  <NA>

## Filter to Wheelspin-exclusive cars

In [144]:
df_lite.dtypes

Brand            str
Vehicle          str
Year             str
Value          int64
Collection       str
Rarity           str
PI               str
Owned         string
dtype: object

In [145]:
df_wheelspin = df_lite.loc[df_lite["Collection"].str.contains("Wheelspin")]
df_wheelspin.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
13,Alfa Romeo,8C Competizione Forza Edition,2007,550000,A possible Wheelspin reward,FORZA EDITION,S1 899,<NA>
16,Alfa Romeo,Giulia Quadrifoglio Forza Edition,2017,370000,A possible Wheelspin reward,FORZA EDITION,S1 900,<NA>
20,Alumi Craft,Class 10 Race Car Forza Edition,2015,350000,A possible Wheelspin reward,FORZA EDITION,A 800,<NA>
37,Aston Martin,Vulcan Forza Edition,2016,1750000,A possible Wheelspin reward,FORZA EDITION,S2 998,<NA>
52,Audi,TT RS Coupé,2010,66000,A possible Wheelspin reward,RARE,A 722,<NA>

In [146]:
df_wheelspin["Rarity"].value_counts()

Rarity
FORZA EDITION    16
RARE             10
COMMON            7
EPIC              6
LEGENDARY         1
Name: count, dtype: int64

### Associate each rarity with numerical value

In [147]:
rarity_dict = {"COMMON": 1, "RARE": 2, "EPIC": 3, "LEGENDARY": 4, "FORZA EDITION": 5}
df_wheelspin["Rarity Value"] = df_wheelspin["Rarity"].map(rarity_dict)
df_wheelspin.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned,Rarity Value
13,Alfa Romeo,8C Competizione Forza Edition,2007,550000,A possible Wheelspin reward,FORZA EDITION,S1 899,<NA>,5
16,Alfa Romeo,Giulia Quadrifoglio Forza Edition,2017,370000,A possible Wheelspin reward,FORZA EDITION,S1 900,<NA>,5
20,Alumi Craft,Class 10 Race Car Forza Edition,2015,350000,A possible Wheelspin reward,FORZA EDITION,A 800,<NA>,5
37,Aston Martin,Vulcan Forza Edition,2016,1750000,A possible Wheelspin reward,FORZA EDITION,S2 998,<NA>,5
52,Audi,TT RS Coupé,2010,66000,A possible Wheelspin reward,RARE,A 722,<NA>,2

### Sort Wheelspin-exclusives according to Rarity

In [148]:
df_wheelspin = df_wheelspin.sort_values(["Rarity Value", "Brand"], ascending=[True, True])
df_wheelspin.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned,Rarity Value
247,Ford,SVT Cobra R,1993,28000,A possible Wheelspin reward,COMMON,C 533,<NA>,1
254,Ford,Crown Victoria Police Interceptor,2010,25000,A possible Wheelspin reward,COMMON,C 521,<NA>,1
310,Honda,Civic Type-R,2004,25000,A possible Wheelspin reward,COMMON,B 610,<NA>,1
387,Jeep,Grand Cherokee SRT,2014,80000,A possible Wheelspin reward,COMMON,A 711,<NA>,1
452,Lotus,Elise 111S,2005,45000,A possible Wheelspin reward,COMMON,B 650,<NA>,1

In [149]:
df_wheelspin = df_wheelspin.drop("Rarity Value", axis=1)
df_wheelspin.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
247,Ford,SVT Cobra R,1993,28000,A possible Wheelspin reward,COMMON,C 533,<NA>
254,Ford,Crown Victoria Police Interceptor,2010,25000,A possible Wheelspin reward,COMMON,C 521,<NA>
310,Honda,Civic Type-R,2004,25000,A possible Wheelspin reward,COMMON,B 610,<NA>
387,Jeep,Grand Cherokee SRT,2014,80000,A possible Wheelspin reward,COMMON,A 711,<NA>
452,Lotus,Elise 111S,2005,45000,A possible Wheelspin reward,COMMON,B 650,<NA>

In [150]:
df_wheelspin["Rarity"].value_counts()

Rarity
FORZA EDITION    16
RARE             10
COMMON            7
EPIC              6
LEGENDARY         1
Name: count, dtype: int64

### Convert dataframe to csv

In [ ]:
df_lite.to_csv("FH3/FH3-0-masterlist.csv", index=False, encoding="utf-8-sig")
df_price.to_csv("FH3/FH3-1-price.csv", index=False, encoding="utf-8-sig")