In [25]:
import pandas as pd

In [26]:
df = pd.read_csv("FH5/FH5-0-owned.csv", encoding="cp1252")
df.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,NaN
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,0
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,0
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,NaN
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,NaN

In [27]:
df.dtypes

Brand           str
Vehicle         str
Year          int64
 Value          str
Collection      str
Rarity          str
PI              str
Owned           str
dtype: object

In [28]:
df["Year"] = df["Year"].astype(str)
df.dtypes

Brand         str
Vehicle       str
Year          str
 Value        str
Collection    str
Rarity        str
PI            str
Owned         str
dtype: object

In [29]:
df["Owned"] = df["Owned"].fillna("1")
df.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,1
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,0
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,0
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,1
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,1

In [30]:
df["Owned"].value_counts()

Owned
1    684
0    167
-     51
Name: count, dtype: int64

In [31]:
df = df.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df = df.reset_index(drop=True)
df.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,1
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,0
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,0
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,1
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,1