In [1]:
import pandas as pd

# Import raw data for preprocessing

In [2]:
filename = "FH5-cars-list"
tables = pd.read_html("raw-website/" + filename + ".htm")
df = tables[1]
df.head(10)

,Vehicle,🔓,🦄,📅,🌍,Value,Sp,Ha,Ac,La,Br,Of,PI
0,"Abarth 124 Spider 2017""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",5.2,4.7,3.8,4.6,3.3,5.5,C562
1,Abarth 595 esseesse 1968Autoshow,NaN,NaN,NaN,NaN,"35,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.1,D100
2,"Abarth 695 Biposto 2016""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",4.9,5.3,4.7,4.4,4.8,5.0,B657
3,"Abarth Fiat 131 1980""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.8,C510
4,Acura Integra Type-R 2001Autoshow,NaN,NaN,NaN,NaN,"25,000 CRCOMMON",5.6,5.1,3.9,3.1,3.4,5.1,C596
5,Acura NSX 2017Autoshow,NaN,NaN,NaN,NaN,"170,000 CRRARE",7.0,7.0,9.2,10.0,7.1,4.7,S1831
6,Acura RSX Type-S 2002Autoshow,NaN,NaN,NaN,NaN,"25,000 CRCOMMON",5.6,5.1,3.9,3.0,3.5,5.3,C585
7,"Alfa Romeo 155 Q4 1992""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",5.4,4.4,4.0,4.3,2.9,5.7,C561
8,Alfa Romeo 33 Stradale 1968Autoshow,NaN,NaN,NaN,NaN,"15,000,000 CRLEGENDARY",6.2,4.4,5.7,5.7,3.6,5.0,A707
9,"Alfa Romeo 4C 2014""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRRARE",5.9,5.7,4.8,7.0,5.2,5.0,A755

## Remove redundant columns

In [3]:
columns_to_drop = [1, 2, 3, 4]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,Of,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRCOMMON",5.2,4.7,3.8,4.6,3.3,5.5,C562
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.1,D100
2,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,4.4,4.8,5.0,B657
3,"Abarth Fiat 131 1980""Hard to Find""","250,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.8,C510
4,Acura Integra Type-R 2001Autoshow,"25,000 CRCOMMON",5.6,5.1,3.9,3.1,3.4,5.1,C596

## Expand abbreviated columns

In [4]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,OffRd,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRCOMMON",5.2,4.7,3.8,4.6,3.3,5.5,C562
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.1,D100
2,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,4.4,4.8,5.0,B657
3,"Abarth Fiat 131 1980""Hard to Find""","250,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.8,C510
4,Acura Integra Type-R 2001Autoshow,"25,000 CRCOMMON",5.6,5.1,3.9,3.1,3.4,5.1,C596

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 902 entries, 0 to 901
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   902 non-null    str
 1   Value     902 non-null    str
 2   Speed     902 non-null    float64
 3   Handling  902 non-null    float64
 4   Accel     902 non-null    float64
 5   Launch    902 non-null    float64
 6   Braking   902 non-null    float64
 7   OffRd     902 non-null    float64
 8   PI        902 non-null    str
dtypes: float64(6), str(3)
memory usage: 63.6 KB

## Remove stat columns from df_lite

In [6]:
columns_to_drop = [2, 3, 4, 5, 6, 7]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                                 Vehicle             Value    PI
0   Abarth 124 Spider 2017"Hard to Find"  250,000 CRCOMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35,000 CRCOMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250,000 CRCOMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250,000 CRCOMMON  C510
4      Acura Integra Type-R 2001Autoshow   25,000 CRCOMMON  C596

## Split original Value column into Value and Rarity

In [7]:
df_lite[["Value", "Rarity"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].str.replace("?", "0")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                                 Vehicle   Value  Rarity    PI
0   Abarth 124 Spider 2017"Hard to Find"  250000  COMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4      Acura Integra Type-R 2001Autoshow   25000  COMMON  C596

## Split original Vehicle column into Brand and Vehicle

### Isolate rows for 2-word vehicle brand names

In [8]:
df1 = df_lite.iloc[df_lite["Vehicle"].str.contains("Alfa|Aston|Auto Union|Automobili Pininfarina|Extreme E|Formula Drift|Forsberg Racing|Funco Motorsports|Land Rover|Local Motors|RJ Anderson|SIERRA Cars|Spania GTA|Universal Studios|W Motors")]
df1.head()

                                          Vehicle     Value     Rarity    PI
7            Alfa Romeo 155 Q4 1992"Hard to Find"    250000     COMMON  C561
8             Alfa Romeo 33 Stradale 1968Autoshow  15000000  LEGENDARY  A707
9                Alfa Romeo 4C 2014"Hard to Find"    250000       RARE  A755
10  Alfa Romeo 8C Competizione 2007"Hard to Find"    300000       EPIC  A755
11    Alfa Romeo Giulia Quadrifoglio 2017Autoshow    120000       RARE  A775

#### Replace first whitespace with underscore

In [9]:
df1["Vehicle"] = df1["Vehicle"].str.replace(" ", "_", n=1)
df1.head()

                                          Vehicle     Value     Rarity    PI
7            Alfa_Romeo 155 Q4 1992"Hard to Find"    250000     COMMON  C561
8             Alfa_Romeo 33 Stradale 1968Autoshow  15000000  LEGENDARY  A707
9                Alfa_Romeo 4C 2014"Hard to Find"    250000       RARE  A755
10  Alfa_Romeo 8C Competizione 2007"Hard to Find"    300000       EPIC  A755
11    Alfa_Romeo Giulia Quadrifoglio 2017Autoshow    120000       RARE  A775

### Separate filtering for Hot Wheels

In [10]:
df_hw = df_lite.iloc[df_lite["Vehicle"].str.contains("Hot Wheels")]
df_hw = df_hw.loc[~df_hw["Vehicle"].str.contains("Brabham|Chevrolet|Hennessey|Mosler|SUBARU|Schuppan|SIERRA")]
df_hw.head()

,Vehicle,Value,Rarity,PI
420,"Hot Wheels 2JetZ 2018HW Academy: ""Chapter 4: T...",250000,LEGENDARY,S1854
421,"Hot Wheels Bad to the Blade 2012HW Academy: ""T...",200000,EPIC,S2998
422,"Hot Wheels Baja Bone Shaker 2013HW Academy: ""H...",150000,LEGENDARY,B700
423,"Hot Wheels Bone Shaker 2011Autoshow, Wheelspin...",150000,LEGENDARY,A790
424,"Hot Wheels Deora II 2000HW Academy: ""Here We P...",500000,LEGENDARY,A800

In [11]:
df_hw["Vehicle"] = df_hw["Vehicle"].str.replace(" ", "_", n=1)
df_hw.head()

,Vehicle,Value,Rarity,PI
420,"Hot_Wheels 2JetZ 2018HW Academy: ""Chapter 4: T...",250000,LEGENDARY,S1854
421,"Hot_Wheels Bad to the Blade 2012HW Academy: ""T...",200000,EPIC,S2998
422,"Hot_Wheels Baja Bone Shaker 2013HW Academy: ""H...",150000,LEGENDARY,B700
423,"Hot_Wheels Bone Shaker 2011Autoshow, Wheelspin...",150000,LEGENDARY,A790
424,"Hot_Wheels Deora II 2000HW Academy: ""Here We P...",500000,LEGENDARY,A800

### Isolate rows for 3-word vehicle brand names

In [12]:
df2 = df_lite.iloc[df_lite["Vehicle"].str.contains("AMG Transport|Casey Currie|Fast and Furious|Gordon Murray|Lynk & Co")]
df2.head()

,Vehicle,Value,Rarity,PI
22,AMG Transport Dynamics M12S Warthog CST 2554Au...,850000,LEGENDARY,A719
135,Casey Currie Motorsports #4402 Ultra 4 'Trophy...,500000,EPIC,A745
222,Fast and Furious Chevrolet Impala Super Sport ...,300000,LEGENDARY,S1836
223,Fast and Furious Datsun 240Z 'Fast X' 1973Auto...,300000,LEGENDARY,S1838
224,Fast and Furious Dodge Charger 'Fast X' 1970Au...,300000,LEGENDARY,S1855

#### Replace first two whitespace with underscore

In [13]:
df2["Vehicle"] = df2["Vehicle"].str.replace(" ", "_", n=2)
df2.head()

,Vehicle,Value,Rarity,PI
22,AMG_Transport_Dynamics M12S Warthog CST 2554Au...,850000,LEGENDARY,A719
135,Casey_Currie_Motorsports #4402 Ultra 4 'Trophy...,500000,EPIC,A745
222,Fast_and_Furious Chevrolet Impala Super Sport ...,300000,LEGENDARY,S1836
223,Fast_and_Furious Datsun 240Z 'Fast X' 1973Auto...,300000,LEGENDARY,S1838
224,Fast_and_Furious Dodge Charger 'Fast X' 1970Au...,300000,LEGENDARY,S1855

### Update df_lite with altered rows

In [14]:
df_lite.update(df1)
df_lite.head()

                                 Vehicle   Value  Rarity    PI
0   Abarth 124 Spider 2017"Hard to Find"  250000  COMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4      Acura Integra Type-R 2001Autoshow   25000  COMMON  C596

In [15]:
df_lite.update(df2)
df_lite.head()

                                 Vehicle   Value  Rarity    PI
0   Abarth 124 Spider 2017"Hard to Find"  250000  COMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4      Acura Integra Type-R 2001Autoshow   25000  COMMON  C596

In [16]:
df_lite.update(df_hw)
df_lite.head()

                                 Vehicle   Value  Rarity    PI
0   Abarth 124 Spider 2017"Hard to Find"  250000  COMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4      Acura Integra Type-R 2001Autoshow   25000  COMMON  C596

### Perform split

In [17]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

    Brand                         Vehicle   Value  Rarity    PI
0  Abarth   124 Spider 2017"Hard to Find"  250000  COMMON  C562
1  Abarth       595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth  695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3  Abarth     Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4   Acura     Integra Type-R 2001Autoshow   25000  COMMON  C596

#### Error checking

In [18]:
df_verify = df_lite.iloc[df_lite["Vehicle"].str.contains("_")]
df_verify.head()

Empty DataFrame
Columns: [Brand, Vehicle, Value, Rarity, PI]
Index: []

#### Replace underscores in Brand column with whitespace

In [19]:
df_lite["Brand"] = df_lite["Brand"].str.replace("_", " ")
df_lite.head()

    Brand                         Vehicle   Value  Rarity    PI
0  Abarth   124 Spider 2017"Hard to Find"  250000  COMMON  C562
1  Abarth       595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth  695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3  Abarth     Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4   Acura     Integra Type-R 2001Autoshow   25000  COMMON  C596

In [ ]:
df_lite[["Vehicle", "Year", "Collection"]] = df_lite["Vehicle"].str.extract(r'^(.*)(\d{4})(.*)$')
df_lite.head()

## Split Vehicle column into Vehicle and Collection

In [ ]:
df_lite[["Vehicle", "Collection"]] = df_lite["Vehicle"].str.split(r'(?=Autoshow)|(?=Barn)|(?=Wheelspin)|(?=\"Hard)|(?=Gifted)|(?=Car\ Collector)|(?=Car\ Mastery)|(?=Horizon\ Story)|(?=Midnight\ Battle)', n=1,
                                                                  expand=True)
df_lite.head()

In [ ]:
df_lite["Collection"].value_counts()

## Split Vehicle Column into Year and Vehicle

In [ ]:
df_lite[["Vehicle", "Year"]] = df_lite["Vehicle"].str.rsplit(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 6, 1, 2, 3, 5, 4]]
df_lite.head()

## Sort by Brand then Year (ascending)

In [ ]:
df_lite = df_lite.sort_values(["Brand", "Year"], ascending=[True, True], key=lambda col: col.str.lower())
df_lite = df_lite.reset_index(drop=True)
df_lite.head(10)

## Clean PI column

In [ ]:
df_lite[["PI1", "PI2"]] = df_lite["PI"].str.split(r'(?<=D)|(?<=C)|(?<=B)|(?<=A)|(?<=S1)|(?<=S2)', n=1,
                                                                  expand=True)
df_lite.head()

In [ ]:
df_lite["PI1"].value_counts()
# "A" is the most common class
# followed by C
# then S1

In [ ]:
df_lite["PI2"].value_counts()
# S1 900 is the most common PI value

In [ ]:
df_lite["PI"] = df_lite["PI1"] + " " + df_lite["PI2"]
df_lite = df_lite.drop(["PI1", "PI2"], axis="columns")
df_lite.head()

In [ ]:
df_lite["Owned"] = pd.Series(dtype="string")
df_lite.head()

### Convert dataframe to csv

In [ ]:
df_lite.to_csv("FH3/FH3-0-masterlist.csv", index=False)