In [26]:
import pandas as pd

# Import raw data for preprocessing

In [27]:
filename = "FH5-cars-list"
tables = pd.read_html("raw-website/" + filename + ".htm")
df = tables[1]
df.head(10)

,Vehicle,🔓,🦄,📅,🌍,Value,Sp,Ha,Ac,La,Br,Of,PI
0,"Abarth 124 Spider 2017""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",5.2,4.7,3.8,4.6,3.3,5.5,C562
1,Abarth 595 esseesse 1968Autoshow,NaN,NaN,NaN,NaN,"35,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.1,D100
2,"Abarth 695 Biposto 2016""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",4.9,5.3,4.7,4.4,4.8,5.0,B657
3,"Abarth Fiat 131 1980""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.8,C510
4,Acura Integra Type-R 2001Autoshow,NaN,NaN,NaN,NaN,"25,000 CRCOMMON",5.6,5.1,3.9,3.1,3.4,5.1,C596
5,Acura NSX 2017Autoshow,NaN,NaN,NaN,NaN,"170,000 CRRARE",7.0,7.0,9.2,10.0,7.1,4.7,S1831
6,Acura RSX Type-S 2002Autoshow,NaN,NaN,NaN,NaN,"25,000 CRCOMMON",5.6,5.1,3.9,3.0,3.5,5.3,C585
7,"Alfa Romeo 155 Q4 1992""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",5.4,4.4,4.0,4.3,2.9,5.7,C561
8,Alfa Romeo 33 Stradale 1968Autoshow,NaN,NaN,NaN,NaN,"15,000,000 CRLEGENDARY",6.2,4.4,5.7,5.7,3.6,5.0,A707
9,"Alfa Romeo 4C 2014""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRRARE",5.9,5.7,4.8,7.0,5.2,5.0,A755

## Remove redundant columns

In [28]:
columns_to_drop = [1, 2, 3, 4]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,Of,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRCOMMON",5.2,4.7,3.8,4.6,3.3,5.5,C562
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.1,D100
2,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,4.4,4.8,5.0,B657
3,"Abarth Fiat 131 1980""Hard to Find""","250,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.8,C510
4,Acura Integra Type-R 2001Autoshow,"25,000 CRCOMMON",5.6,5.1,3.9,3.1,3.4,5.1,C596

## Expand abbreviated columns

In [29]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,OffRd,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRCOMMON",5.2,4.7,3.8,4.6,3.3,5.5,C562
1,Abarth 595 esseesse 1968Autoshow,"35,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.1,D100
2,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,4.4,4.8,5.0,B657
3,"Abarth Fiat 131 1980""Hard to Find""","250,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.8,C510
4,Acura Integra Type-R 2001Autoshow,"25,000 CRCOMMON",5.6,5.1,3.9,3.1,3.4,5.1,C596

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 902 entries, 0 to 901
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   902 non-null    str
 1   Value     902 non-null    str
 2   Speed     902 non-null    float64
 3   Handling  902 non-null    float64
 4   Accel     902 non-null    float64
 5   Launch    902 non-null    float64
 6   Braking   902 non-null    float64
 7   OffRd     902 non-null    float64
 8   PI        902 non-null    str
dtypes: float64(6), str(3)
memory usage: 63.6 KB

## Remove stat columns from df_lite

In [31]:
columns_to_drop = [2, 3, 4, 5, 6, 7]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                                 Vehicle             Value    PI
0   Abarth 124 Spider 2017"Hard to Find"  250,000 CRCOMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35,000 CRCOMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250,000 CRCOMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250,000 CRCOMMON  C510
4      Acura Integra Type-R 2001Autoshow   25,000 CRCOMMON  C596

## Split original Value column into Value and Rarity

In [32]:
df_lite[["Value", "Rarity"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].str.replace("?", "0")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                                 Vehicle   Value  Rarity    PI
0   Abarth 124 Spider 2017"Hard to Find"  250000  COMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4      Acura Integra Type-R 2001Autoshow   25000  COMMON  C596

## Split original Vehicle column into Brand and Vehicle

### Isolate rows for 2-word vehicle brand names

In [33]:
df1 = df_lite.iloc[df_lite["Vehicle"].str.contains("Alfa|Aston|Auto Union|Automobili Pininfarina|Extreme E|Formula Drift|Forsberg Racing|Funco Motorsports|Land Rover|Local Motors|RJ Anderson|SIERRA Cars|Spania GTA|Universal Studios|W Motors")]
df1.head()

                                          Vehicle     Value     Rarity    PI
7            Alfa Romeo 155 Q4 1992"Hard to Find"    250000     COMMON  C561
8             Alfa Romeo 33 Stradale 1968Autoshow  15000000  LEGENDARY  A707
9                Alfa Romeo 4C 2014"Hard to Find"    250000       RARE  A755
10  Alfa Romeo 8C Competizione 2007"Hard to Find"    300000       EPIC  A755
11    Alfa Romeo Giulia Quadrifoglio 2017Autoshow    120000       RARE  A775

#### Replace first whitespace with underscore

In [34]:
df1["Vehicle"] = df1["Vehicle"].str.replace(" ", "_", n=1)
df1.head()

                                          Vehicle     Value     Rarity    PI
7            Alfa_Romeo 155 Q4 1992"Hard to Find"    250000     COMMON  C561
8             Alfa_Romeo 33 Stradale 1968Autoshow  15000000  LEGENDARY  A707
9                Alfa_Romeo 4C 2014"Hard to Find"    250000       RARE  A755
10  Alfa_Romeo 8C Competizione 2007"Hard to Find"    300000       EPIC  A755
11    Alfa_Romeo Giulia Quadrifoglio 2017Autoshow    120000       RARE  A775

### Separate filtering for Hot Wheels

In [35]:
df_hw = df_lite.iloc[df_lite["Vehicle"].str.contains("Hot Wheels")]
df_hw = df_hw.loc[~df_hw["Vehicle"].str.contains("Brabham|Chevrolet|Hennessey|Mosler|SUBARU|Schuppan|SIERRA")]
df_hw.head()

,Vehicle,Value,Rarity,PI
420,"Hot Wheels 2JetZ 2018HW Academy: ""Chapter 4: T...",250000,LEGENDARY,S1854
421,"Hot Wheels Bad to the Blade 2012HW Academy: ""T...",200000,EPIC,S2998
422,"Hot Wheels Baja Bone Shaker 2013HW Academy: ""H...",150000,LEGENDARY,B700
423,"Hot Wheels Bone Shaker 2011Autoshow, Wheelspin...",150000,LEGENDARY,A790
424,"Hot Wheels Deora II 2000HW Academy: ""Here We P...",500000,LEGENDARY,A800

In [36]:
df_hw["Vehicle"] = df_hw["Vehicle"].str.replace(" ", "_", n=1)
df_hw.head()

,Vehicle,Value,Rarity,PI
420,"Hot_Wheels 2JetZ 2018HW Academy: ""Chapter 4: T...",250000,LEGENDARY,S1854
421,"Hot_Wheels Bad to the Blade 2012HW Academy: ""T...",200000,EPIC,S2998
422,"Hot_Wheels Baja Bone Shaker 2013HW Academy: ""H...",150000,LEGENDARY,B700
423,"Hot_Wheels Bone Shaker 2011Autoshow, Wheelspin...",150000,LEGENDARY,A790
424,"Hot_Wheels Deora II 2000HW Academy: ""Here We P...",500000,LEGENDARY,A800

### Isolate rows for 3-word vehicle brand names

In [37]:
df2 = df_lite.iloc[df_lite["Vehicle"].str.contains("AMG Transport|Casey Currie|Fast and Furious|Gordon Murray|Lynk & Co")]
df2.head()

,Vehicle,Value,Rarity,PI
22,AMG Transport Dynamics M12S Warthog CST 2554Au...,850000,LEGENDARY,A719
135,Casey Currie Motorsports #4402 Ultra 4 'Trophy...,500000,EPIC,A745
222,Fast and Furious Chevrolet Impala Super Sport ...,300000,LEGENDARY,S1836
223,Fast and Furious Datsun 240Z 'Fast X' 1973Auto...,300000,LEGENDARY,S1838
224,Fast and Furious Dodge Charger 'Fast X' 1970Au...,300000,LEGENDARY,S1855

#### Replace first two whitespace with underscore

In [38]:
df2["Vehicle"] = df2["Vehicle"].str.replace(" ", "_", n=2)
df2.head()

,Vehicle,Value,Rarity,PI
22,AMG_Transport_Dynamics M12S Warthog CST 2554Au...,850000,LEGENDARY,A719
135,Casey_Currie_Motorsports #4402 Ultra 4 'Trophy...,500000,EPIC,A745
222,Fast_and_Furious Chevrolet Impala Super Sport ...,300000,LEGENDARY,S1836
223,Fast_and_Furious Datsun 240Z 'Fast X' 1973Auto...,300000,LEGENDARY,S1838
224,Fast_and_Furious Dodge Charger 'Fast X' 1970Au...,300000,LEGENDARY,S1855

### Update df_lite with altered rows

In [39]:
df_lite.update(df1)
df_lite.head()

                                 Vehicle   Value  Rarity    PI
0   Abarth 124 Spider 2017"Hard to Find"  250000  COMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4      Acura Integra Type-R 2001Autoshow   25000  COMMON  C596

In [40]:
df_lite.update(df2)
df_lite.head()

                                 Vehicle   Value  Rarity    PI
0   Abarth 124 Spider 2017"Hard to Find"  250000  COMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4      Acura Integra Type-R 2001Autoshow   25000  COMMON  C596

In [41]:
df_lite.update(df_hw)
df_lite.head()

                                 Vehicle   Value  Rarity    PI
0   Abarth 124 Spider 2017"Hard to Find"  250000  COMMON  C562
1       Abarth 595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3     Abarth Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4      Acura Integra Type-R 2001Autoshow   25000  COMMON  C596

### Perform split

In [42]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

    Brand                         Vehicle   Value  Rarity    PI
0  Abarth   124 Spider 2017"Hard to Find"  250000  COMMON  C562
1  Abarth       595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth  695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3  Abarth     Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4   Acura     Integra Type-R 2001Autoshow   25000  COMMON  C596

#### Error checking

In [43]:
df_verify = df_lite.iloc[df_lite["Vehicle"].str.contains("_")]
df_verify.head()

Empty DataFrame
Columns: [Brand, Vehicle, Value, Rarity, PI]
Index: []

#### Replace underscores in Brand column with whitespace

In [44]:
df_lite["Brand"] = df_lite["Brand"].str.replace("_", " ")
df_lite.head()

    Brand                         Vehicle   Value  Rarity    PI
0  Abarth   124 Spider 2017"Hard to Find"  250000  COMMON  C562
1  Abarth       595 esseesse 1968Autoshow   35000  COMMON  D100
2  Abarth  695 Biposto 2016"Hard to Find"  250000  COMMON  B657
3  Abarth     Fiat 131 1980"Hard to Find"  250000  COMMON  C510
4   Acura     Integra Type-R 2001Autoshow   25000  COMMON  C596

## Split into 3 columns using str.extract and regex

### Filter "Car Mastery" rows separately

In [45]:
df_cm = df_lite.iloc[df_lite["Vehicle"].str.contains("Car Mastery")]
df_cm.head()

,Brand,Vehicle,Value,Rarity,PI
186,DeBerti,Wrangler Unlimited 2013Car Mastery: 2012 Jeep ...,200000,EPIC,A749
192,Dodge,Charger Daytona HEMI 1969Car Mastery: 1969 Dod...,900000,EPIC,C595
417,Hoonigan,Mazda RX-7 Twerkstallion 1992Car Mastery: 1990...,50000,RARE,A799
418,Hoonigan,Rauh-Welt Begriff Porsche 911 Turbo 1991Car Ma...,160000,RARE,S1811
494,Lamborghini,Diablo GTR 1999Car Mastery: 1997 Lamborghini D...,1000000,EPIC,S1881

In [46]:
df_cm[["Vehicle", "Year", "Collection"]] = df_cm["Vehicle"].str.extract(r'^(.*?)(\d{4})(.*)$')
df_cm = df_cm.iloc[:, [0, 1, 5, 2, 6, 3, 4]]
df_cm.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI
186,DeBerti,Wrangler Unlimited,2013,200000,Car Mastery: 2012 Jeep Wrangler Rubicon,EPIC,A749
192,Dodge,Charger Daytona HEMI,1969,900000,Car Mastery: 1969 Dodge Charger R/T,EPIC,C595
417,Hoonigan,Mazda RX-7 Twerkstallion,1992,50000,Car Mastery: 1990 Mazda Savanna RX-7,RARE,A799
418,Hoonigan,Rauh-Welt Begriff Porsche 911 Turbo,1991,160000,Car Mastery: 1995 Porsche 911 GT2,RARE,S1811
494,Lamborghini,Diablo GTR,1999,1000000,Car Mastery: 1997 Lamborghini Diablo SV,EPIC,S1881

### Perform general splitting

In [47]:
df_lite[["Vehicle", "Year", "Collection"]] = df_lite["Vehicle"].str.extract(r'^(.*)(\d{4})(.*)$')
df_lite = df_lite.iloc[:, [0, 1, 5, 2, 6, 3, 4]]
df_lite.head()

    Brand          Vehicle  Year   Value      Collection  Rarity    PI
0  Abarth      124 Spider   2017  250000  "Hard to Find"  COMMON  C562
1  Abarth    595 esseesse   1968   35000        Autoshow  COMMON  D100
2  Abarth     695 Biposto   2016  250000  "Hard to Find"  COMMON  B657
3  Abarth        Fiat 131   1980  250000  "Hard to Find"  COMMON  C510
4   Acura  Integra Type-R   2001   25000        Autoshow  COMMON  C596

#### Update with df_cm

In [48]:
df_lite.update(df_cm)
df_lite.head()

    Brand          Vehicle  Year   Value      Collection  Rarity    PI
0  Abarth      124 Spider   2017  250000  "Hard to Find"  COMMON  C562
1  Abarth    595 esseesse   1968   35000        Autoshow  COMMON  D100
2  Abarth     695 Biposto   2016  250000  "Hard to Find"  COMMON  B657
3  Abarth        Fiat 131   1980  250000  "Hard to Find"  COMMON  C510
4   Acura  Integra Type-R   2001   25000        Autoshow  COMMON  C596

In [49]:
df_lite.iloc[df_lite["Collection"].str.contains("Car Mastery")].head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI
186,DeBerti,Wrangler Unlimited,2013,200000,Car Mastery: 2012 Jeep Wrangler Rubicon,EPIC,A749
192,Dodge,Charger Daytona HEMI,1969,900000,Car Mastery: 1969 Dodge Charger R/T,EPIC,C595
417,Hoonigan,Mazda RX-7 Twerkstallion,1992,50000,Car Mastery: 1990 Mazda Savanna RX-7,RARE,A799
418,Hoonigan,Rauh-Welt Begriff Porsche 911 Turbo,1991,160000,Car Mastery: 1995 Porsche 911 GT2,RARE,S1811
494,Lamborghini,Diablo GTR,1999,1000000,Car Mastery: 1997 Lamborghini Diablo SV,EPIC,S1881

## Sort by Brand then Year and Vehicle (ascending)

In [50]:
df_lite.dtypes

Brand           str
Vehicle         str
Year            str
Value         int64
Collection      str
Rarity          str
PI              str
dtype: object

In [51]:
df_lite = df_lite.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df_lite = df_lite.reset_index(drop=True)
df_lite.head(10)

,Brand,Vehicle,Year,Value,Collection,Rarity,PI
0,Abarth,595 esseesse,1968,35000,Autoshow,COMMON,D100
1,Abarth,Fiat 131,1980,250000,"""Hard to Find""",COMMON,C510
2,Abarth,695 Biposto,2016,250000,"""Hard to Find""",COMMON,B657
3,Abarth,124 Spider,2017,250000,"""Hard to Find""",COMMON,C562
4,Acura,Integra Type-R,2001,25000,Autoshow,COMMON,C596
5,Acura,RSX Type-S,2002,25000,Autoshow,COMMON,C585
6,Acura,NSX,2017,170000,Autoshow,RARE,S1831
7,Alfa Romeo,Giulia Sprint GTA Stradale,1965,300000,Autoshow,RARE,D486
8,Alfa Romeo,Giulia TZ2,1965,4000000,Autoshow,LEGENDARY,B641
9,Alfa Romeo,33 Stradale,1968,15000000,Autoshow,LEGENDARY,A707

## Clean PI column

In [52]:
df_lite[["PI1", "PI2"]] = df_lite["PI"].str.split(r'(?<=D)|(?<=C)|(?<=B)|(?<=A)|(?<=S1)|(?<=S2)', n=1,
                                                                  expand=True)
df_lite.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,PI1,PI2
0,Abarth,595 esseesse,1968,35000,Autoshow,COMMON,D100,D,100
1,Abarth,Fiat 131,1980,250000,"""Hard to Find""",COMMON,C510,C,510
2,Abarth,695 Biposto,2016,250000,"""Hard to Find""",COMMON,B657,B,657
3,Abarth,124 Spider,2017,250000,"""Hard to Find""",COMMON,C562,C,562
4,Acura,Integra Type-R,2001,25000,Autoshow,COMMON,C596,C,596

### Stats

In [53]:
df_lite["PI1"].value_counts()
# "A" is the most common class
# followed by S1
# then B

PI1
A     206
S1    205
B     164
C     125
D     124
S2     78
Name: count, dtype: int64

In [54]:
df_lite["PI2"].value_counts()
# A 800 is the most common PI value

PI2
800    19
100    17
900    14
748    12
998    10
       ..
340     1
527     1
886     1
198     1
136     1
Name: count, Length: 464, dtype: int64

In [55]:
df_lite["Year"].value_counts()

Year
2018    58
2022    47
2020    41
2019    40
2021    39
        ..
1929     1
1954     1
1933     1
1951     1
1945     1
Name: count, Length: 85, dtype: int64

In [56]:
df_lite["Value"].value_counts()

Value
250000    168
500000     55
300000     41
25000      40
20000      32
         ...
51000       1
32000       1
10000       1
28800       1
64000       1
Name: count, Length: 190, dtype: int64

In [57]:
df_lite["Rarity"].value_counts()

Rarity
RARE             289
EPIC             249
COMMON           173
LEGENDARY        170
FORZA EDITION     19
ANNIVERSARY        1
DONUT EDITION      1
Name: count, dtype: int64

In [58]:
df_lite["PI"] = df_lite["PI1"] + " " + df_lite["PI2"]
df_lite = df_lite.drop(["PI1", "PI2"], axis="columns")
df_lite.head()

    Brand          Vehicle  Year   Value      Collection  Rarity     PI
0  Abarth    595 esseesse   1968   35000        Autoshow  COMMON  D 100
1  Abarth        Fiat 131   1980  250000  "Hard to Find"  COMMON  C 510
2  Abarth     695 Biposto   2016  250000  "Hard to Find"  COMMON  B 657
3  Abarth      124 Spider   2017  250000  "Hard to Find"  COMMON  C 562
4   Acura  Integra Type-R   2001   25000        Autoshow  COMMON  C 596

In [59]:
df_lite["Owned"] = pd.Series(dtype="string")
df_lite.head()

    Brand          Vehicle  Year   Value      Collection  Rarity     PI Owned
0  Abarth    595 esseesse   1968   35000        Autoshow  COMMON  D 100  <NA>
1  Abarth        Fiat 131   1980  250000  "Hard to Find"  COMMON  C 510  <NA>
2  Abarth     695 Biposto   2016  250000  "Hard to Find"  COMMON  B 657  <NA>
3  Abarth      124 Spider   2017  250000  "Hard to Find"  COMMON  C 562  <NA>
4   Acura  Integra Type-R   2001   25000        Autoshow  COMMON  C 596  <NA>

### Convert dataframe to csv

In [60]:
df_lite.to_csv("FH5/FH5-0-masterlist.csv", index=False, encoding="utf-8-sig")