In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("FH5/FH5-0-owned.csv", encoding="cp1252")
df.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,NaN
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,1
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,1
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,NaN
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,NaN

In [3]:
df.dtypes

Brand           str
Vehicle         str
Year          int64
 Value          str
Collection      str
Rarity          str
PI              str
Owned           str
dtype: object

In [4]:
df["Year"] = df["Year"].astype(str)
df.dtypes

Brand         str
Vehicle       str
Year          str
 Value        str
Collection    str
Rarity        str
PI            str
Owned         str
dtype: object

In [5]:
df["Owned"] = df["Owned"].fillna("1")
df.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,1
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,1
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,1
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,1
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,1

In [6]:
df["Owned"].value_counts()

Owned
1    758
0     94
-     50
Name: count, dtype: int64

In [7]:
df = df.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df = df.reset_index(drop=True)
df.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,1
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,1
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,1
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,1
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,1

In [8]:
df_notowned = df.iloc[df["Owned"].str.contains("0")]
df_notowned.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
8,Alfa Romeo,Giulia TZ2,1965,"4,000,000",Autoshow,LEGENDARY,B 641,0
9,Alfa Romeo,33 Stradale,1968,"15,000,000",Autoshow,LEGENDARY,A 707,0
28,Aston Martin,DBR1,1958,"22,500,000",Autoshow,LEGENDARY,B 678,0
71,Auto Union,Type D,1939,"15,000,000","Autoshow, ""Fairy Tale Ending"" accolade",LEGENDARY,B 675,0
76,Bentley,Blower 4-1/2 Litre Supercharged,1931,"4,000,000","Autoshow, Wheelspin",LEGENDARY,D 207,0

In [9]:
df_notowned_htf = df_notowned[df_notowned["Collection"].str.contains("Hard to Find")]
df_notowned_htf.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
212,Extreme E,#125 ABT Cupra XE,2022,"700,000","""Hard to Find""",RARE,A 748,0
213,Extreme E,#22 JBXE,2022,"700,000","""Hard to Find""",RARE,A 748,0
214,Extreme E,#23 Genesys Andretti United,2022,"700,000","""Hard to Find""",RARE,A 748,0
216,Extreme E,#44 X44,2022,"700,000","""Hard to Find""",RARE,A 748,0
218,Extreme E,#55 ACCIONA | Sainz XE Team,2022,"700,000","""Hard to Find""",RARE,A 748,0

In [10]:
df_save = df_notowned_htf.copy()

In [11]:
df_save["Vehicle"] = df_notowned_htf["Brand"] + " " + df_notowned_htf["Vehicle"] + "(" + df_notowned_htf["Year"] + ")"
df_save.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
212,Extreme E,Extreme E #125 ABT Cupra XE (2022),2022,"700,000","""Hard to Find""",RARE,A 748,0
213,Extreme E,Extreme E #22 JBXE (2022),2022,"700,000","""Hard to Find""",RARE,A 748,0
214,Extreme E,Extreme E #23 Genesys Andretti United (2022),2022,"700,000","""Hard to Find""",RARE,A 748,0
216,Extreme E,Extreme E #44 X44 (2022),2022,"700,000","""Hard to Find""",RARE,A 748,0
218,Extreme E,Extreme E #55 ACCIONA | Sainz XE Team (2022),2022,"700,000","""Hard to Find""",RARE,A 748,0

In [12]:
columns_to_drop = [0, 2]
df_save = df_save.drop(df_save.columns[columns_to_drop], axis=1)
df_save.head()

,Vehicle,Value,Collection,Rarity,PI,Owned
212,Extreme E #125 ABT Cupra XE (2022),"700,000","""Hard to Find""",RARE,A 748,0
213,Extreme E #22 JBXE (2022),"700,000","""Hard to Find""",RARE,A 748,0
214,Extreme E #23 Genesys Andretti United (2022),"700,000","""Hard to Find""",RARE,A 748,0
216,Extreme E #44 X44 (2022),"700,000","""Hard to Find""",RARE,A 748,0
218,Extreme E #55 ACCIONA | Sainz XE Team (2022),"700,000","""Hard to Find""",RARE,A 748,0

In [13]:
df_nonautoshow = df_notowned[~df_notowned["Collection"].str.contains("Autoshow")]
df_nonautoshow["Vehicle"] = df_nonautoshow["Year"] + " " + df_nonautoshow["Brand"] + " " + df_nonautoshow["Vehicle"]
df_nonautoshow = df_nonautoshow.drop(df_nonautoshow.columns[columns_to_drop], axis=1)
df_nonautoshow.head()

,Vehicle,Value,Collection,Rarity,PI,Owned
212,2022 Extreme E #125 ABT Cupra XE,"700,000","""Hard to Find""",RARE,A 748,0
213,2022 Extreme E #22 JBXE,"700,000","""Hard to Find""",RARE,A 748,0
214,2022 Extreme E #23 Genesys Andretti United,"700,000","""Hard to Find""",RARE,A 748,0
216,2022 Extreme E #44 X44,"700,000","""Hard to Find""",RARE,A 748,0
218,2022 Extreme E #55 ACCIONA | Sainz XE Team,"700,000","""Hard to Find""",RARE,A 748,0

In [14]:
df_save.to_csv("FH5/FH5-missingHtF.csv", index=False, encoding="utf-8-sig")
df_nonautoshow.to_csv("FH5/FH5-nonautoshow.csv", index=False, encoding="utf-8-sig")