In [1]:
import pandas as pd

# Import FH5 car list extended

In [2]:
filename = "Forza Horizon 5 Car List"
tables = pd.read_html("raw-website/" + filename + ".htm")
df = tables[0]
df.head(10)

,Car Model,Car Type,Collect,Added,Nickname,ID
0,2017 Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740
1,2016 Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489
2,1980 Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124
3,1968 Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017
4,2017 Acura NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352
5,2002 Acura RSX Type-S,Retro Hot Hatch,Autoshow,Launch,Acura RSX,422
6,2001 Acura Integra Type-R,Retro Hot Hatch,Autoshow,Launch,Acura Integra,368
7,2017 Alfa Romeo Giulia Quadrifoglio,Super Saloons,Autoshow,Series 24,Alfa Giulia '17,2542
8,2014 Alfa Romeo 4C,Modern Sports Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 4C,2038
9,2007 Alfa Romeo 8C Competizione,GT Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 8C,1032

## Check stats

In [3]:
df.dtypes

Car Model      str
Car Type       str
Collect        str
Added          str
Nickname       str
ID           int64
dtype: object

In [4]:
df["Nickname"].value_counts()

Nickname
Honda S2000        2
Porsche Cayman     2
Abarth 124 '17     1
Abarth 695 '16     1
Abarth 131         1
                  ..
Wuling Mini EV     1
Wuling Sunshine    1
Xpeng P7           1
Zenvo TSR-S        1
Zenvo ST1          1
Name: count, Length: 900, dtype: int64

In [5]:
df_filter = df[(df["Nickname"].str.contains("Honda S2000"))|(df["Nickname"].str.contains("Porsche Cayman"))]
df_filter.head()

,Car Model,Car Type,Collect,Added,Nickname,ID
394,2009 Honda S2000 CR,Modern Sports Cars,"Autoshow, Wheelspin",Launch,Honda S2000,2005
399,2003 Honda S2000,Modern Sports Cars,"Autoshow, Wheelspin",Launch,Honda S2000,427
753,2016 Porsche Cayman GT4,Track Toys,"Autoshow, Wheelspin",Launch,Porsche Cayman,2529
754,2015 Porsche Cayman GTS,Modern Sports Cars,"Autoshow, Wheelspin",Launch,Porsche Cayman,2293

In [6]:
df["ID"].value_counts()

ID
1426    2
2740    1
2489    1
1124    1
2017    1
       ..
3789    1
3548    1
3547    1
3212    1
2474    1
Name: count, Length: 901, dtype: int64

In [7]:
df_filter = df[(df["ID"]==1451)|(df["ID"]==2181)|(df["ID"]==1328)|(df["ID"]==1387)|(df["ID"]==1253)]
df_filter = df_filter.sort_values("ID")
display(df_filter)

,Car Model,Car Type,Collect,Added,Nickname,ID
698,2010 Noble M600,Modern Supercars,"Backstage, Seasonal",Series 5,Noble M600,1253
122,2011 Bugatti Veyron Super Sport,Hypercars,Autoshow,Launch,Bugatti Veyron,1328
892,1997 Volvo 850 R,Retro Saloons,"Autoshow, Wheelspin",Launch,Volvo 850,1387
27,2012 Ascari KZ1R,Modern Supercars,"Backstage, Seasonal",Series 6,Ascari KZ1R,1451
38,2013 Aston Martin V12 Vantage S,Super GT,"Autoshow, Wheelspin",Launch,Vantage S '13,2181

## Split Year from Car Model

In [8]:
df[["Year", "Car Model"]] = df["Car Model"].str.extract(r'^(\d{4})(.*)$')
df["Car Model"] = df["Car Model"].str.strip()
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
0,Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017
1,Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016
2,Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980
3,Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968
4,Acura NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,2017

In [9]:
df.loc[df["Nickname"]=="Pagani Zonda C", "Year"] = "2010"
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
0,Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017
1,Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016
2,Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980
3,Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968
4,Acura NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,2017

In [10]:
df.dtypes

Car Model      str
Car Type       str
Collect        str
Added          str
Nickname       str
ID           int64
Year           str
dtype: object

## Split Brand from Car Model

### Isolate rows for 2-word vehicle brand names

In [11]:
df1 = df.iloc[df["Car Model"].str.contains("Alfa|Aston|Auto Union|Automobili Pininfarina|Extreme E|Formula Drift|Forsberg Racing|Funco Motorsports|Land Rover|Local Motors|RJ Anderson|SIERRA Cars|Spania GTA|Universal Studios|W Motors")]
df1.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
7,Alfa Romeo Giulia Quadrifoglio,Super Saloons,Autoshow,Series 24,Alfa Giulia '17,2542,2017
8,Alfa Romeo 4C,Modern Sports Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 4C,2038,2014
9,Alfa Romeo 8C Competizione,GT Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 8C,1032,2007
10,Alfa Romeo 155 Q4,Retro Saloons,"Backstage, Seasonal",Series 24,Alfa Romeo 155,1393,1992
11,Alfa Romeo 33 Stradale,Classic Racers,Autoshow,Series 24,Alfa Romeo 33S,1549,1968

#### Replace first whitespace with underscore

In [12]:
df1["Car Model"] = df1["Car Model"].str.replace(" ", "_", n=1)
df1.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
7,Alfa_Romeo Giulia Quadrifoglio,Super Saloons,Autoshow,Series 24,Alfa Giulia '17,2542,2017
8,Alfa_Romeo 4C,Modern Sports Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 4C,2038,2014
9,Alfa_Romeo 8C Competizione,GT Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 8C,1032,2007
10,Alfa_Romeo 155 Q4,Retro Saloons,"Backstage, Seasonal",Series 24,Alfa Romeo 155,1393,1992
11,Alfa_Romeo 33 Stradale,Classic Racers,Autoshow,Series 24,Alfa Romeo 33S,1549,1968

### Separate filtering for Hot Wheels

In [13]:
df_hw = df.iloc[df["Car Model"].str.contains("Hot Wheels")]
df_hw = df_hw.loc[~df_hw["Car Model"].str.contains("Brabham|Chevrolet|Hennessey|Mosler|SUBARU|Schuppan|SIERRA")]
df_hw.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
420,Hot Wheels 2JetZ,Rods and Customs,"Backstage, Wheelspin, Seasonal",Series 9,2JetZ,3405,2018
421,Hot Wheels Baja Bone Shaker,Unlimited Offroad,Autoshow DLC,Hot Wheels Expansion,Baja Bone Shaker,3702,2013
422,Hot Wheels Bad to the Blade,Extreme Track Toys,Autoshow DLC,Hot Wheels Expansion,Hot Wheels BTTB,3704,2012
423,Hot Wheels Rip Rod,Unlimited Buggies,"Backstage, Wheelspin, Seasonal",Series 9,Rip Rod,2751,2012
424,Hot Wheels Bone Shaker,Rods and Customs,Autoshow,Launch,Bone Shaker,2575,2011

In [14]:
df_hw["Car Model"] = df_hw["Car Model"].str.replace(" ", "_", n=1)
df_hw.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
420,Hot_Wheels 2JetZ,Rods and Customs,"Backstage, Wheelspin, Seasonal",Series 9,2JetZ,3405,2018
421,Hot_Wheels Baja Bone Shaker,Unlimited Offroad,Autoshow DLC,Hot Wheels Expansion,Baja Bone Shaker,3702,2013
422,Hot_Wheels Bad to the Blade,Extreme Track Toys,Autoshow DLC,Hot Wheels Expansion,Hot Wheels BTTB,3704,2012
423,Hot_Wheels Rip Rod,Unlimited Buggies,"Backstage, Wheelspin, Seasonal",Series 9,Rip Rod,2751,2012
424,Hot_Wheels Bone Shaker,Rods and Customs,Autoshow,Launch,Bone Shaker,2575,2011

### Isolate rows for 3-word vehicle brand names

In [15]:
df2 = df.iloc[df["Car Model"].str.contains("AMG Transport|Casey Currie|Fast and Furious|Gordon Murray|Lynk & Co")]
df2.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
22,AMG Transport Dynamics M12S Warthog CST,Unlimited Offroad,"Autoshow, Wheelspin",Launch,M12S Warthog CST,2574,2554
135,Casey Currie Motorsports #4402 Ultra 4 'Trophy...,Unlimited Offroad,Autoshow DLC,Rally Adventure Expansion,#4402 Ultra 4,3603,2019
222,Fast and Furious Dodge Charger SRT Hellcat Red...,Modern Muscle,Autoshow DLC,Fast X Car Pack,FAF Hellcat,3836,2022
223,Fast and Furious Flip Car 2.0 'Fast X',Track Toys,Autoshow DLC,Fast X Car Pack,FAF Flip Car,3838,2022
224,Fast and Furious Datsun 240Z 'Fast X',Classic Sports Cars,Autoshow DLC,Fast X Car Pack,FAF 240Z,3832,1973

#### Replace first two whitespace with underscore

In [16]:
df2["Car Model"] = df2["Car Model"].str.replace(" ", "_", n=2)
df2.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
22,AMG_Transport_Dynamics M12S Warthog CST,Unlimited Offroad,"Autoshow, Wheelspin",Launch,M12S Warthog CST,2574,2554
135,Casey_Currie_Motorsports #4402 Ultra 4 'Trophy...,Unlimited Offroad,Autoshow DLC,Rally Adventure Expansion,#4402 Ultra 4,3603,2019
222,Fast_and_Furious Dodge Charger SRT Hellcat Red...,Modern Muscle,Autoshow DLC,Fast X Car Pack,FAF Hellcat,3836,2022
223,Fast_and_Furious Flip Car 2.0 'Fast X',Track Toys,Autoshow DLC,Fast X Car Pack,FAF Flip Car,3838,2022
224,Fast_and_Furious Datsun 240Z 'Fast X',Classic Sports Cars,Autoshow DLC,Fast X Car Pack,FAF 240Z,3832,1973

### Update df_lite with altered rows

In [17]:
df.update(df1)
df.update(df2)
df.update(df_hw)
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
0,Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017
1,Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016
2,Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980
3,Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968
4,Acura NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,2017

### Perform split

In [18]:
df[["Brand", "Car Model"]] = df["Car Model"].str.split(" ", n=1, expand=True)
#df = df.iloc[:, [4, 0, 1, 2, 3]]
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year,Brand
0,124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017,Abarth
1,695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016,Abarth
2,Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980,Abarth
3,595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968,Abarth
4,NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,2017,Acura

#### Error checking

In [19]:
df_verify = df.iloc[df["Car Model"].str.contains("_")]
df_verify.head()

Empty DataFrame
Columns: [Car Model, Car Type, Collect, Added, Nickname, ID, Year, Brand]
Index: []

#### Replace underscores in Brand column with whitespace

In [20]:
df["Brand"] = df["Brand"].str.replace("_", " ")
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year,Brand
0,124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017,Abarth
1,695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016,Abarth
2,Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980,Abarth
3,595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968,Abarth
4,NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,2017,Acura

## Sort by Brand then Year and Vehicle (ascending)

In [21]:
df["Year"] = df["Year"].str.strip()
df = df.sort_values(["Brand", "Year", "Car Model"], ascending=[True, True, True], key=lambda col: col.str.lower())
df = df.reset_index(drop=True)
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year,Brand
0,595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968,Abarth
1,Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980,Abarth
2,695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016,Abarth
3,124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017,Abarth
4,Integra Type-R,Retro Hot Hatch,Autoshow,Launch,Acura Integra,368,2001,Acura

## Merge columns

In [22]:
df["Car Model"] = df["Year"] + " " + df["Brand"] + " " + df["Car Model"]
df = df.drop(["Year", "Brand"], axis=1)
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID
0,1968 Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017
1,1980 Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124
2,2016 Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489
3,2017 Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740
4,2001 Acura Integra Type-R,Retro Hot Hatch,Autoshow,Launch,Acura Integra,368

# Read FH5 user data

In [23]:
df_owned = pd.read_csv("FH5/FH5-0-owned.csv", encoding="cp1252")
df_owned.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,NaN
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,1
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,1
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,NaN
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,NaN

In [24]:
df_owned.dtypes

Brand           str
Vehicle         str
Year          int64
 Value          str
Collection      str
Rarity          str
PI              str
Owned           str
dtype: object

## Merge and remove redundant columns

In [25]:
df_owned["Year"] = df_owned["Year"].astype(str)
df_owned = df_owned.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df_owned = df_owned.reset_index(drop=True)

df_owned["Car Model"] = df_owned["Year"] + " " + df_owned["Brand"] + " " + df_owned["Vehicle"]
columns_to_drop = ["Brand", "Vehicle", "Year"]
df_owned = df_owned.drop(["Brand", "Vehicle", "Year"], axis=1)
df_owned = df_owned.iloc[:, [5, 0, 1, 2, 3, 4]]

df_owned["Owned"] = df_owned["Owned"].fillna("1")
df_owned.head()

                    Car Model     Value       Collection  Rarity     PI Owned
0   1968 Abarth 595 esseesse     35,000         Autoshow  COMMON  D 100     1
1       1980 Abarth Fiat 131    250,000   "Hard to Find"  COMMON  C 510     1
2    2016 Abarth 695 Biposto    250,000   "Hard to Find"  COMMON  B 657     1
3     2017 Abarth 124 Spider    250,000   "Hard to Find"  COMMON  C 562     1
4  2001 Acura Integra Type-R     25,000         Autoshow  COMMON  C 596     1

In [26]:
df_owned["Owned"].value_counts()

Owned
1    758
0     94
-     50
Name: count, dtype: int64

In [27]:
df["Number"] = df.index + 1
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number
0,1968 Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1
1,1980 Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,2
2,2016 Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,3
3,2017 Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,4
4,2001 Acura Integra Type-R,Retro Hot Hatch,Autoshow,Launch,Acura Integra,368,5

In [28]:
df_owned["Number"] = df_owned.index + 1
df_owned.head()

,Car Model,Value,Collection,Rarity,PI,Owned,Number
0,1968 Abarth 595 esseesse,"35,000",Autoshow,COMMON,D 100,1,1
1,1980 Abarth Fiat 131,"250,000","""Hard to Find""",COMMON,C 510,1,2
2,2016 Abarth 695 Biposto,"250,000","""Hard to Find""",COMMON,B 657,1,3
3,2017 Abarth 124 Spider,"250,000","""Hard to Find""",COMMON,C 562,1,4
4,2001 Acura Integra Type-R,"25,000",Autoshow,COMMON,C 596,1,5

In [29]:
df["Car Model"] = df["Car Model"].str.strip()
df_owned["Car Model"] = df_owned["Car Model"].str.strip()
df_master = pd.merge(df, df_owned, on="Car Model", how="outer")
df_master.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number_x,Value,Collection,Rarity,PI,Owned,Number_y
0,1926 Bugatti Type 35 C,Vintage Racers,"Autoshow, Wheelspin",Launch,Bugatti T35 C,2066.0,121.0,"1,300,000","Autoshow, Wheelspin",LEGENDARY,D 285,1,121.0
1,1929 Mercedes-Benz SSK,Rare Classics,"Autoshow, Wheelspin",Launch,M-B SSK,3026.0,596.0,"7,500,000","Autoshow, Wheelspin",LEGENDARY,D 256,1,596.0
2,1930 Bentley 8 Litre,Rare Classics,"Autoshow, Wheelspin",Launch,4-1/2 Liter '31,1372.0,76.0,"1,500,000","Autoshow, Wheelspin",LEGENDARY,D 181,1,76.0
3,1930 Bentley Blower 4-1/2 Litre Supercharged,Vintage Racers,"Autoshow, Wheelspin",Launch,Bentley 8 Litre,2976.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1931 Bentley Blower 4-1/2 Litre Supercharged,NaN,NaN,NaN,NaN,NaN,NaN,"4,000,000","Autoshow, Wheelspin",LEGENDARY,D 207,0,77.0

In [30]:
df_master.dtypes

Car Model         str
Car Type          str
Collect           str
Added             str
Nickname          str
ID            float64
Number_x      float64
 Value            str
Collection        str
Rarity            str
PI                str
Owned             str
Number_y      float64
dtype: object

In [31]:
df_master["Number_x"] = df_master["Number_x"].fillna(df_master["Number_y"])
df_master["Number_y"] = df_master["Number_y"].fillna(df_master["Number_x"])

In [32]:
#df_master["ID"].astype(int)
df_master["Number_x"] = df_master["Number_x"].astype(int)
df_master["Number_y"] = df_master["Number_y"].astype(int)
df_master = df_master.iloc[:, [6, 12, 0, 1, 2, 8, 3, 4, 5, 7, 9, 10, 11]]
df_master = df_master.sort_values("Number_x")
df_master.head()

,Number_x,Number_y,Car Model,Car Type,Collect,Collection,Added,Nickname,ID,Value,Rarity,PI,Owned
94,1,1,1968 Abarth 595 esseesse,Cult Cars,Autoshow,Autoshow,Series 24,Abarth 595 '68,2017.0,"35,000",COMMON,D 100,1
190,2,2,1980 Abarth Fiat 131,Classic Rally,"Backstage, Seasonal","""Hard to Find""",Series 24,Abarth 131,1124.0,"250,000",COMMON,C 510,1
623,3,3,2016 Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal","""Hard to Find""",Series 24,Abarth 695 '16,2489.0,"250,000",COMMON,B 657,1
665,4,4,2017 Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal","""Hard to Find""",Series 24,Abarth 124 '17,2740.0,"250,000",COMMON,C 562,1
370,5,5,2001 Acura Integra Type-R,Retro Hot Hatch,Autoshow,Autoshow,Launch,Acura Integra,368.0,"25,000",COMMON,C 596,1

In [33]:
df_verify = df_master.iloc[~(df_master["Number_x"]==df_master["Number_y"])]
df_verify.head()

,Number_x,Number_y,Car Model,Car Type,Collect,Collection,Added,Nickname,ID,Value,Rarity,PI,Owned
824,339,340,2020 Ford #2069 Ford Performance Bronco R,Offroad,"Autoshow, Wheelspin","Autoshow, Wheelspin",Launch,Bronco R,3404.0,"250,000",EPIC,C 544,1

In [34]:
df_notowned_htf = df_master.iloc[(df_master["Collection"].str.contains("Hard to Find")) & (df_master["Owned"]=="0")]
df_notowned_htf.head()

,Number_x,Number_y,Car Model,Car Type,Collect,Collection,Added,Nickname,ID,Value,Rarity,PI,Owned
910,213,213,2022 Extreme E #125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#125 Extreme E,3708.0,"700,000",RARE,A 748,0
911,214,214,2022 Extreme E #22 JBXE,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#22 Extreme E,3709.0,"700,000",RARE,A 748,0
912,215,215,2022 Extreme E #23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#23 Extreme E,3710.0,"700,000",RARE,A 748,0
914,217,217,2022 Extreme E #44 X44,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#44 Extreme E,3712.0,"700,000",RARE,A 748,0
917,219,219,2022 Extreme E #55 ACCIONA | Sainz XE Team,NaN,NaN,"""Hard to Find""",NaN,NaN,NaN,"700,000",RARE,A 748,0

In [35]:
df_notowned_htf1 = df_master.iloc[(df_master["Collect"].str.contains("Backstage")) & (df_master["Owned"]=="0")]
df_notowned_htf1.head()

,Number_x,Number_y,Car Model,Car Type,Collect,Collection,Added,Nickname,ID,Value,Rarity,PI,Owned
910,213,213,2022 Extreme E #125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#125 Extreme E,3708.0,"700,000",RARE,A 748,0
911,214,214,2022 Extreme E #22 JBXE,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#22 Extreme E,3709.0,"700,000",RARE,A 748,0
912,215,215,2022 Extreme E #23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#23 Extreme E,3710.0,"700,000",RARE,A 748,0
914,217,217,2022 Extreme E #44 X44,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#44 Extreme E,3712.0,"700,000",RARE,A 748,0
273,239,239,1992 Ferrari 512 TR,Retro Supercars,"Backstage, Seasonal","""Hard to Find""",Series 7,Ferrari 512TR,255.0,"270,000",EPIC,A 733,0

In [36]:
df_not_owned_htf_master = pd.merge(df_notowned_htf, df_notowned_htf1, how="outer")
df_not_owned_htf_master.head()

,Number_x,Number_y,Car Model,Car Type,Collect,Collection,Added,Nickname,ID,Value,Rarity,PI,Owned
0,213,213,2022 Extreme E #125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#125 Extreme E,3708.0,"700,000",RARE,A 748,0
1,214,214,2022 Extreme E #22 JBXE,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#22 Extreme E,3709.0,"700,000",RARE,A 748,0
2,215,215,2022 Extreme E #23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#23 Extreme E,3710.0,"700,000",RARE,A 748,0
3,217,217,2022 Extreme E #44 X44,Unlimited Offroad,"Backstage, Seasonal","""Hard to Find""",Series 10,#44 Extreme E,3712.0,"700,000",RARE,A 748,0
4,219,219,2022 Extreme E #55 ACCIONA | Sainz XE Team,NaN,NaN,"""Hard to Find""",NaN,NaN,NaN,"700,000",RARE,A 748,0

In [37]:
df_verify = df_not_owned_htf_master.iloc[~(df_not_owned_htf_master["Number_x"]==df_not_owned_htf_master["Number_y"])]
df_verify.head()

Empty DataFrame
Columns: [Number_x, Number_y, Car Model, Car Type, Collect, Collection, Added, Nickname, ID,  Value , Rarity, PI, Owned]
Index: []

# Apply user data to extended list

In [38]:
df_ext = df.copy()
df_ext.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number
0,1968 Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1
1,1980 Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,2
2,2016 Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,3
3,2017 Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,4
4,2001 Acura Integra Type-R,Retro Hot Hatch,Autoshow,Launch,Acura Integra,368,5

In [39]:
df_owned.head()

,Car Model,Value,Collection,Rarity,PI,Owned,Number
0,1968 Abarth 595 esseesse,"35,000",Autoshow,COMMON,D 100,1,1
1,1980 Abarth Fiat 131,"250,000","""Hard to Find""",COMMON,C 510,1,2
2,2016 Abarth 695 Biposto,"250,000","""Hard to Find""",COMMON,B 657,1,3
3,2017 Abarth 124 Spider,"250,000","""Hard to Find""",COMMON,C 562,1,4
4,2001 Acura Integra Type-R,"25,000",Autoshow,COMMON,C 596,1,5

In [40]:
df_ext["Owned"] = df_owned["Owned"]
df_ext.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number,Owned
0,1968 Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1,1
1,1980 Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,2,1
2,2016 Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,3,1
3,2017 Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,4,1
4,2001 Acura Integra Type-R,Retro Hot Hatch,Autoshow,Launch,Acura Integra,368,5,1

In [41]:
df_ext["Owned"].value_counts()

Owned
1    758
0     94
-     50
Name: count, dtype: int64

In [42]:
df_ext_missing = df_ext.loc[(df_ext["Owned"]=="0") & (~df_ext["Collect"].str.contains("Autoshow"))]
df_ext_missing = df_ext_missing.reset_index(drop=True)
df_ext_missing.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number,Owned
0,2022 Extreme E #125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#125 Extreme E,3708,213,0
1,2022 Extreme E #22 JBXE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#22 Extreme E,3709,214,0
2,2022 Extreme E #23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal",Series 10,#23 Extreme E,3710,215,0
3,2022 Extreme E #44 X44,Unlimited Offroad,"Backstage, Seasonal",Series 10,#44 Extreme E,3712,217,0
4,2022 Extreme E #55 ACCIONA / Sainz XE Team,Unlimited Offroad,"Backstage, Seasonal",Series 10,#55 Extreme E,3714,219,0

# Merge different sources for missing non-autoshow cars

In [43]:
df_missing = pd.read_csv("FH5/FH5-nonautoshow.csv", encoding="utf-8")
df_missing.rename(columns={ df_missing.columns[0]: "Car Model" }, inplace=True)
df_missing.head()

,Car Model,Value,Collection,Rarity,PI,Owned
0,2022 Extreme E #125 ABT Cupra XE,"700,000","""Hard to Find""",RARE,A 748,0
1,2022 Extreme E #22 JBXE,"700,000","""Hard to Find""",RARE,A 748,0
2,2022 Extreme E #23 Genesys Andretti United,"700,000","""Hard to Find""",RARE,A 748,0
3,2022 Extreme E #44 X44,"700,000","""Hard to Find""",RARE,A 748,0
4,2022 Extreme E #55 ACCIONA | Sainz XE Team,"700,000","""Hard to Find""",RARE,A 748,0

In [44]:
df_missing["Car Model"] = df_ext_missing["Car Model"]
df_missing.head()

,Car Model,Value,Collection,Rarity,PI,Owned
0,2022 Extreme E #125 ABT Cupra XE,"700,000","""Hard to Find""",RARE,A 748,0
1,2022 Extreme E #22 JBXE,"700,000","""Hard to Find""",RARE,A 748,0
2,2022 Extreme E #23 Genesys Andretti United,"700,000","""Hard to Find""",RARE,A 748,0
3,2022 Extreme E #44 X44,"700,000","""Hard to Find""",RARE,A 748,0
4,2022 Extreme E #55 ACCIONA / Sainz XE Team,"700,000","""Hard to Find""",RARE,A 748,0

In [45]:
#df_missing["Car Model"] = df_missing["Car Model"].str.strip()
df_missing_master = pd.merge(df_ext_missing, df_missing, on="Car Model", how="outer")
df_missing_master = df_missing_master.sort_values("Number")
df_missing_master.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number,Owned_x,Value,Collection,Rarity,PI,Owned_y
49,2022 Extreme E #125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#125 Extreme E,3708,213,0,"700,000","""Hard to Find""",RARE,A 748,0
50,2022 Extreme E #22 JBXE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#22 Extreme E,3709,214,0,"700,000","""Hard to Find""",RARE,A 748,0
51,2022 Extreme E #23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal",Series 10,#23 Extreme E,3710,215,0,"700,000","""Hard to Find""",RARE,A 748,0
52,2022 Extreme E #44 X44,Unlimited Offroad,"Backstage, Seasonal",Series 10,#44 Extreme E,3712,217,0,"700,000","""Hard to Find""",RARE,A 748,0
53,2022 Extreme E #55 ACCIONA / Sainz XE Team,Unlimited Offroad,"Backstage, Seasonal",Series 10,#55 Extreme E,3714,219,0,"700,000","""Hard to Find""",RARE,A 748,0

In [46]:
df_missing_master[["Year", "Car Model"]] = df_missing_master["Car Model"].str.extract(r'^(\d{4})(.*)$')
df_missing_master["Car Model"] = df_missing_master["Car Model"].str.strip()
df_missing_master.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number,Owned_x,Value,Collection,Rarity,PI,Owned_y,Year
49,Extreme E #125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#125 Extreme E,3708,213,0,"700,000","""Hard to Find""",RARE,A 748,0,2022
50,Extreme E #22 JBXE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#22 Extreme E,3709,214,0,"700,000","""Hard to Find""",RARE,A 748,0,2022
51,Extreme E #23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal",Series 10,#23 Extreme E,3710,215,0,"700,000","""Hard to Find""",RARE,A 748,0,2022
52,Extreme E #44 X44,Unlimited Offroad,"Backstage, Seasonal",Series 10,#44 Extreme E,3712,217,0,"700,000","""Hard to Find""",RARE,A 748,0,2022
53,Extreme E #55 ACCIONA / Sainz XE Team,Unlimited Offroad,"Backstage, Seasonal",Series 10,#55 Extreme E,3714,219,0,"700,000","""Hard to Find""",RARE,A 748,0,2022

## Split Brand from Car Model

In [47]:
df1 = df_missing_master.iloc[df_missing_master["Car Model"].str.contains("Alfa|Aston|Auto Union|Automobili Pininfarina|Extreme E|Formula Drift|Forsberg Racing|Funco Motorsports|Land Rover|Local Motors|RJ Anderson|SIERRA Cars|Spania GTA|Universal Studios|W Motors")]
df1["Car Model"] = df1["Car Model"].str.replace(" ", "_", n=1)
df_hw = df_missing_master.iloc[df_missing_master["Car Model"].str.contains("Hot Wheels")]
df_hw = df_hw.loc[~df_hw["Car Model"].str.contains("Brabham|Chevrolet|Hennessey|Mosler|SUBARU|Schuppan|SIERRA")]
df_hw["Car Model"] = df_hw["Car Model"].str.replace(" ", "_", n=1)
df2 = df_missing_master.iloc[df_missing_master["Car Model"].str.contains("AMG Transport|Casey Currie|Fast and Furious|Gordon Murray|Lynk & Co")]
df2["Car Model"] = df2["Car Model"].str.replace(" ", "_", n=2)
df_missing_master.update(df1)
df_missing_master.update(df2)
df_missing_master.update(df_hw)
df_missing_master.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number,Owned_x,Value,Collection,Rarity,PI,Owned_y,Year
49,Extreme_E #125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#125 Extreme E,3708,213,0,"700,000","""Hard to Find""",RARE,A 748,0,2022
50,Extreme_E #22 JBXE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#22 Extreme E,3709,214,0,"700,000","""Hard to Find""",RARE,A 748,0,2022
51,Extreme_E #23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal",Series 10,#23 Extreme E,3710,215,0,"700,000","""Hard to Find""",RARE,A 748,0,2022
52,Extreme_E #44 X44,Unlimited Offroad,"Backstage, Seasonal",Series 10,#44 Extreme E,3712,217,0,"700,000","""Hard to Find""",RARE,A 748,0,2022
53,Extreme_E #55 ACCIONA / Sainz XE Team,Unlimited Offroad,"Backstage, Seasonal",Series 10,#55 Extreme E,3714,219,0,"700,000","""Hard to Find""",RARE,A 748,0,2022

In [48]:
df_missing_master[["Brand", "Car Model"]] = df_missing_master["Car Model"].str.split(" ", n=1, expand=True)
df_missing_master["Brand"] = df_missing_master["Brand"].str.replace("_", " ")
df_missing_master.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number,Owned_x,Value,Collection,Rarity,PI,Owned_y,Year,Brand
49,#125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#125 Extreme E,3708,213,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
50,#22 JBXE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#22 Extreme E,3709,214,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
51,#23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal",Series 10,#23 Extreme E,3710,215,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
52,#44 X44,Unlimited Offroad,"Backstage, Seasonal",Series 10,#44 Extreme E,3712,217,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
53,#55 ACCIONA / Sainz XE Team,Unlimited Offroad,"Backstage, Seasonal",Series 10,#55 Extreme E,3714,219,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E

In [49]:
df_missing_master.dtypes

Car Model       str
Car Type        str
Collect         str
Added           str
Nickname        str
ID            int64
Number        int64
Owned_x         str
 Value          str
Collection      str
Rarity          str
PI              str
Owned_y       int64
Year            str
Brand           str
dtype: object

In [50]:
df_missing_master = df_missing_master.sort_values(["Brand", "Nickname"], ascending=[True, True], key=lambda col: col.str.lower())
df_missing_master = df_missing_master.reset_index(drop=True)
df_missing_master.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number,Owned_x,Value,Collection,Rarity,PI,Owned_y,Year,Brand
0,#125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#125 Extreme E,3708,213,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
1,#22 JBXE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#22 Extreme E,3709,214,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
2,#23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal",Series 10,#23 Extreme E,3710,215,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
3,#44 X44,Unlimited Offroad,"Backstage, Seasonal",Series 10,#44 Extreme E,3712,217,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
4,#55 ACCIONA / Sainz XE Team,Unlimited Offroad,"Backstage, Seasonal",Series 10,#55 Extreme E,3714,219,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E

In [51]:
df_missing_alphabetical = df_missing_master.sort_values(["Brand", "Year", "Car Model"], ascending=[True, True, True], key=lambda col: col.str.lower())
df_missing_alphabetical.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number,Owned_x,Value,Collection,Rarity,PI,Owned_y,Year,Brand
0,#125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#125 Extreme E,3708,213,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
1,#22 JBXE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#22 Extreme E,3709,214,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
2,#23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal",Series 10,#23 Extreme E,3710,215,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
3,#44 X44,Unlimited Offroad,"Backstage, Seasonal",Series 10,#44 Extreme E,3712,217,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E
4,#55 ACCIONA / Sainz XE Team,Unlimited Offroad,"Backstage, Seasonal",Series 10,#55 Extreme E,3714,219,0,"700,000","""Hard to Find""",RARE,A 748,0,2022,Extreme E

In [52]:
df_missing_alphabetical["Car Model"] = df_missing_alphabetical["Year"] + " " + df_missing_alphabetical["Brand"] + " " + df_missing_alphabetical["Car Model"]
df_missing_alphabetical = df_missing_alphabetical.drop(["Year", "Brand", "Owned_x", "Number", "ID"], axis=1)
df_missing_alphabetical.head()

,Car Model,Car Type,Collect,Added,Nickname,Value,Collection,Rarity,PI,Owned_y
0,2022 Extreme E #125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#125 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0
1,2022 Extreme E #22 JBXE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#22 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0
2,2022 Extreme E #23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal",Series 10,#23 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0
3,2022 Extreme E #44 X44,Unlimited Offroad,"Backstage, Seasonal",Series 10,#44 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0
4,2022 Extreme E #55 ACCIONA / Sainz XE Team,Unlimited Offroad,"Backstage, Seasonal",Series 10,#55 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0

In [53]:
df_missing_alphabetical = df_missing_alphabetical.iloc[:, [0, 1, 3, 2, 6, 4, 5, 7, 8, 9]]
df_missing_alphabetical.rename(columns={ df_missing_alphabetical.columns[9]: "Owned" }, inplace=True)
df_missing_alphabetical.head()

,Car Model,Car Type,Added,Collect,Collection,Nickname,Value,Rarity,PI,Owned
0,2022 Extreme E #125 ABT Cupra XE,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#125 Extreme E,"700,000",RARE,A 748,0
1,2022 Extreme E #22 JBXE,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#22 Extreme E,"700,000",RARE,A 748,0
2,2022 Extreme E #23 Genesys Andretti United,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#23 Extreme E,"700,000",RARE,A 748,0
3,2022 Extreme E #44 X44,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#44 Extreme E,"700,000",RARE,A 748,0
4,2022 Extreme E #55 ACCIONA / Sainz XE Team,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#55 Extreme E,"700,000",RARE,A 748,0

In [54]:
df_missing_master["Car Model"] = df_missing_master["Year"] + " " + df_missing_master["Brand"] + " " + df_missing_master["Car Model"]
df_missing_master = df_missing_master.drop(["Year", "Brand", "Owned_x", "Number", "ID"], axis=1)
df_missing_master.head()

,Car Model,Car Type,Collect,Added,Nickname,Value,Collection,Rarity,PI,Owned_y
0,2022 Extreme E #125 ABT Cupra XE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#125 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0
1,2022 Extreme E #22 JBXE,Unlimited Offroad,"Backstage, Seasonal",Series 10,#22 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0
2,2022 Extreme E #23 Genesys Andretti United,Unlimited Offroad,"Backstage, Seasonal",Series 10,#23 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0
3,2022 Extreme E #44 X44,Unlimited Offroad,"Backstage, Seasonal",Series 10,#44 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0
4,2022 Extreme E #55 ACCIONA / Sainz XE Team,Unlimited Offroad,"Backstage, Seasonal",Series 10,#55 Extreme E,"700,000","""Hard to Find""",RARE,A 748,0

In [55]:
df_missing_master = df_missing_master.iloc[:, [0, 1, 3, 2, 6, 4, 5, 7, 8, 9]]
df_missing_master.rename(columns={ df_missing_master.columns[9]: "Owned" }, inplace=True)
df_missing_master.head()

,Car Model,Car Type,Added,Collect,Collection,Nickname,Value,Rarity,PI,Owned
0,2022 Extreme E #125 ABT Cupra XE,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#125 Extreme E,"700,000",RARE,A 748,0
1,2022 Extreme E #22 JBXE,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#22 Extreme E,"700,000",RARE,A 748,0
2,2022 Extreme E #23 Genesys Andretti United,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#23 Extreme E,"700,000",RARE,A 748,0
3,2022 Extreme E #44 X44,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#44 Extreme E,"700,000",RARE,A 748,0
4,2022 Extreme E #55 ACCIONA / Sainz XE Team,Unlimited Offroad,Series 10,"Backstage, Seasonal","""Hard to Find""",#55 Extreme E,"700,000",RARE,A 748,0

In [56]:
df_missing_series = df_missing_master.sort_values("Added")
df_missing_series["Added2"] = df_missing_series["Added"].str.extract(r"(\d+)")
df_missing_series["Added2"] = df_missing_series["Added2"].fillna("0")
#df_missing_series = df_missing_series.sort_values(["Added", "Added2"], ascending=[True, True], key=lambda col: col.str.lower())
#df_missing_series.head()

In [57]:
df_missing_series.dtypes

Car Model       str
Car Type        str
Added           str
Collect         str
Collection      str
Nickname        str
 Value          str
Rarity          str
PI              str
Owned         int64
Added2          str
dtype: object

In [58]:
df_missing_series["Added2"] = df_missing_series["Added2"].astype("Int64")
df_missing_series = df_missing_series.sort_values("Added2")
df_missing_series = df_missing_series.drop(columns="Added2")
df_missing_series.head()

,Car Model,Car Type,Added,Collect,Collection,Nickname,Value,Rarity,PI,Owned
29,2023 Lamborghini Huracán Sterrato,Rally Monsters,Horizon Realms,Accolade,"""Master of Worlds"" accolade",Huracán Sterrato,"250,000",LEGENDARY,S1 836,0
21,1984 Honda Civic CRX Mugen,Retro Hot Hatch,Launch,"Backstage, Seasonal",Midnight Battle 2,Honda Civic '84,"40,000",EPIC,D 499,0
55,1998 SUBARU Impreza 22B-STi Version,Retro Rally,Launch,"Backstage, Wheelspin, Seasonal",Wheelspin,Subaru 22B,"110,000",LEGENDARY,B 640,0
63,1963 Volkswagen Beetle Forza Edition,Track Toys,Launch,Accolade,"""Flexibility Beats Everything"" accolade",Beetle '63 FE,"500,000",FORZA EDITION,S1 900,0
8,2010 Ferrari 599 GTO,Super GT,Series 2,"Backstage, Seasonal","""Hard to Find""",Ferrari 599 GTO,"350,000",EPIC,S1 828,0

### Convert dataframe to csv

In [59]:
df_missing_alphabetical.to_csv("FH5/FH5-missing-alphabetical.csv", index=False, encoding="utf-8-sig")
df_missing_master.to_csv("FH5/FH5-missing-master.csv", index=False, encoding="utf-8-sig")
df_missing_series.to_csv("FH5/FH5-missing-series.csv", index=False, encoding="utf-8-sig")