In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("FH5/FH5-0-owned.csv", encoding="cp1252")
df.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,NaN
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,1
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,1
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,NaN
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,NaN

In [3]:
df.dtypes

Brand           str
Vehicle         str
Year          int64
 Value          str
Collection      str
Rarity          str
PI              str
Owned           str
dtype: object

In [4]:
df["Year"] = df["Year"].astype(str)
df.dtypes

Brand         str
Vehicle       str
Year          str
 Value        str
Collection    str
Rarity        str
PI            str
Owned         str
dtype: object

In [5]:
df["Owned"] = df["Owned"].fillna("1")
df.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,1
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,1
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,1
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,1
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,1

In [6]:
df["Owned"].value_counts()

Owned
1    848
-     49
0      5
Name: count, dtype: int64

In [7]:
df = df.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df = df.reset_index(drop=True)
df.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,1
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,1
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,1
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,1
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,1

In [8]:
df_notowned = df.iloc[df["Owned"].str.contains("0")]
df_notowned.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
28,Aston Martin,DBR1,1958,"22,500,000",Autoshow,LEGENDARY,B 678,0
119,Brabham,BT62,2019,"1,500,000","HW Academy: ""Double Trouble"", Autoshow (DLC: H...",LEGENDARY,S2 974,0
385,Hennessey,Venom F5,2021,"3,000,000","HW Academy: ""Fresh Orange Routes"", Autoshow (D...",LEGENDARY,S2 964,0
547,Lotus,Evija,2020,"2,500,000","Autoshow, ""Horizon Arcade Fan"" accolade",LEGENDARY,S2 994,0
810,SIERRA Cars,#23 Yokohama Alpha,2020,"70,000","HW Academy: ""Hot Wheels Legend"", Autoshow (DLC...",EPIC,S2 986,0

In [9]:
df_notowned_htf = df_notowned[df_notowned["Collection"].str.contains("Hard to Find")]
df_notowned_htf.head()

Empty DataFrame
Columns: [Brand, Vehicle, Year,  Value , Collection, Rarity, PI, Owned]
Index: []

In [10]:
df_save = df_notowned_htf.copy()

In [11]:
df_save["Vehicle"] = df_notowned_htf["Brand"] + " " + df_notowned_htf["Vehicle"] + "(" + df_notowned_htf["Year"] + ")"
df_save.head()

Empty DataFrame
Columns: [Brand, Vehicle, Year,  Value , Collection, Rarity, PI, Owned]
Index: []

In [12]:
columns_to_drop = [0, 2]
df_save = df_save.drop(df_save.columns[columns_to_drop], axis=1)
df_save.head()

Empty DataFrame
Columns: [Vehicle,  Value , Collection, Rarity, PI, Owned]
Index: []

In [13]:
df_nonautoshow = df_notowned[~df_notowned["Collection"].str.contains("Autoshow")]
df_nonautoshow["Vehicle"] = df_nonautoshow["Year"] + " " + df_nonautoshow["Brand"] + " " + df_nonautoshow["Vehicle"]
df_nonautoshow = df_nonautoshow.drop(df_nonautoshow.columns[columns_to_drop], axis=1)
df_nonautoshow.head()

Empty DataFrame
Columns: [Vehicle,  Value , Collection, Rarity, PI, Owned]
Index: []

In [14]:
#df_save.to_csv("FH5/FH5-missingHtF.csv", index=False, encoding="utf-8-sig")
#df_nonautoshow.to_csv("FH5/FH5-nonautoshow.csv", index=False, encoding="utf-8-sig")
df_notowned.to_csv("FH5/FH5-notowned.csv", index=False, encoding="utf-8-sig")