In [147]:
import pandas as pd

# Import FH5 car list extended

In [148]:
filename = "Forza Horizon 5 Car List"
tables = pd.read_html("raw-website/" + filename + ".htm")
df = tables[0]
df.head(10)

,Car Model,Car Type,Collect,Added,Nickname,ID
0,2017 Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740
1,2016 Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489
2,1980 Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124
3,1968 Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017
4,2017 Acura NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352
5,2002 Acura RSX Type-S,Retro Hot Hatch,Autoshow,Launch,Acura RSX,422
6,2001 Acura Integra Type-R,Retro Hot Hatch,Autoshow,Launch,Acura Integra,368
7,2017 Alfa Romeo Giulia Quadrifoglio,Super Saloons,Autoshow,Series 24,Alfa Giulia '17,2542
8,2014 Alfa Romeo 4C,Modern Sports Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 4C,2038
9,2007 Alfa Romeo 8C Competizione,GT Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 8C,1032

## Check stats

In [149]:
df.dtypes

Car Model      str
Car Type       str
Collect        str
Added          str
Nickname       str
ID           int64
dtype: object

In [150]:
df["Nickname"].value_counts()

Nickname
Honda S2000        2
Porsche Cayman     2
Abarth 124 '17     1
Abarth 695 '16     1
Abarth 131         1
                  ..
Wuling Mini EV     1
Wuling Sunshine    1
Xpeng P7           1
Zenvo TSR-S        1
Zenvo ST1          1
Name: count, Length: 900, dtype: int64

In [151]:
df_filter = df[(df["Nickname"].str.contains("Honda S2000"))|(df["Nickname"].str.contains("Porsche Cayman"))]
df_filter.head()

,Car Model,Car Type,Collect,Added,Nickname,ID
394,2009 Honda S2000 CR,Modern Sports Cars,"Autoshow, Wheelspin",Launch,Honda S2000,2005
399,2003 Honda S2000,Modern Sports Cars,"Autoshow, Wheelspin",Launch,Honda S2000,427
753,2016 Porsche Cayman GT4,Track Toys,"Autoshow, Wheelspin",Launch,Porsche Cayman,2529
754,2015 Porsche Cayman GTS,Modern Sports Cars,"Autoshow, Wheelspin",Launch,Porsche Cayman,2293

In [152]:
df["ID"].value_counts()

ID
1451    2
2181    2
1328    2
1387    2
1253    2
       ..
3789    1
3548    1
3547    1
3212    1
2474    1
Name: count, Length: 897, dtype: int64

In [153]:
df_filter = df[(df["ID"]==1451)|(df["ID"]==2181)|(df["ID"]==1328)|(df["ID"]==1387)|(df["ID"]==1253)]
df_filter = df_filter.sort_values("ID")
display(df_filter)

,Car Model,Car Type,Collect,Added,Nickname,ID
657,2010 Mosler MT900S,Extreme Track Toys,"Autoshow, Wheelspin",Launch,Mosler MT900S,1253
698,2010 Noble M600,Modern Supercars,"Backstage, Seasonal",Series 5,Noble M600,1253
306,2011 Ford F-150 SVT Raptor,Pickups & 4x4s,"Autoshow, Wheelspin",Launch,Ford Raptor '11,1328
122,2011 Bugatti Veyron Super Sport,Hypercars,Autoshow,Launch,Bugatti Veyron,1328
892,1997 Volvo 850 R,Retro Saloons,"Autoshow, Wheelspin",Launch,Volvo 850,1387
608,1998 Mercedes-Benz AMG CLK GTR,Retro Supercars,"Autoshow, Wheelspin",Launch,M-B CLK-GTR,1387
98,2012 BMW M5,Super Saloons,"Autoshow, Wheelspin",Launch,BMW M5 '12,1451
27,2012 Ascari KZ1R,Modern Supercars,"Backstage, Seasonal",Series 6,Ascari KZ1R,1451
38,2013 Aston Martin V12 Vantage S,Super GT,"Autoshow, Wheelspin",Launch,Vantage S '13,2181
57,2013 Audi R8 Coupe V10 plus 5.2 FSI quattro,Modern Supercars,"Backstage, Wheelspin, Seasonal",Launch,Audi R8 '13,2181

## Split Year from Car Model

In [154]:
df[["Year", "Car Model"]] = df["Car Model"].str.extract(r'^(\d{4})(.*)$')
df["Car Model"] = df["Car Model"].str.strip()
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
0,Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017
1,Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016
2,Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980
3,Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968
4,Acura NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,2017

In [155]:
df.dtypes

Car Model      str
Car Type       str
Collect        str
Added          str
Nickname       str
ID           int64
Year           str
dtype: object

## Split Brand from Car Model

### Isolate rows for 2-word vehicle brand names

In [156]:
df1 = df.iloc[df["Car Model"].str.contains("Alfa|Aston|Auto Union|Automobili Pininfarina|Extreme E|Formula Drift|Forsberg Racing|Funco Motorsports|Land Rover|Local Motors|RJ Anderson|SIERRA Cars|Spania GTA|Universal Studios|W Motors")]
df1.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
7,Alfa Romeo Giulia Quadrifoglio,Super Saloons,Autoshow,Series 24,Alfa Giulia '17,2542,2017
8,Alfa Romeo 4C,Modern Sports Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 4C,2038,2014
9,Alfa Romeo 8C Competizione,GT Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 8C,1032,2007
10,Alfa Romeo 155 Q4,Retro Saloons,"Backstage, Seasonal",Series 24,Alfa Romeo 155,1393,1992
11,Alfa Romeo 33 Stradale,Classic Racers,Autoshow,Series 24,Alfa Romeo 33S,1549,1968

#### Replace first whitespace with underscore

In [157]:
df1["Car Model"] = df1["Car Model"].str.replace(" ", "_", n=1)
df1.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
7,Alfa_Romeo Giulia Quadrifoglio,Super Saloons,Autoshow,Series 24,Alfa Giulia '17,2542,2017
8,Alfa_Romeo 4C,Modern Sports Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 4C,2038,2014
9,Alfa_Romeo 8C Competizione,GT Cars,"Backstage, Seasonal",Series 24,Alfa Romeo 8C,1032,2007
10,Alfa_Romeo 155 Q4,Retro Saloons,"Backstage, Seasonal",Series 24,Alfa Romeo 155,1393,1992
11,Alfa_Romeo 33 Stradale,Classic Racers,Autoshow,Series 24,Alfa Romeo 33S,1549,1968

### Separate filtering for Hot Wheels

In [158]:
df_hw = df.iloc[df["Car Model"].str.contains("Hot Wheels")]
df_hw = df_hw.loc[~df_hw["Car Model"].str.contains("Brabham|Chevrolet|Hennessey|Mosler|SUBARU|Schuppan|SIERRA")]
df_hw.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
420,Hot Wheels 2JetZ,Rods and Customs,"Backstage, Wheelspin, Seasonal",Series 9,2JetZ,3405,2018
421,Hot Wheels Baja Bone Shaker,Unlimited Offroad,Autoshow DLC,Hot Wheels Expansion,Baja Bone Shaker,3702,2013
422,Hot Wheels Bad to the Blade,Extreme Track Toys,Autoshow DLC,Hot Wheels Expansion,Hot Wheels BTTB,1532,2012
423,Hot Wheels Rip Rod,Unlimited Buggies,"Backstage, Wheelspin, Seasonal",Series 9,Rip Rod,3704,2012
424,Hot Wheels Bone Shaker,Rods and Customs,Autoshow,Launch,Bone Shaker,1477,2011

In [159]:
df_hw["Car Model"] = df_hw["Car Model"].str.replace(" ", "_", n=1)
df_hw.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
420,Hot_Wheels 2JetZ,Rods and Customs,"Backstage, Wheelspin, Seasonal",Series 9,2JetZ,3405,2018
421,Hot_Wheels Baja Bone Shaker,Unlimited Offroad,Autoshow DLC,Hot Wheels Expansion,Baja Bone Shaker,3702,2013
422,Hot_Wheels Bad to the Blade,Extreme Track Toys,Autoshow DLC,Hot Wheels Expansion,Hot Wheels BTTB,1532,2012
423,Hot_Wheels Rip Rod,Unlimited Buggies,"Backstage, Wheelspin, Seasonal",Series 9,Rip Rod,3704,2012
424,Hot_Wheels Bone Shaker,Rods and Customs,Autoshow,Launch,Bone Shaker,1477,2011

### Isolate rows for 3-word vehicle brand names

In [160]:
df2 = df.iloc[df["Car Model"].str.contains("AMG Transport|Casey Currie|Fast and Furious|Gordon Murray|Lynk & Co")]
df2.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
22,AMG Transport Dynamics M12S Warthog CST,Unlimited Offroad,"Autoshow, Wheelspin",Launch,M12S Warthog CST,2574,2554
135,Casey Currie Motorsports #4402 Ultra 4 'Trophy...,Unlimited Offroad,Autoshow DLC,Rally Adventure Expansion,#4402 Ultra 4,3603,2019
222,Fast and Furious Dodge Charger SRT Hellcat Red...,Modern Muscle,Autoshow DLC,Fast X Car Pack,FAF Hellcat,3836,2022
223,Fast and Furious Flip Car 2.0 'Fast X',Track Toys,Autoshow DLC,Fast X Car Pack,FAF Flip Car,3838,2022
224,Fast and Furious Datsun 240Z 'Fast X',Classic Sports Cars,Autoshow DLC,Fast X Car Pack,FAF 240Z,3832,1973

#### Replace first two whitespace with underscore

In [161]:
df2["Car Model"] = df2["Car Model"].str.replace(" ", "_", n=2)
df2.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
22,AMG_Transport_Dynamics M12S Warthog CST,Unlimited Offroad,"Autoshow, Wheelspin",Launch,M12S Warthog CST,2574,2554
135,Casey_Currie_Motorsports #4402 Ultra 4 'Trophy...,Unlimited Offroad,Autoshow DLC,Rally Adventure Expansion,#4402 Ultra 4,3603,2019
222,Fast_and_Furious Dodge Charger SRT Hellcat Red...,Modern Muscle,Autoshow DLC,Fast X Car Pack,FAF Hellcat,3836,2022
223,Fast_and_Furious Flip Car 2.0 'Fast X',Track Toys,Autoshow DLC,Fast X Car Pack,FAF Flip Car,3838,2022
224,Fast_and_Furious Datsun 240Z 'Fast X',Classic Sports Cars,Autoshow DLC,Fast X Car Pack,FAF 240Z,3832,1973

### Update df_lite with altered rows

In [162]:
df.update(df1)
df.update(df2)
df.update(df_hw)
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year
0,Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017
1,Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016
2,Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980
3,Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968
4,Acura NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,2017

### Perform split

In [163]:
df[["Brand", "Car Model"]] = df["Car Model"].str.split(" ", n=1, expand=True)
#df = df.iloc[:, [4, 0, 1, 2, 3]]
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year,Brand
0,124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017,Abarth
1,695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016,Abarth
2,Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980,Abarth
3,595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968,Abarth
4,NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,2017,Acura

#### Error checking

In [164]:
df_verify = df.iloc[df["Car Model"].str.contains("_")]
df_verify.head()

Empty DataFrame
Columns: [Car Model, Car Type, Collect, Added, Nickname, ID, Year, Brand]
Index: []

#### Replace underscores in Brand column with whitespace

In [165]:
df["Brand"] = df["Brand"].str.replace("_", " ")
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year,Brand
0,124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017,Abarth
1,695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016,Abarth
2,Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980,Abarth
3,595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968,Abarth
4,NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,2017,Acura

## Sort by Brand then Year and Vehicle (ascending)

In [166]:
df["Year"] = df["Year"].str.strip()
df = df.sort_values(["Brand", "Year", "Car Model"], ascending=[True, True, True], key=lambda col: col.str.lower())
df = df.reset_index(drop=True)
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Year,Brand
0,595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,1968,Abarth
1,Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,1980,Abarth
2,695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2016,Abarth
3,124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,2017,Abarth
4,Integra Type-R,Retro Hot Hatch,Autoshow,Launch,Acura Integra,368,2001,Acura

## Merge columns

In [167]:
df["Car Model"] = df["Year"] + " " + df["Brand"] + " " + df["Car Model"]
df = df.drop(["Year", "Brand"], axis=1)
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID
0,1968 Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017
1,1980 Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124
2,2016 Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489
3,2017 Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740
4,2001 Acura Integra Type-R,Retro Hot Hatch,Autoshow,Launch,Acura Integra,368

# Read FH5 user data

In [81]:
df_owned = pd.read_csv("FH5/FH5-0-owned.csv", encoding="cp1252")
df_owned.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,Owned
0,Abarth,595 esseesse,1968,"35,000",Autoshow,COMMON,D 100,NaN
1,Abarth,Fiat 131,1980,"250,000","""Hard to Find""",COMMON,C 510,0
2,Abarth,695 Biposto,2016,"250,000","""Hard to Find""",COMMON,B 657,0
3,Abarth,124 Spider,2017,"250,000","""Hard to Find""",COMMON,C 562,NaN
4,Acura,Integra Type-R,2001,"25,000",Autoshow,COMMON,C 596,NaN

In [82]:
df_owned.dtypes

Brand           str
Vehicle         str
Year          int64
 Value          str
Collection      str
Rarity          str
PI              str
Owned           str
dtype: object

## Merge and remove redundant columns

In [83]:
df_owned["Year"] = df_owned["Year"].astype(str)
df_owned = df_owned.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, False, True], key=lambda col: col.str.lower())
df_owned = df_owned.reset_index(drop=True)

df_owned["Car Model"] = df_owned["Year"] + " " + df_owned["Brand"] + " " + df_owned["Vehicle"]
columns_to_drop = ["Brand", "Vehicle", "Year"]
df_owned = df_owned.drop(["Brand", "Vehicle", "Year"], axis=1)
df_owned = df_owned.iloc[:, [5, 0, 1, 2, 3, 4]]

df_owned["Owned"] = df_owned["Owned"].fillna("1")
df_owned.head()

                   Car Model     Value       Collection  Rarity      PI Owned
0    2017 Abarth 124 Spider    250,000   "Hard to Find"  COMMON   C 562     1
1   2016 Abarth 695 Biposto    250,000   "Hard to Find"  COMMON   B 657     0
2      1980 Abarth Fiat 131    250,000   "Hard to Find"  COMMON   C 510     0
3  1968 Abarth 595 esseesse     35,000         Autoshow  COMMON   D 100     1
4            2017 Acura NSX    170,000         Autoshow    RARE  S1 831     1

In [84]:
df_owned["Owned"].value_counts()

Owned
1    708
0    144
-     50
Name: count, dtype: int64

In [85]:
df["Number"] = df.index + 1
df.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number
0,2017 Abarth 124 Spider,Modern Sports Cars,"Backstage, Seasonal",Series 24,Abarth 124 '17,2740,1
1,2016 Abarth 695 Biposto,Hot Hatch,"Backstage, Seasonal",Series 24,Abarth 695 '16,2489,2
2,1980 Abarth Fiat 131,Classic Rally,"Backstage, Seasonal",Series 24,Abarth 131,1124,3
3,1968 Abarth 595 esseesse,Cult Cars,Autoshow,Series 24,Abarth 595 '68,2017,4
4,2017 Acura NSX,Modern Supercars,Autoshow,Launch,Acura NSX '17,2352,5

In [86]:
df_owned["Number"] = df_owned.index + 1
df_owned.head()

,Car Model,Value,Collection,Rarity,PI,Owned,Number
0,2017 Abarth 124 Spider,"250,000","""Hard to Find""",COMMON,C 562,1,1
1,2016 Abarth 695 Biposto,"250,000","""Hard to Find""",COMMON,B 657,0,2
2,1980 Abarth Fiat 131,"250,000","""Hard to Find""",COMMON,C 510,0,3
3,1968 Abarth 595 esseesse,"35,000",Autoshow,COMMON,D 100,1,4
4,2017 Acura NSX,"170,000",Autoshow,RARE,S1 831,1,5

In [87]:
df["Car Model"] = df["Car Model"].str.strip()
df_owned["Car Model"] = df_owned["Car Model"].str.strip()
df_master = pd.merge(df, df_owned, on="Car Model", how="outer")
df_master.head()

,Car Model,Car Type,Collect,Added,Nickname,ID,Number_x,Value,Collection,Rarity,PI,Owned,Number_y
0,1926 Bugatti Type 35 C,Vintage Racers,"Autoshow, Wheelspin",Launch,Bugatti T35 C,2066.0,125.0,"1,300,000","Autoshow, Wheelspin",LEGENDARY,D 285,1,125.0
1,1929 Mercedes-Benz SSK,Rare Classics,"Autoshow, Wheelspin",Launch,M-B SSK,3026.0,619.0,"7,500,000","Autoshow, Wheelspin",LEGENDARY,D 256,1,619.0
2,1930 Bentley 8 Litre,Rare Classics,"Autoshow, Wheelspin",Launch,4-1/2 Liter '31,2976.0,81.0,"1,500,000","Autoshow, Wheelspin",LEGENDARY,D 181,1,82.0
3,1930 Bentley Blower 4-1/2 Litre Supercharged,Vintage Racers,"Autoshow, Wheelspin",Launch,Bentley 8 Litre,1372.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1931 Bentley Blower 4-1/2 Litre Supercharged,NaN,NaN,NaN,NaN,NaN,NaN,"4,000,000","Autoshow, Wheelspin",LEGENDARY,D 207,0,81.0

In [88]:
df_master.dtypes

Car Model         str
Car Type          str
Collect           str
Added             str
Nickname          str
ID            float64
Number_x      float64
 Value            str
Collection        str
Rarity            str
PI                str
Owned             str
Number_y      float64
dtype: object

## Expand abbreviated columns

## Remove stat columns from df_lite

In [ ]:
columns_to_drop = [2, 3, 4, 5, 6, 7]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

## Split original Value column into Value and Rarity

In [ ]:
df_lite.iloc[df_lite["Value"].str.contains("?", regex=False)].head()

In [ ]:
df_lite[["Value", "Rarity"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

## Split original Vehicle column into Brand and Vehicle

### Isolate rows for 2-word vehicle brand names

In [ ]:
df1 = df_lite.iloc[df_lite["Vehicle"].str.contains("Alfa|Aston|Auto Union|Automobili Pininfarina|Extreme E|Formula Drift|Forsberg Racing|Funco Motorsports|Land Rover|Local Motors|RJ Anderson|SIERRA Cars|Spania GTA|Universal Studios|W Motors")]
df1.head()

#### Replace first whitespace with underscore

In [ ]:
df1["Vehicle"] = df1["Vehicle"].str.replace(" ", "_", n=1)
df1.head()

### Separate filtering for Hot Wheels

In [ ]:
df_hw = df_lite.iloc[df_lite["Vehicle"].str.contains("Hot Wheels")]
df_hw = df_hw.loc[~df_hw["Vehicle"].str.contains("Brabham|Chevrolet|Hennessey|Mosler|SUBARU|Schuppan|SIERRA")]
df_hw.head()

In [ ]:
df_hw["Vehicle"] = df_hw["Vehicle"].str.replace(" ", "_", n=1)
df_hw.head()

### Isolate rows for 3-word vehicle brand names

In [ ]:
df2 = df_lite.iloc[df_lite["Vehicle"].str.contains("AMG Transport|Casey Currie|Fast and Furious|Gordon Murray|Lynk & Co")]
df2.head()

#### Replace first two whitespace with underscore

In [ ]:
df2["Vehicle"] = df2["Vehicle"].str.replace(" ", "_", n=2)
df2.head()

### Update df_lite with altered rows

In [ ]:
df_lite.update(df1)
df_lite.head()

In [ ]:
df_lite.update(df2)
df_lite.head()

In [ ]:
df_lite.update(df_hw)
df_lite.head()

### Perform split

In [ ]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

#### Error checking

In [ ]:
df_verify = df_lite.iloc[df_lite["Vehicle"].str.contains("_")]
df_verify.head()

#### Replace underscores in Brand column with whitespace

In [ ]:
df_lite["Brand"] = df_lite["Brand"].str.replace("_", " ")
df_lite.head()

## Split into 3 columns using str.extract and regex

### Filter "Car Mastery" rows separately

In [ ]:
df_cm = df_lite.iloc[df_lite["Vehicle"].str.contains("Car Mastery")]
df_cm.head()

In [ ]:
df_cm[["Vehicle", "Year", "Collection"]] = df_cm["Vehicle"].str.extract(r'^(.*?)(\d{4})(.*)$')
df_cm = df_cm.iloc[:, [0, 1, 5, 2, 6, 3, 4]]
df_cm.head()

### Perform general splitting

In [ ]:
df_lite[["Vehicle", "Year", "Collection"]] = df_lite["Vehicle"].str.extract(r'^(.*)(\d{4})(.*)$')
df_lite = df_lite.iloc[:, [0, 1, 5, 2, 6, 3, 4]]
df_lite.head()

#### Update with df_cm

In [ ]:
df_lite.update(df_cm)
df_lite.head()

In [ ]:
df_lite.iloc[df_lite["Collection"].str.contains("Car Mastery")].head()

## Sort by Brand then Year and Vehicle (ascending)

In [ ]:
df_lite.dtypes

In [ ]:
df_lite = df_lite.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df_lite = df_lite.reset_index(drop=True)
df_lite.head(10)

## Clean PI column

In [ ]:
df_lite[["PI1", "PI2"]] = df_lite["PI"].str.split(r'(?<=D)|(?<=C)|(?<=B)|(?<=A)|(?<=S1)|(?<=S2)', n=1,
                                                                  expand=True)
df_lite.head()

### Stats

In [ ]:
df_lite["PI1"].value_counts()
# "A" is the most common class
# followed by S1
# then B

In [ ]:
df_lite["PI2"].value_counts()
# A 800 is the most common PI value

In [ ]:
df_lite["Year"].value_counts()

In [ ]:
df_lite["Value"].value_counts()

In [ ]:
df_lite["Rarity"].value_counts()

In [ ]:
df_lite["PI"] = df_lite["PI1"] + " " + df_lite["PI2"]
df_lite = df_lite.drop(["PI1", "PI2"], axis="columns")
df_lite.head()

In [ ]:
df_lite["Owned"] = pd.Series(dtype="string")
df_lite.head()

### Convert dataframe to csv

In [ ]:
df_lite.to_csv("FH5/FH5-0-masterlist.csv", index=False, encoding="utf-8-sig")