In [27]:
import pandas as pd

# Import raw data for preprocessing

In [28]:
filename = "FH6-cars-list-16-08-26"
tables = pd.read_html("raw-website/" + filename + ".htm")
df = tables[1]
df.head(10)

,Vehicle,🔓,🦄,📅,🌍,Value,Sp,Ha,Ac,La,Br,Of,PI
0,"Abarth 124 Spider 2017""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRRARE",5.2,4.7,3.8,4.6,3.3,5.5,C450
1,"Abarth 695 Biposto 2016""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",4.9,5.3,4.7,3.9,4.8,5.1,B540
2,"Abarth Fiat 131 1980Autoshow, Wheelspin",NaN,NaN,NaN,NaN,"125,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.9,D399
3,"Abarth 595 esseesse 1968Autoshow, Wheelspin",NaN,NaN,NaN,NaN,"25,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.2,D100
4,"Acura Integra A-Spec 2023Autoshow, Wheelspin, ...",NaN,NaN,NaN,NaN,"36,000 CRRARE",5.7,4.7,4.2,4.2,3.7,5.5,C484
5,Acura NSX Type S 2022Earn the Blue wristband,NaN,NaN,NaN,NaN,"193,000 CREPIC",7.3,6.2,8.7,7.7,6.9,5.4,S1734
6,"Acura RSX Type S 2002Autoshow, Wheelspin, Afte...",NaN,NaN,NaN,NaN,"18,000 CRCOMMON",5.6,4.7,3.9,3.0,3.5,5.6,C462
7,"Acura Integra Type R 2001Autoshow, Wheelspin",NaN,NaN,NaN,NaN,"25,000 CRCOMMON",5.6,4.6,3.9,3.1,3.4,5.4,C471
8,Alfa Romeo Giulia GTAm 2021Autoshow (DLC: Ital...,NaN,NaN,NaN,NaN,"225,000 CRRARE",6.9,6.3,5.5,5.9,7.2,4.6,S1711
9,"Alfa Romeo Giulia Quadrifoglio 2017Autoshow, W...",NaN,NaN,NaN,NaN,"45,000 CRRARE",7.3,6.4,5.9,4.9,6.7,5.0,A667

## Remove redundant columns

In [29]:
columns_to_drop = [1, 2, 3, 4]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,Of,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRRARE",5.2,4.7,3.8,4.6,3.3,5.5,C450
1,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,3.9,4.8,5.1,B540
2,"Abarth Fiat 131 1980Autoshow, Wheelspin","125,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.9,D399
3,"Abarth 595 esseesse 1968Autoshow, Wheelspin","25,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.2,D100
4,"Acura Integra A-Spec 2023Autoshow, Wheelspin, ...","36,000 CRRARE",5.7,4.7,4.2,4.2,3.7,5.5,C484

## Expand abbreviated columns

In [30]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,OffRd,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRRARE",5.2,4.7,3.8,4.6,3.3,5.5,C450
1,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,3.9,4.8,5.1,B540
2,"Abarth Fiat 131 1980Autoshow, Wheelspin","125,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.9,D399
3,"Abarth 595 esseesse 1968Autoshow, Wheelspin","25,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.2,D100
4,"Acura Integra A-Spec 2023Autoshow, Wheelspin, ...","36,000 CRRARE",5.7,4.7,4.2,4.2,3.7,5.5,C484

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   636 non-null    str
 1   Value     636 non-null    str
 2   Speed     636 non-null    float64
 3   Handling  636 non-null    float64
 4   Accel     636 non-null    float64
 5   Launch    636 non-null    float64
 6   Braking   636 non-null    float64
 7   OffRd     636 non-null    float64
 8   PI        636 non-null    str
dtypes: float64(6), str(3)
memory usage: 44.8 KB

## Remove stat columns from df_lite

In [32]:
columns_to_drop = [2, 3, 4, 5, 6, 7]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                                             Vehicle             Value    PI
0               Abarth 124 Spider 2017"Hard to Find"    250,000 CRRARE  C450
1              Abarth 695 Biposto 2016"Hard to Find"  250,000 CRCOMMON  B540
2            Abarth Fiat 131 1980Autoshow, Wheelspin  125,000 CRCOMMON  D399
3        Abarth 595 esseesse 1968Autoshow, Wheelspin   25,000 CRCOMMON  D100
4  Acura Integra A-Spec 2023Autoshow, Wheelspin, ...     36,000 CRRARE  C484

## Split original Value column into Value and Rarity

In [33]:
df_lite.iloc[df_lite["Value"].str.contains("?", regex=False)].head()

Empty DataFrame
Columns: [Vehicle, Value, PI]
Index: []

In [34]:
df_lite[["Value", "Rarity"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].str.replace("?", "0")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                                             Vehicle   Value  Rarity    PI
0               Abarth 124 Spider 2017"Hard to Find"  250000    RARE  C450
1              Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B540
2            Abarth Fiat 131 1980Autoshow, Wheelspin  125000  COMMON  D399
3        Abarth 595 esseesse 1968Autoshow, Wheelspin   25000  COMMON  D100
4  Acura Integra A-Spec 2023Autoshow, Wheelspin, ...   36000    RARE  C484

## Split original Vehicle column into Brand and Vehicle

### Isolate rows for 2-word vehicle brand names

In [35]:
df1 = df_lite.iloc[df_lite["Vehicle"].str.contains("Alfa|Aston|De Tomaso|Formula Drift|Funco Motorsports|Land Rover|RJ Anderson|SIERRA Cars")]
df1.head()

                                              Vehicle   Value Rarity     PI
8   Alfa Romeo Giulia GTAm 2021Autoshow (DLC: Ital...  225000   RARE  S1711
9   Alfa Romeo Giulia Quadrifoglio 2017Autoshow, W...   45000   RARE   A667
10                         Alfa Romeo 4C 2014Autoshow   73000   EPIC   A644
11  Alfa Romeo 8C Competizione 2007Autoshow, Wheel...  312000   EPIC   A635
12                     Alfa Romeo 155 Q4 1992Autoshow   30000   EPIC   C439

#### Replace first whitespace with underscore

In [36]:
df1["Vehicle"] = df1["Vehicle"].str.replace(" ", "_", n=1)
df1.head()

                                              Vehicle   Value Rarity     PI
8   Alfa_Romeo Giulia GTAm 2021Autoshow (DLC: Ital...  225000   RARE  S1711
9   Alfa_Romeo Giulia Quadrifoglio 2017Autoshow, W...   45000   RARE   A667
10                         Alfa_Romeo 4C 2014Autoshow   73000   EPIC   A644
11  Alfa_Romeo 8C Competizione 2007Autoshow, Wheel...  312000   EPIC   A635
12                     Alfa_Romeo 155 Q4 1992Autoshow   30000   EPIC   C439

### Isolate rows for 3-word vehicle brand names

In [37]:
df2 = df_lite.iloc[df_lite["Vehicle"].str.contains("AMG Transport|Casey Currie|Gordon Murray")]
df2.head()

,Vehicle,Value,Rarity,PI
21,AMG Transport Dynamics M12S Warthog CST 2554Au...,850000,LEGENDARY,A663
100,Casey Currie Motorsports #4402 Ultra 4 'Trophy...,250000,EPIC,A641
260,"Gordon Murray Automotive T.50 2022Autoshow, Ea...",3050000,LEGENDARY,S2871

#### Replace first two whitespace with underscore

In [38]:
df2["Vehicle"] = df2["Vehicle"].str.replace(" ", "_", n=2)
df2.head()

,Vehicle,Value,Rarity,PI
21,AMG_Transport_Dynamics M12S Warthog CST 2554Au...,850000,LEGENDARY,A663
100,Casey_Currie_Motorsports #4402 Ultra 4 'Trophy...,250000,EPIC,A641
260,"Gordon_Murray_Automotive T.50 2022Autoshow, Ea...",3050000,LEGENDARY,S2871

### Update df_lite with altered rows

In [39]:
df_lite.update(df1)
df_lite.head()

                                             Vehicle   Value  Rarity    PI
0               Abarth 124 Spider 2017"Hard to Find"  250000    RARE  C450
1              Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B540
2            Abarth Fiat 131 1980Autoshow, Wheelspin  125000  COMMON  D399
3        Abarth 595 esseesse 1968Autoshow, Wheelspin   25000  COMMON  D100
4  Acura Integra A-Spec 2023Autoshow, Wheelspin, ...   36000    RARE  C484

In [40]:
df_lite.update(df2)
df_lite.head()

                                             Vehicle   Value  Rarity    PI
0               Abarth 124 Spider 2017"Hard to Find"  250000    RARE  C450
1              Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B540
2            Abarth Fiat 131 1980Autoshow, Wheelspin  125000  COMMON  D399
3        Abarth 595 esseesse 1968Autoshow, Wheelspin   25000  COMMON  D100
4  Acura Integra A-Spec 2023Autoshow, Wheelspin, ...   36000    RARE  C484

### Perform split

In [41]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

,Brand,Vehicle,Value,Rarity,PI
0,Abarth,"124 Spider 2017""Hard to Find""",250000,RARE,C450
1,Abarth,"695 Biposto 2016""Hard to Find""",250000,COMMON,B540
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484

#### Error checking

In [42]:
df_verify = df_lite.iloc[df_lite["Vehicle"].str.contains("_")]
df_verify.head()

Empty DataFrame
Columns: [Brand, Vehicle, Value, Rarity, PI]
Index: []

#### Replace underscores in Brand column with whitespace

In [43]:
df_lite["Brand"] = df_lite["Brand"].str.replace("_", " ")
df_lite.head()

,Brand,Vehicle,Value,Rarity,PI
0,Abarth,"124 Spider 2017""Hard to Find""",250000,RARE,C450
1,Abarth,"695 Biposto 2016""Hard to Find""",250000,COMMON,B540
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484

## Split into 3 columns using str.extract and regex

### Check "Car Mastery" rows

In [44]:
df_cm = df_lite.iloc[df_lite["Vehicle"].str.contains("Car Mastery")]
df_cm.head()

,Brand,Vehicle,Value,Rarity,PI
124,Chevrolet,Corvette Stingray 427 1967Car Mastery: Chevrol...,135000,EPIC,B510
178,Ferrari,F50 GT 1996Car Mastery: Ferrari F50,5500000,LEGENDARY,R948
197,Ford,Supervan 4 2022Car Mastery: Ford Supervan 3,2000000,EPIC,R919
290,Honda,Civic RS 1974Car Mastery: Honda Civic Type R (...,14000,COMMON,D254
522,Porsche,Carrera GT 2003Car Mastery: Porsche 918 Spyder,1800000,EPIC,S1758

In [45]:
df_cm[["Vehicle", "Year", "Collection"]] = df_cm["Vehicle"].str.extract(r'^(.*?)(\d{4})(.*)$')
df_cm = df_cm.iloc[:, [0, 1, 5, 2, 6, 3, 4]]
df_cm.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI
124,Chevrolet,Corvette Stingray 427,1967,135000,Car Mastery: Chevrolet Corvette Stingray Coupe,EPIC,B510
178,Ferrari,F50 GT,1996,5500000,Car Mastery: Ferrari F50,LEGENDARY,R948
197,Ford,Supervan 4,2022,2000000,Car Mastery: Ford Supervan 3,EPIC,R919
290,Honda,Civic RS,1974,14000,Car Mastery: Honda Civic Type R (2023),COMMON,D254
522,Porsche,Carrera GT,2003,1800000,Car Mastery: Porsche 918 Spyder,EPIC,S1758

### Perform general splitting

In [46]:
df_lite[["Vehicle", "Year", "Collection"]] = df_lite["Vehicle"].str.extract(r'^(.*)(\d{4})(.*)$')
df_lite = df_lite.iloc[:, [0, 1, 5, 2, 6, 3, 4]]
df_lite.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI
0,Abarth,124 Spider,2017,250000,"""Hard to Find""",RARE,C450
1,Abarth,695 Biposto,2016,250000,"""Hard to Find""",COMMON,B540
2,Abarth,Fiat 131,1980,125000,"Autoshow, Wheelspin",COMMON,D399
3,Abarth,595 esseesse,1968,25000,"Autoshow, Wheelspin",COMMON,D100
4,Acura,Integra A-Spec,2023,36000,"Autoshow, Wheelspin, Aftermarket Car",RARE,C484

#### Update with df_cm

In [47]:
df_lite.update(df_cm)
df_lite.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI
0,Abarth,124 Spider,2017,250000,"""Hard to Find""",RARE,C450
1,Abarth,695 Biposto,2016,250000,"""Hard to Find""",COMMON,B540
2,Abarth,Fiat 131,1980,125000,"Autoshow, Wheelspin",COMMON,D399
3,Abarth,595 esseesse,1968,25000,"Autoshow, Wheelspin",COMMON,D100
4,Acura,Integra A-Spec,2023,36000,"Autoshow, Wheelspin, Aftermarket Car",RARE,C484

In [48]:
df_lite.iloc[df_lite["Collection"].str.contains("Car Mastery")].head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI
124,Chevrolet,Corvette Stingray 427,1967,135000,Car Mastery: Chevrolet Corvette Stingray Coupe,EPIC,B510
178,Ferrari,F50 GT,1996,5500000,Car Mastery: Ferrari F50,LEGENDARY,R948
197,Ford,Supervan 4,2022,2000000,Car Mastery: Ford Supervan 3,EPIC,R919
290,Honda,Civic RS,1974,14000,Car Mastery: Honda Civic Type R (2023),COMMON,D254
522,Porsche,Carrera GT,2003,1800000,Car Mastery: Porsche 918 Spyder,EPIC,S1758

## Sort by Brand then Year and Vehicle (ascending)

In [49]:
df_lite.dtypes

Brand           str
Vehicle         str
Year            str
Value         int64
Collection      str
Rarity          str
PI              str
dtype: object

In [50]:
df_lite = df_lite.sort_values(["Brand", "Year", "Vehicle"], ascending=[True, True, True], key=lambda col: col.str.lower())
df_lite = df_lite.reset_index(drop=True)
df_lite.head(10)

,Brand,Vehicle,Year,Value,Collection,Rarity,PI
0,Abarth,595 esseesse,1968,25000,"Autoshow, Wheelspin",COMMON,D100
1,Abarth,Fiat 131,1980,125000,"Autoshow, Wheelspin",COMMON,D399
2,Abarth,695 Biposto,2016,250000,"""Hard to Find""",COMMON,B540
3,Abarth,124 Spider,2017,250000,"""Hard to Find""",RARE,C450
4,Acura,Integra Type R,2001,25000,"Autoshow, Wheelspin",COMMON,C471
5,Acura,RSX Type S,2002,18000,"Autoshow, Wheelspin, Aftermarket Car",COMMON,C462
6,Acura,NSX Type S,2022,193000,Earn the Blue wristband,EPIC,S1734
7,Acura,Integra A-Spec,2023,36000,"Autoshow, Wheelspin, Aftermarket Car",RARE,C484
8,Alfa Romeo,Giulia Sprint GTA Stradale,1965,343000,"Autoshow, Wheelspin",RARE,D379
9,Alfa Romeo,Giulia TZ2,1965,1200000,"Earn 4,500 points in the ""Horizon Promo"" categ...",LEGENDARY,B532

## Clean PI column

In [51]:
df_lite[["PI1", "PI2"]] = df_lite["PI"].str.split(r'(?<=D)|(?<=C)|(?<=B)|(?<=A)|(?<=S1)|(?<=S2)|(?<=R)', n=1,
                                                                  expand=True)
df_lite.head()

,Brand,Vehicle,Year,Value,Collection,Rarity,PI,PI1,PI2
0,Abarth,595 esseesse,1968,25000,"Autoshow, Wheelspin",COMMON,D100,D,100
1,Abarth,Fiat 131,1980,125000,"Autoshow, Wheelspin",COMMON,D399,D,399
2,Abarth,695 Biposto,2016,250000,"""Hard to Find""",COMMON,B540,B,540
3,Abarth,124 Spider,2017,250000,"""Hard to Find""",RARE,C450,C,450
4,Acura,Integra Type R,2001,25000,"Autoshow, Wheelspin",COMMON,C471,C,471

### Stats

In [ ]:
df_lite["PI1"].value_counts()
# "B" is the most common class
# followed by S1
# then A

PI1
B     126
S1    117
A     113
C     100
D      91
S2     58
R      31
Name: count, dtype: int64

In [ ]:
df_lite["PI2"].value_counts()
# D 100 is the most common PI value

PI2
100    14
700     8
900     8
484     4
678     4
       ..
440     1
308     1
426     1
107     1
906     1
Name: count, Length: 402, dtype: int64

## Filter to cars that are obtainable via Autoshow and Wheelspin

In [12]:
df_sort = df_lite[df_lite["Vehicle"].str.contains("Autoshow, Wheelspin")]
df_sort.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Hard to Find,Wheelspin,Aftermarket Car,Collection Journal
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399,True,False,True,False,False
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100,True,False,True,False,False
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484,True,False,True,True,False
6,Acura,"RSX Type S 2002Autoshow, Wheelspin, Aftermarke...",18000,COMMON,C462,True,False,True,True,False
7,Acura,"Integra Type R 2001Autoshow, Wheelspin",25000,COMMON,C471,True,False,True,False,False

In [13]:
df_sort.info()

<class 'pandas.DataFrame'>
Index: 397 entries, 2 to 626
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               397 non-null    str
 1   Vehicle             397 non-null    str
 2   Value               397 non-null    int64
 3   Rarity              397 non-null    str
 4   PI                  397 non-null    str
 5   Autoshow            397 non-null    bool
 6   Hard to Find        397 non-null    bool
 7   Wheelspin           397 non-null    bool
 8   Aftermarket Car     397 non-null    bool
 9   Collection Journal  397 non-null    bool
dtypes: bool(5), int64(1), str(4)
memory usage: 20.5 KB

## Sort vehicles by brand, then lowest to highest cost

In [14]:
#df_sort = df_sort.sort_values(["Vehicle", "Value"], ascending=[True, True])
df_sort = df_sort.sort_values(["Brand", "Value"], ascending=[True, True])
#df_sort = df_sort[df_sort["Value"] <= 500000]
df_sort.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Hard to Find,Wheelspin,Aftermarket Car,Collection Journal
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100,True,False,True,False,False
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399,True,False,True,False,False
6,Acura,"RSX Type S 2002Autoshow, Wheelspin, Aftermarke...",18000,COMMON,C462,True,False,True,True,False
7,Acura,"Integra Type R 2001Autoshow, Wheelspin",25000,COMMON,C471,True,False,True,False,False
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484,True,False,True,True,False

In [15]:
df_sort.info()

<class 'pandas.DataFrame'>
Index: 397 entries, 3 to 626
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               397 non-null    str
 1   Vehicle             397 non-null    str
 2   Value               397 non-null    int64
 3   Rarity              397 non-null    str
 4   PI                  397 non-null    str
 5   Autoshow            397 non-null    bool
 6   Hard to Find        397 non-null    bool
 7   Wheelspin           397 non-null    bool
 8   Aftermarket Car     397 non-null    bool
 9   Collection Journal  397 non-null    bool
dtypes: bool(5), int64(1), str(4)
memory usage: 20.5 KB

### Convert dataframes to csv

In [16]:
df_sort.to_csv(filename + "-sorted" + ".csv", index=False)

In [17]:
df_lite.to_csv(filename + ".csv", index=False)

## Filter to Wheelspin-exclusive cars

In [18]:
df_wheelspin = df_lite.loc[(df_lite["Autoshow"] == False) & (df_lite["Wheelspin"] == True)]
df_wheelspin = df_wheelspin.drop(columns=["Hard to Find", "Aftermarket Car"])
df_wheelspin.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Wheelspin,Collection Journal
21,Apollo,Intensa Emozione 2019Wheelspin,3200000,LEGENDARY,R916,False,True,False
27,Aston,Martin Valhalla Concept Car 2019Wheelspin,1150000,LEGENDARY,R960,False,True,False
28,Aston,Martin DBS Superleggera 2019Wheelspin,275000,EPIC,S1736,False,True,False
57,Audi,Sport quattro 1983Wheelspin,650000,EPIC,B526,False,True,False
62,Bentley,Bentayga 2016Wheelspin,250000,EPIC,A612,False,True,False

In [19]:
df_wheelspin["Rarity"].value_counts()

Rarity
EPIC             26
LEGENDARY        11
FORZA EDITION     8
RARE              1
Name: count, dtype: int64

### Associate each rarity with numerical value

In [20]:
rarity_dict = {"COMMON": 1, "RARE": 2, "EPIC": 3, "LEGENDARY": 4, "FORZA EDITION": 5}
df_wheelspin["Rarity Value"] = df_wheelspin["Rarity"].map(rarity_dict)
df_wheelspin.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Wheelspin,Collection Journal,Rarity Value
21,Apollo,Intensa Emozione 2019Wheelspin,3200000,LEGENDARY,R916,False,True,False,4
27,Aston,Martin Valhalla Concept Car 2019Wheelspin,1150000,LEGENDARY,R960,False,True,False,4
28,Aston,Martin DBS Superleggera 2019Wheelspin,275000,EPIC,S1736,False,True,False,3
57,Audi,Sport quattro 1983Wheelspin,650000,EPIC,B526,False,True,False,3
62,Bentley,Bentayga 2016Wheelspin,250000,EPIC,A612,False,True,False,3

### Sort Wheelspin-exclusives according to Rarity

In [21]:
df_wheelspin = df_wheelspin.sort_values(["Rarity Value", "Brand"], ascending=[True, True])
df_wheelspin.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Wheelspin,Collection Journal,Rarity Value
602,Toyota,"Sports 800 1965Wheelspin, Earn 4,000 points in...",250000,RARE,D141,False,True,True,2
28,Aston,Martin DBS Superleggera 2019Wheelspin,275000,EPIC,S1736,False,True,False,3
57,Audi,Sport quattro 1983Wheelspin,650000,EPIC,B526,False,True,False,3
71,BMW,"M2 Competition Coupé 2020Wheelspin, Earn the Y...",250000,EPIC,A656,False,True,False,3
62,Bentley,Bentayga 2016Wheelspin,250000,EPIC,A612,False,True,False,3

In [22]:
df_wheelspin = df_wheelspin.drop(columns=["Rarity Value"])
df_wheelspin.info()

<class 'pandas.DataFrame'>
Index: 46 entries, 602 to 624
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               46 non-null     str
 1   Vehicle             46 non-null     str
 2   Value               46 non-null     int64
 3   Rarity              46 non-null     str
 4   PI                  46 non-null     str
 5   Autoshow            46 non-null     bool
 6   Wheelspin           46 non-null     bool
 7   Collection Journal  46 non-null     bool
dtypes: bool(3), int64(1), str(4)
memory usage: 2.3 KB

### Dataframe to csv

In [23]:
df_wheelspin.to_csv(filename + "-wheelspin" + ".csv", index=False)

In [28]:
df_test = df_lite[(df_lite["Rarity"] == "COMMON") & (df_lite["Wheelspin"] == True)]
df_test = df_test.sort_values(["Value"], ascending=False)
df_test.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Hard to Find,Wheelspin,Aftermarket Car,Collection Journal
131,DeBerti,Toyota Tacoma TRD 'The Performance Truck' 2019...,250000,COMMON,S1717,True,False,True,False,False
414,Mercedes-Benz,"AMG Hammer Coupe 1987Autoshow, Wheelspin",225000,COMMON,B565,True,False,True,False,False
503,Porsche,"Taycan Turbo S 2020Autoshow, Wheelspin",200000,COMMON,S1725,True,False,True,False,False
55,Audi,"RS 4 Avant 2001Autoshow, Wheelspin",175000,COMMON,B544,True,False,True,False,False
220,Ford,"Mustang SVT Cobra R 2000Autoshow, Wheelspin",153000,COMMON,B528,True,False,True,False,False