In [58]:
import pandas as pd

In [59]:
filename = "fh6cars-15-07-26"

In [60]:
tables = pd.read_html(filename + ".htm")
df = tables[1]
df.head()

,Vehicle,🔓,🦄,📅,🌍,Value,Sp,Ha,Ac,La,Br,Of,PI
0,"Abarth 124 Spider 2017""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRRARE",5.2,4.7,3.8,4.6,3.3,5.5,C450
1,"Abarth 695 Biposto 2016""Hard to Find""",NaN,NaN,NaN,NaN,"250,000 CRCOMMON",4.9,5.3,4.7,3.9,4.8,5.1,B540
2,"Abarth Fiat 131 1980Autoshow, Wheelspin",NaN,NaN,NaN,NaN,"125,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.9,D399
3,"Abarth 595 esseesse 1968Autoshow, Wheelspin",NaN,NaN,NaN,NaN,"25,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.2,D100
4,"Acura Integra A-Spec 2023Autoshow, Wheelspin, ...",NaN,NaN,NaN,NaN,"36,000 CRRARE",5.7,4.7,4.2,4.2,3.7,5.5,C484

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 627 entries, 0 to 626
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Vehicle  627 non-null    str
 1   🔓        0 non-null      float64
 2   🦄        0 non-null      float64
 3   📅        0 non-null      float64
 4   🌍        0 non-null      float64
 5   Value    627 non-null    str
 6   Sp       627 non-null    float64
 7   Ha       627 non-null    float64
 8   Ac       627 non-null    float64
 9   La       627 non-null    float64
 10  Br       627 non-null    float64
 11  Of       627 non-null    float64
 12  PI       627 non-null    str
dtypes: float64(10), str(3)
memory usage: 63.8 KB

In [62]:
columns_to_drop = [1, 2, 3, 4]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,Of,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRRARE",5.2,4.7,3.8,4.6,3.3,5.5,C450
1,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,3.9,4.8,5.1,B540
2,"Abarth Fiat 131 1980Autoshow, Wheelspin","125,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.9,D399
3,"Abarth 595 esseesse 1968Autoshow, Wheelspin","25,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.2,D100
4,"Acura Integra A-Spec 2023Autoshow, Wheelspin, ...","36,000 CRRARE",5.7,4.7,4.2,4.2,3.7,5.5,C484

In [63]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,OffRd,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRRARE",5.2,4.7,3.8,4.6,3.3,5.5,C450
1,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,3.9,4.8,5.1,B540
2,"Abarth Fiat 131 1980Autoshow, Wheelspin","125,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.9,D399
3,"Abarth 595 esseesse 1968Autoshow, Wheelspin","25,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.2,D100
4,"Acura Integra A-Spec 2023Autoshow, Wheelspin, ...","36,000 CRRARE",5.7,4.7,4.2,4.2,3.7,5.5,C484

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 627 entries, 0 to 626
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   627 non-null    str
 1   Value     627 non-null    str
 2   Speed     627 non-null    float64
 3   Handling  627 non-null    float64
 4   Accel     627 non-null    float64
 5   Launch    627 non-null    float64
 6   Braking   627 non-null    float64
 7   OffRd     627 non-null    float64
 8   PI        627 non-null    str
dtypes: float64(6), str(3)
memory usage: 44.2 KB

In [65]:
columns_to_drop = [2, 3, 4, 5, 6, 7]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                                             Vehicle             Value    PI
0               Abarth 124 Spider 2017"Hard to Find"    250,000 CRRARE  C450
1              Abarth 695 Biposto 2016"Hard to Find"  250,000 CRCOMMON  B540
2            Abarth Fiat 131 1980Autoshow, Wheelspin  125,000 CRCOMMON  D399
3        Abarth 595 esseesse 1968Autoshow, Wheelspin   25,000 CRCOMMON  D100
4  Acura Integra A-Spec 2023Autoshow, Wheelspin, ...     36,000 CRRARE  C484

In [66]:
df_lite[["Value", "Rarity"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].str.replace("?", "0")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                                             Vehicle   Value  Rarity    PI
0               Abarth 124 Spider 2017"Hard to Find"  250000    RARE  C450
1              Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B540
2            Abarth Fiat 131 1980Autoshow, Wheelspin  125000  COMMON  D399
3        Abarth 595 esseesse 1968Autoshow, Wheelspin   25000  COMMON  D100
4  Acura Integra A-Spec 2023Autoshow, Wheelspin, ...   36000    RARE  C484

In [67]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

,Brand,Vehicle,Value,Rarity,PI
0,Abarth,"124 Spider 2017""Hard to Find""",250000,RARE,C450
1,Abarth,"695 Biposto 2016""Hard to Find""",250000,COMMON,B540
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484

In [68]:
df_lite.info()

<class 'pandas.DataFrame'>
RangeIndex: 627 entries, 0 to 626
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    627 non-null    str
 1   Vehicle  627 non-null    str
 2   Value    627 non-null    int64
 3   Rarity   627 non-null    str
 4   PI       627 non-null    str
dtypes: int64(1), str(4)
memory usage: 24.6 KB

In [69]:
df_sort = df_lite[df_lite["Vehicle"].str.contains("Autoshow, Wheelspin")]
df_sort.head()

,Brand,Vehicle,Value,Rarity,PI
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484
6,Acura,"RSX Type S 2002Autoshow, Wheelspin, Aftermarke...",18000,COMMON,C462
7,Acura,"Integra Type R 2001Autoshow, Wheelspin",25000,COMMON,C471

In [70]:
df_sort.info()

<class 'pandas.DataFrame'>
Index: 397 entries, 2 to 626
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    397 non-null    str
 1   Vehicle  397 non-null    str
 2   Value    397 non-null    int64
 3   Rarity   397 non-null    str
 4   PI       397 non-null    str
dtypes: int64(1), str(4)
memory usage: 18.6 KB

In [71]:
#df_sort = df_sort.sort_values(["Vehicle", "Value"], ascending=[True, True])
df_sort = df_sort.sort_values(["Value", "Vehicle"], ascending=[True, True])
df_sort.head()

,Brand,Vehicle,Value,Rarity,PI
625,Wuling,"Sunshine S 2013Autoshow, Wheelspin",2000,RARE,D107
623,Wuling,"Hongguang Mini EV 2022Autoshow, Wheelspin, Aft...",5000,RARE,D100
285,Honda,"City E II 1984Autoshow, Wheelspin, Aftermarket...",7500,EPIC,D203
277,Honda,"Acty 1994Autoshow, Wheelspin, Earn 750 points ...",9000,COMMON,D100
581,Toyota,"Crown Super Deluxe Taxi 2005Autoshow, Wheelspin",10000,COMMON,D181

In [72]:
df_sort.to_csv(filename + "-sorted" + ".csv", index=False)

In [73]:
df_lite.to_csv(filename + ".csv", index=False)