In [1]:
import pandas as pd

# Import raw data

In [ ]:
filename = "fh6cars-15-07-26"
tables = pd.read_html(filename + ".htm")
df = tables[1]
df.head()

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 627 entries, 0 to 626
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Vehicle  627 non-null    str
 1   🔓        0 non-null      float64
 2   🦄        0 non-null      float64
 3   📅        0 non-null      float64
 4   🌍        0 non-null      float64
 5   Value    627 non-null    str
 6   Sp       627 non-null    float64
 7   Ha       627 non-null    float64
 8   Ac       627 non-null    float64
 9   La       627 non-null    float64
 10  Br       627 non-null    float64
 11  Of       627 non-null    float64
 12  PI       627 non-null    str
dtypes: float64(10), str(3)
memory usage: 63.8 KB

## Remove redundant columns

In [25]:
columns_to_drop = [1, 2, 3, 4]
df = df.drop(df.columns[columns_to_drop], axis=1)
df.head()

,Vehicle,Value,Sp,Ha,Ac,La,Br,Of,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRRARE",5.2,4.7,3.8,4.6,3.3,5.5,C450
1,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,3.9,4.8,5.1,B540
2,"Abarth Fiat 131 1980Autoshow, Wheelspin","125,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.9,D399
3,"Abarth 595 esseesse 1968Autoshow, Wheelspin","25,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.2,D100
4,"Acura Integra A-Spec 2023Autoshow, Wheelspin, ...","36,000 CRRARE",5.7,4.7,4.2,4.2,3.7,5.5,C484

## Expand abbreviated columns

In [26]:
df = df.rename(columns={"Sp": "Speed", "Ha": "Handling", "Ac": "Accel", "La": "Launch", "Br": "Braking", "Of": "OffRd"})
df.head()

,Vehicle,Value,Speed,Handling,Accel,Launch,Braking,OffRd,PI
0,"Abarth 124 Spider 2017""Hard to Find""","250,000 CRRARE",5.2,4.7,3.8,4.6,3.3,5.5,C450
1,"Abarth 695 Biposto 2016""Hard to Find""","250,000 CRCOMMON",4.9,5.3,4.7,3.9,4.8,5.1,B540
2,"Abarth Fiat 131 1980Autoshow, Wheelspin","125,000 CRCOMMON",4.3,4.1,4.1,3.9,3.2,5.9,D399
3,"Abarth 595 esseesse 1968Autoshow, Wheelspin","25,000 CRCOMMON",2.6,3.7,1.7,2.6,2.0,5.2,D100
4,"Acura Integra A-Spec 2023Autoshow, Wheelspin, ...","36,000 CRRARE",5.7,4.7,4.2,4.2,3.7,5.5,C484

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 627 entries, 0 to 626
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Vehicle   627 non-null    str
 1   Value     627 non-null    str
 2   Speed     627 non-null    float64
 3   Handling  627 non-null    float64
 4   Accel     627 non-null    float64
 5   Launch    627 non-null    float64
 6   Braking   627 non-null    float64
 7   OffRd     627 non-null    float64
 8   PI        627 non-null    str
dtypes: float64(6), str(3)
memory usage: 44.2 KB

## Remove stat columns from df_lite

In [28]:
columns_to_drop = [2, 3, 4, 5, 6, 7]
df_lite = df.drop(df.columns[columns_to_drop], axis=1)
df_lite.head()

                                             Vehicle             Value    PI
0               Abarth 124 Spider 2017"Hard to Find"    250,000 CRRARE  C450
1              Abarth 695 Biposto 2016"Hard to Find"  250,000 CRCOMMON  B540
2            Abarth Fiat 131 1980Autoshow, Wheelspin  125,000 CRCOMMON  D399
3        Abarth 595 esseesse 1968Autoshow, Wheelspin   25,000 CRCOMMON  D100
4  Acura Integra A-Spec 2023Autoshow, Wheelspin, ...     36,000 CRRARE  C484

In [29]:
df_lite[["Value", "Rarity"]] = df["Value"].str.split("CR", n=1, expand=True)
df_lite = df_lite.iloc[:, [0, 1, 3, 2]]

df_lite["Value"] = df_lite["Value"].str.replace(",", "")
df_lite["Value"] = df_lite["Value"].str.replace("?", "0")
df_lite["Value"] = df_lite["Value"].astype(int)
df_lite.head()

                                             Vehicle   Value  Rarity    PI
0               Abarth 124 Spider 2017"Hard to Find"  250000    RARE  C450
1              Abarth 695 Biposto 2016"Hard to Find"  250000  COMMON  B540
2            Abarth Fiat 131 1980Autoshow, Wheelspin  125000  COMMON  D399
3        Abarth 595 esseesse 1968Autoshow, Wheelspin   25000  COMMON  D100
4  Acura Integra A-Spec 2023Autoshow, Wheelspin, ...   36000    RARE  C484

In [30]:
df_lite[["Brand", "Vehicle"]] = df_lite["Vehicle"].str.split(" ", n=1, expand=True)
df_lite = df_lite.iloc[:, [4, 0, 1, 2, 3]]
df_lite.head()

,Brand,Vehicle,Value,Rarity,PI
0,Abarth,"124 Spider 2017""Hard to Find""",250000,RARE,C450
1,Abarth,"695 Biposto 2016""Hard to Find""",250000,COMMON,B540
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484

In [31]:
df_lite["Autoshow"] = df_lite["Vehicle"].str.contains("Autoshow")
df_lite["Hard to Find"] = df_lite["Vehicle"].str.contains("Hard to Find")
df_lite["Wheelspin"] = df_lite["Vehicle"].str.contains("Wheelspin")
df_lite["Aftermarket Car"] = df_lite["Vehicle"].str.contains("Aftermarket Car")
df_lite["Collection Journal"] = df_lite["Vehicle"].str.contains("Collection Journal")
df_lite.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Hard to Find,Wheelspin,Aftermarket Car,Collection Journal
0,Abarth,"124 Spider 2017""Hard to Find""",250000,RARE,C450,False,True,False,False,False
1,Abarth,"695 Biposto 2016""Hard to Find""",250000,COMMON,B540,False,True,False,False,False
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399,True,False,True,False,False
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100,True,False,True,False,False
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484,True,False,True,True,False

In [32]:
df_lite.info()

<class 'pandas.DataFrame'>
RangeIndex: 627 entries, 0 to 626
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               627 non-null    str
 1   Vehicle             627 non-null    str
 2   Value               627 non-null    int64
 3   Rarity              627 non-null    str
 4   PI                  627 non-null    str
 5   Autoshow            627 non-null    bool
 6   Hard to Find        627 non-null    bool
 7   Wheelspin           627 non-null    bool
 8   Aftermarket Car     627 non-null    bool
 9   Collection Journal  627 non-null    bool
dtypes: bool(5), int64(1), str(4)
memory usage: 27.7 KB

In [33]:
df_sort = df_lite[df_lite["Vehicle"].str.contains("Autoshow, Wheelspin")]
df_sort.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Hard to Find,Wheelspin,Aftermarket Car,Collection Journal
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399,True,False,True,False,False
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100,True,False,True,False,False
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484,True,False,True,True,False
6,Acura,"RSX Type S 2002Autoshow, Wheelspin, Aftermarke...",18000,COMMON,C462,True,False,True,True,False
7,Acura,"Integra Type R 2001Autoshow, Wheelspin",25000,COMMON,C471,True,False,True,False,False

In [34]:
df_sort.info()

<class 'pandas.DataFrame'>
Index: 397 entries, 2 to 626
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               397 non-null    str
 1   Vehicle             397 non-null    str
 2   Value               397 non-null    int64
 3   Rarity              397 non-null    str
 4   PI                  397 non-null    str
 5   Autoshow            397 non-null    bool
 6   Hard to Find        397 non-null    bool
 7   Wheelspin           397 non-null    bool
 8   Aftermarket Car     397 non-null    bool
 9   Collection Journal  397 non-null    bool
dtypes: bool(5), int64(1), str(4)
memory usage: 20.5 KB

In [35]:
#df_sort = df_sort.sort_values(["Vehicle", "Value"], ascending=[True, True])
df_sort = df_sort.sort_values(["Brand", "Value"], ascending=[True, True])
df_sort = df_sort[df_sort["Value"] <= 500000]
df_sort.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Hard to Find,Wheelspin,Aftermarket Car,Collection Journal
3,Abarth,"595 esseesse 1968Autoshow, Wheelspin",25000,COMMON,D100,True,False,True,False,False
2,Abarth,"Fiat 131 1980Autoshow, Wheelspin",125000,COMMON,D399,True,False,True,False,False
6,Acura,"RSX Type S 2002Autoshow, Wheelspin, Aftermarke...",18000,COMMON,C462,True,False,True,True,False
7,Acura,"Integra Type R 2001Autoshow, Wheelspin",25000,COMMON,C471,True,False,True,False,False
4,Acura,"Integra A-Spec 2023Autoshow, Wheelspin, Afterm...",36000,RARE,C484,True,False,True,True,False

In [36]:
df_sort.info()

<class 'pandas.DataFrame'>
Index: 334 entries, 3 to 623
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               334 non-null    str
 1   Vehicle             334 non-null    str
 2   Value               334 non-null    int64
 3   Rarity              334 non-null    str
 4   PI                  334 non-null    str
 5   Autoshow            334 non-null    bool
 6   Hard to Find        334 non-null    bool
 7   Wheelspin           334 non-null    bool
 8   Aftermarket Car     334 non-null    bool
 9   Collection Journal  334 non-null    bool
dtypes: bool(5), int64(1), str(4)
memory usage: 17.3 KB

In [37]:
df_sort.to_csv(filename + "-sorted" + ".csv", index=False)

In [38]:
df_lite.to_csv(filename + ".csv", index=False)

In [39]:
df_wheelspin = df_lite.loc[(df_lite["Autoshow"] == False) & (df_lite["Wheelspin"] == True)]
df_wheelspin.head()

,Brand,Vehicle,Value,Rarity,PI,Autoshow,Hard to Find,Wheelspin,Aftermarket Car,Collection Journal
21,Apollo,Intensa Emozione 2019Wheelspin,3200000,LEGENDARY,R916,False,False,True,False,False
27,Aston,Martin Valhalla Concept Car 2019Wheelspin,1150000,LEGENDARY,R960,False,False,True,False,False
28,Aston,Martin DBS Superleggera 2019Wheelspin,275000,EPIC,S1736,False,False,True,False,False
57,Audi,Sport quattro 1983Wheelspin,650000,EPIC,B526,False,False,True,False,False
62,Bentley,Bentayga 2016Wheelspin,250000,EPIC,A612,False,False,True,False,False

In [40]:
df_wheelspin.info()

<class 'pandas.DataFrame'>
Index: 46 entries, 21 to 624
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               46 non-null     str
 1   Vehicle             46 non-null     str
 2   Value               46 non-null     int64
 3   Rarity              46 non-null     str
 4   PI                  46 non-null     str
 5   Autoshow            46 non-null     bool
 6   Hard to Find        46 non-null     bool
 7   Wheelspin           46 non-null     bool
 8   Aftermarket Car     46 non-null     bool
 9   Collection Journal  46 non-null     bool
dtypes: bool(5), int64(1), str(4)
memory usage: 2.4 KB